### ISSUE TITLE
Support GeoJSON files?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#100]
Several processes such as load_collection, aggregate_polygon, filter_polygon etc support GeoJSON as data type for one of their parameters. It could be useful to support simply referring to a file as in the run_udf process:

```json
                {
                    "description": "Path to an GeoJSON file uploaded to the server.",
                    "type": "string",
                    "subtype": "file-path"
                },
```

Or do you think it's enough to let clients load the files and then send it in the process graph? Does it make also sense for very large GeoJSON files?

**Comment by jdries** [comment]
In our backend we do this using the read_vector process:
http://openeo.vgt.vito.be/openeo/0.4.0/processes/read_vector
but this no longer seems to be officially supported, or never was?

**Comment by m-mohr** [comment]
There was never a process read_vector. I guess we could solve this also with #83 instead of defining a special case for GeoJSON.

**Comment by jdries** [comment]
In #83, we're mostly talking about loading raster data. It is indeed very similar, but having a separate process per type of data might make sense, otherwise we'd have a process with multiple return types?

**Comment by m-mohr** [comment]
load_collection also returns either vector or raster at the moment, I think that's fine. I don't think we should define all the load/import processes twice for vector and raster or is there any good reason to keep them separate?

**Comment by m-mohr** [comment]
Let's try to use #106 instead of specifying a special case to load GeoJSON from user-uploaded files.
