### ISSUE TITLE
Invert mask

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#103]
The mask process allows polygons to be passed as mask, in which case the pixels covered by the polygons are masked out (replaced with replacement value):

> All pixels for which the point at the pixel center intersects with the corresponding polygon (as defined in the Simple Features standard by the OGC) are replaced.

(from https://openeo.org/documentation/0.4/processes.html#mask)

Wouldn't it be useful as well to have an option to flip this behaviour: preserve the pixels that are covered by any of the polygons and replace the "outside" of the polygons. (This would actually be my intuitive expectation of how this process would handle polygons by default)

**Comment by m-mohr** [comment]
Sounds useful. I guess the parameter should also apply to the other options of `mask`.

**Comment by soxofaan** [comment]
indeed (and actually, my intuition would expect that flipped behavior to be the default for raster masks as well, but maybe it's an EO convention I'm not used to yet)

**Comment by lforesta** [comment]
We could also use the process "not" to invert the mask, but it's a bit clearer if this behavior can be defined directly when calling "mask".

**Comment by soxofaan** [comment]
> We could also use the process "not" to invert the mask, 

But that wouldn't work for a polygon (GeoJSON) based mask, right?

**Comment by m-mohr** [comment]
It would, but with more steps: Create mask from GeoJSON, apply `not` on all pixels in mask, apply mask on original data.
That's not very intuitive and I agree that there should be a more user-friendly option for it.

**Comment by m-mohr** [comment]
There's now PR #110 to implement this proposal. @soxofaan

**Comment by m-mohr** [comment]
Has been merged. Is now available in mask_polygon.
