### ISSUE TITLE
Fix filters

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#104]
Currently, the property filters (e.g. `filter` or `properties` in `load_collection`) is completely broken as there's no way to properly reference the metadata fields and also the type "boolean" for expression elements doesn't really reflect that you can insert processes returning a boolean.

How I could imagine it working in the future: https://github.com/Open-EO/openeo-processes/issues/84#issuecomment-565395003

**Comment by lforesta** [comment]
> the property filters (e.g. filter or properties in load_collection)

"filter" here is the process filter? I thought this process does not work on metadata but on pixel values?

**Comment by m-mohr** [comment]
`filter` (and `filter_*`) are working on dimension labels, not pixel values.
The parameter `properties` in `load_collection` is working on metadata.
I didn't made this clear in the initial post. Anyway, there's no way to reference the dimension labels/metadata fields, which is an issue at the moment.

**Comment by m-mohr** [comment]
Closing as duplicate of #84
