### ISSUE TITLE
import_*: Import data from non-API sources

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#105]
This originates from #83: There are probably several processes, which could be useful to import data from "non-API" sources, similarly to `load_uploaded_files`. Some ideas:
* `import_s3`: Load data from Amazon S3 (see [example in #83](https://github.com/Open-EO/openeo-processes/issues/83#issuecomment-540573097))
* `import_nfs`: Import from a network file storage system attached to the back-end. Example from VITO: [load_disk_data](http://openeo.vgt.vito.be/openeo/0.4.0/processes/load_disk_data)
* `import_stac`: Import from a STAC catalog/API
* `import_external_result`: Import a openEO job result from another back-end
* and more (GCS, Azure, ...)

Similarly, there could be export_* processes at some point.

**Comment by lforesta** [comment]
I like the idea. Maybe we could write explicitly in their description that these processes may require a significant (and possibly slow) data transfer. This may not be clear to non-technical users.

**Comment by m-mohr** [comment]
More or less encapsulates too many different new processes. There are some separate issues for such processes, e.g. #322
