### ISSUE TITLE
Tile-based processing

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#108]
Originated from #102:

@lforesta wrote [here](https://github.com/Open-EO/openeo-processes/pull/102#discussion_r358688710): 
> Suppose a group working on algorithms which are entirely scene based (i.e. processing rasters independently); with S2 they might be happy (or even prefer) that the output has the same CRS as the original raster, but with this approach, to achieve their goal they would need to submit one job for each CRS.

@m-mohr wrote:
> There are no scenes (= granules) in the openEO world, but if a back-end gives users information on scenes and users would want to work on them individually, then I would expect that each scene is an individual data cube. That means crs doesn't need to be set in load_collection (1 scene = 1 crs) and they can work with the original crs until they want to merge and need to resample to a common crs. You can easily use multiple load_collection in a process graph and re-use algorithms with stored process graphs, so it's not necessarily one job for each crs.
>
> The back-end only throws the error if the data requested hast multiple crs assigned. If you load data from a single crs although the collection has multiple crs assigned, you don't need to throw an error. Only if you load data over a region that has multiple crs assigned, you need to make clear what the target crs is. It just needs to be unambiguous.
> 
> I think this makes sense, no?

@lforesta wrote:
> Ok never mind the scenes/granules. If my processing is pixel based (i.e. every pixel can be processed completely independently from others), it does not matter that my datacube has multiple CRS or one only. Clearly I'm thinking of a loose datacube, but I think there are people who work with applications of this type. For example, groups doing research on processors from L1 to L2, often they process data on a pixel level. Say I'm one such group and I want to create my S2-L2 product for an entire continent by using an openEO compliant back-end. I could do:
> ```
> load_collection(S2, bbox=full-continent)
> apply(my_UDF) # the UDF may be a set of standard processes
> save_raster
> ```
>
> If I'm forced to specify a unique CRS for this example, the back-end will have to reproject lots of data, although the group in this case is maybe happier to have the original UTM tile structure preserved (data like this is then used by other groups to do further processing, they will make sure it's all in the projection they want to use).
>
> In this example, to achieve the same without reprojecting, either I create one job per CRS or within the same job I call load_collection multiple times with different bbox defined, right? This seems a lot of overhead for "keeping the original projection".
>
> Anyway, maybe this is a corner case and in any case there are ways to create jobs where the original multiple CRSs are kept (paragraph above). I just wanted to point out example(s) where this PR may not be optimal. 

@m-mohr wrote:
> I'm not sure how your example would work with save_result. How would a data cube of a whole continent be stored? When saving, the save_result process doesn't know any longer the original files and thus can't save it to the original tile structure. Maybe some back-ends can do that, but user can't expect that to happen on all back-ends. So this use case doesn't even work without having this PR merged, I think. I don't think your use case can currently be tackled very well in openEO. I guess we would need a process that can load individual tiles into individual data cubes for that, e.g. load_tiles() which returns an array of data cubes and then we'd need an array_each process so you can apply a "callback" on each data cube and save them individually.

**Comment by lforesta** [comment]
>  How would a data cube of a whole continent be stored? When saving, the save_result process doesn't know any longer the original files and thus can't save it to the original tile structure.

I think this depends on the implementation, in general a back-end should have knowledge about this. The back-end would save files in the way specified on the /output_files endpoint (we discussed this in another issue that I can't find at the moment). One common option would be to save one file per timestamp, which relates to individual input files usually.

About the process idea, are you thinking of UTM tiles? Or how would you specify the tile otherwise?

**Comment by jdries** [comment]
We also have this use case where users would like their output to be in the Sentinel-2 tiling grid. 
I'm not there yet, but probably going to use some parameter in save_result to specify this. This is again a case that I'd like to try out in an implementation first before standardizing it.

**Comment by m-mohr** [comment]
@lforesta Not sure, weren't you speaking about the original granules as originally published on OpenSciHub etc? I was speaking about them, but maybe you are speaking about other things?

**Comment by lforesta** [comment]
Yes I was thinking of those although if we define a process it could be more general (or have a more specific name).
But I agree with @jdries and maybe leave this for the moment. We can discuss this more in detail when we have some real cases in mind I guess.

**Comment by m-mohr** [comment]
That's why it is not part of the next milestone here. ;-)

**Comment by kempenep** [comment]
I have the feeling that we have two fundamentally different views here on a data cube.
One approach is a loose representation of a (filtered) collection on which a processing steps can be applied. Clearly, there can be multiple CRS contained in a collection. The result is also a collection that can contain multiple CRS..

The other approach is a more strict definition of a data cube that has a well defined spatial and temporal resolution in a single CRS. My understanding was that after "load_collection" we would obtain such a data cube. In fact, I do not see the need for the "load_collection" in the first approach.

I can see the benefit of both approaches, and I do support them in our back-end if needed (clearly not all processes implemented yet).
In the first approach, I implement the processing steps as methods of a (filtered) Collection class (there is no need for load_collection). This is typically a file based processing. In the second approach, I first perform a load_collection and obtain a well defined data cube object (typically in memory, or in some Dask xarray representation). In this approach, processing steps are implemented as methods of the data Cube class.

Backends will each have their own approaches, but I think we need to agree on the terminology of a data cube. If we have different interpretations, our users will be lost (and we will loose our users).

**Comment by m-mohr** [comment]
Yes, I agree @kempenep. I designed API and processes based on your "strict definition of a data cube".

**Comment by lforesta** [comment]
@kempenep do you also have (force?) a uniform resolution in time? Typically, EO data will be non-uniform in this dimension, no?

**Comment by kempenep** [comment]
@lforesta good point. To my understanding a data cube should have indeed a regular grid in both space and time. Currently I represent the data cube as sparse in time. However, the grid parameters for time and space are member attributes of the data cube, so we can always explode the sparse matrix if needed.

**Comment by m-mohr** [comment]
@edzer Here are some points to consider for your data cube definition in the glossary. :-)

**Comment by lforesta** [comment]
If we want to define the full grid of the datacube correctly from a mathematical standpoint, we need to define that for each dimension (whereas we tend to think about this only for the two spatial dimensions). Time is often sparse, spectral bands are as well, etc..
But if we want to define the whole grid (for each dimension), this becomes quite cumbersome for users I think. And it may introduce some interpolation/extrapolation if they define a regular grid for the time dimension without knowing yet which data is in the cube.

I'm not advocating for this, but if we don't do that I think the datacube will still be loosely rather than strictly defined.

**Comment by m-mohr** [comment]
Related to #98. Tile (identifier) could be a dimension.

**Comment by jdries** [comment]
For reference, this is how Sentinelhub allows output tiling grids to be defined:
https://docs.sentinel-hub.com/api/latest/api/batch/#tiling-grids
Problems here:
- the resolution is part of the grid definition, whereas openEO defines it by resampling operations
- the grids are referenced with simple numerical id's (0,1,2), maybe an actuall name is better?
We do however need to map this in openEO, because we want to be able to forward data from Sentinelhub, without requiring heavy reformatting. (That would incur an unneeded cost IMO).

**Comment by m-mohr** [comment]
We are mixing issues here, I think. This issue was meant to be for tile-based processing, but tiling for saving is a different topic, isn't it? While the processes can solve tile-based processing, the tiling on save has to be specified in /file_formats and is basically a back-end choice. We can and should probably agree on a common option that we expose via /file_formats, but that's better started off and discussed in Platform.

**Comment by m-mohr** [comment]
Stale, not part of openEO, I think.
