### ISSUE TITLE
Can we support pickled Python code instead of uploading scripts separately? 

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#11]
Using the cloudpickle module, we can pickle a python lamba or function on the client side, and send it to the backend for execution. This simplifies things for the user, as he doesn't have to explicitly create processes by uploading scripts.
Is this something we can support?
Not sure to what extent Python version in client and backend have to be aligned in order for this to work.
My current client implementation will be at least Python 3.5.

**Comment by m-mohr** [comment]
@jdries Do we still need support for pickled Python code now that we have support to generally insert a python script to the `run_udf` process? See https://open-eo.github.io/openeo-api/v/0.4.0/processreference/#run_udf

**Comment by jdries** [comment]
Pickled code still has some important advantages, but I would close this issue for now. Let's try to work with the current proposal first!
