### ISSUE TITLE
aggregate_spatial: Statistics for more than one dimension?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#126]
@mkadunc wrote in https://github.com/Open-EO/openeo-processes/pull/123#discussion_r367501563 regarding aggregate_polygon: 

> Why are we limiting this to one remaining dimension - e.g. why not get statistics over space for each (time,band) combination?

**Comment by m-mohr** [comment]
Postponing to 1.0-final if there's no veto...

**Comment by m-mohr** [comment]
Hey @jdries , you were talking about aggregate_polygon today and it seems you are invested most into this process. What do you think about this? Ever stumbled across a need for this with your use cases?

**Comment by jdries** [comment]
Yes, we actually do retain the band dimension as well, so you can get a 'multiband' aggregated time series. This is maybe not compliant with the current spec, strictly speaking?

**Comment by m-mohr** [comment]
Sounds like that. Should we adopt the specification of aggregate_spatial (fka aggregate_polygon)?

**Comment by clausmichele** [comment]
@m-mohr Rising up this issue. Why don't we make available aggregate_spatial over the full spatial dimension instead of a polygon? Defining the polygon is cumbersome compared to get the statistics over the area I've already carefully selected. Like a resampling with the target size as 1 pixel in spatial domain.

**Comment by m-mohr** [comment]
@clausmichele That seems to be a different issue, right? For your usecase you'd usually do a reduce, but that doesn't really work as you have two spatial dimensions instead of one.

**Comment by clausmichele** [comment]
exactly, but since I see that we can't use reduce_dimension with the two spatial dimension at the moment, I thought we could use aggregate_spatial instead.

**Comment by soxofaan** [comment]
<ping>


In the mean time, we actually have a couple of example notebooks, demo's and videos (against the VITO backend) that illustrate this 'multiband' aggregated time series feature, which is strictly speaking violating the spec.

**Comment by m-mohr** [comment]
This will be implemented in 2.0.0. See #382
