### ISSUE TITLE
Add process graph examples

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#136]
Many processes lack examples as it wasn't really possible to find small, self-contained examples yet. Due to the changes for https://github.com/Open-EO/openeo-api/issues/161 we can do that much better now and collect and add more examples.

**Comment by soxofaan** [comment]
Agreed. While working on 1.0.0 support on python client, this was one of the things that I missed from current docs.

**Comment by m-mohr** [comment]
That's the task of the whole consortium. We started from scratch so there are not a lot of process graphs and we - University of Münster - don't have the strongest background in remote sensing and data processing. So we depend on the real world use cases and process graphs all of you come up with. If you have anything to share, please post them at https://openeo.org/documentation/1.0/developers/examples/ or do PRs against this repo for individual processes. With 1.0 there are some general examples in some of the processes already (see #137).

**Comment by soxofaan** [comment]
For what it's worth: we have a couple of examples for the unit tests of the python client at 
https://github.com/Open-EO/openeo-python-client/tree/master/tests/data/1.0.0

Note however, the current version in master is not fully 1.0.0 valid. I'm working on better 1.0.0 support in a feature branch at the moment, but I hope to merge this somewhere this week:
https://github.com/soxofaan/openeo-python-client/tree/EP-3251-graph-building/tests/data/1.0.0

**Comment by m-mohr** [comment]
That's a good resource, but I'm not going through the repos and scrap examples from there as I'm not sure what helps and what doesn't. For example, the eq examples are probably not needed, there are good non-process-graph examples in the json. merge_cubes might be interesting, but I'd like to encourage you that you do PRs or more concrete requests once there are open questions so that we can add only what really needs to be improved for the sake of time.

**Comment by m-mohr** [comment]
There's an examples folder where we can add additional examples. All the examples there should be referenced from at least one process.

**Comment by soxofaan** [comment]
https://github.com/Open-EO/openeo-processes/blob/1645b9719da12c30ac6f660e7ab006540c989764/array_apply.json#L88-L101

These  references have `../draft/..` in their href, isn't that going to cause issues/confusion once that is merged in master? Or are you planning to rewrite all these urls after merging in master?
Wouldn't it be better to use a version instead of a branch name? e.g. `../1.0.0/...` or even without patch component: `1.0`.

**Comment by m-mohr** [comment]
Before merging, I replace all version numbers (here: draft). Even with a version number you still need to rename them later so there's no real win.

**Comment by soxofaan** [comment]
>  so there's no real win

a slight improvement would be that version numbers carry a meaning on the level of the API itself, while branch names are just implementation details.

**Comment by m-mohr** [comment]
I don't get that point. Draft versions are not meant to be exposed via API anyway. And having future version numbers in there breaks the draft docs.

**Comment by m-mohr** [comment]
The examples are not really bound to a release and can be added later, too.
