### ISSUE TITLE
array_count?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#138]
While working on #137, I found that it could be useful for several use cases to have an operation that returns the number of elements in a list, similarly to the existing count process for data cubes.

Some use cases: 
- Count the number of elements in a time series when no data is ignored
- Compute mean, sd, variance etc. Every formula that computes something like `1/n * func(...)` (n = number of elements) or so.

Side note: Having that said, we could "save" (i.e. remove) quite a lot of processes if we change arrays to be 1D datacubes.

**Comment by mkadunc** [comment]
👍 on the side note

**Comment by mkadunc** [comment]
(how about changing scalars to be 0D datacubes :) ?)

**Comment by mkadunc** [comment]
Don't we already have this - https://open-eo.github.io/openeo-api/processreference/#count ?

**Comment by m-mohr** [comment]
> similarly to the existing count process for data cubes.

@mkadunc Yes, that's what I meant above. But that's only defined for data cubes, not arrays.
I guess we need a separate issue for array -> data cube conversion. Feel free to open for for 0D data cubes, hehe. Not sure how long it survives though...  ;-)
