### ISSUE TITLE
One dimensional data cubes instead of arrays?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#139]
Originates from #138: We have quite a lot of processes defined for arrays which duplicate processes we also have for data cubes. We could "save" (i.e. remove) quite a lot of processes if we change arrays to be 1D datacubes. This should be explored, I see some pros and cons for that...

**Comment by soxofaan** [comment]
Could you list some examples?

**Comment by m-mohr** [comment]
Examples for? All processes that work on arrays basically, e.g. `mean(array data, boolean ignore_nodata)` could be `mean(raster-cube data, boolean ignore_data)` with the restriction in the docs that data needs to be a 1D data cube always. 

Nevertheless, keep in mind that this is in the milestone "future", which means implementation only "after the project ends" and therefore not anytime soon.

**Comment by soxofaan** [comment]
FYI: in Python's numpy (which is a well known reference for probably large part of openEO audience I guess) aggregation functions like `mean` work on all dimensions at once by default (so `mean(3D array) -> scalar`). If a user wants to apply it to just one dimension (`mean(3D array) -> 2D array`), they have to specify the dimension (`axis=1` or something alike).
For example see: https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html

So in this sense it could be even possible to drop this "... data needs to be a 1D data cube always"  constraint

**Comment by m-mohr** [comment]
Not sure how numpy works exactly, but I tried to avoid mixing data cube logic and processing logic in processes as far as possible so that we don't need to define common things over and over again (like `keepdims` and `axis` in numpy mean). Either a process manages the data cube (e.g. apply, reduce) or processes data (e.g. mean, normalized_difference). Not sure whether we should make the quite simple processes like mean more complicated.

**Comment by soxofaan** [comment]
Indeed, dragging in additional argument/option boilerplate for all these process is not ideal. Not only for API maintenance but also client maintenance.

On the other hand you could say: processes like `mean` always work across all dimensions of given cube (no `axis` argument in process definition). If users wants to only apply it to one dimension, they can use `reduce_dimension` with a `mean` "callback". So that keeps API simple and generic, while user/client can still achieve either goal (scalar mean or single dimension mean-reduction).

**Comment by jdries** [comment]
For me, an important distinction is that datacubes are potentially very large, so indeed require things like 'reduce_dimension_binary' to correctly specify the intent. An array is for me a smaller thing, so you can indeed do mean for an array.
So I'd say we should keep it as-is. (Or I don't see the use case yet.)

Functions that do make sense on a full datacube should specify so explicitly.

This also avoids ending up with an API that is so generic that it becomes hard to implement entirely.

**Comment by m-mohr** [comment]
The issue is that array are not specified to be small, i.e. an array passed in apply_dimension or reduce_dimension can be pretty large. For reduce_dimension there's the binary counterpart, but that's not true for all processes although for all other processes you can likely "stream" the values (process in chunks) better than in reducers.

The main driver behind the proposal is that one-dimensional arrays are already supported by all the cube-related processes and the array_* processes basically duplicate all the cube definitions so in the end we could reduce the spec by a couple of processes.

**Comment by m-mohr** [comment]
I don't see this happening in the near future, so closing for now.
