### ISSUE TITLE
resample_* confusion

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#146]
While working on 1.0.0 support in python client, I stumbled upon these processes:

- `resample_cube_spatial(raster-cube:object data, raster-cube:object target, ?string method) : raster-cube:object` 
    Resamples the spatial dimensions (x,y) from a source data cube to a target data cube and return the results as a new data cube.
- `resample_cube_temporal(raster-cube:object data, raster-cube:object target, process-graph:object method, ?string|null dimension, ?any context) : raster-cube:object`
    Resamples a temporal dimension from a source data cube to a target data cube and return the results as a new data cube.
- `resample_spatial(raster-cube:object data, ?mixed resolution, ?mixed projection, ?string method, ?string align) : raster-cube:object`
    Resamples the spatial dimensions (x,y) of the data cube to a specified resolution and/or warps the data cube to the target projection. At least resolution or projection must be specified.

Some notes:
- from quick glance, it is not obvious how to choose between `resample_cube_spatial` and `resample_spatial`. It would help if both would reference each other, explaining when to pick one or the other
- the ".. to a target cube and return the results as a new data cube" in `resample_cube_spatial` and `resample_cube_temporal`  is somewhat confusing. Suggestion (assuming I understand what is meant): " .. resamples the ... dimension from a source  data cube to align with the dimensions of the given target data cube and return ..."

**Comment by m-mohr** [comment]
1. Agreed, will add the cross-references.
2. Sounds alright. I'll make a PR and let you review.
