### ISSUE TITLE
apply: clarify dimensions parameter

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#15]
For the 'apply' process https://open-eo.github.io/openeo-api/v/0.4.0/processreference/#apply
I don't really know what to do with the dimensions parameter. I get it in the context of 'reduce/aggregate' process, but not in the sense of apply to each pixel?
I'm guessing our intention was to be able to apply a process to a single spectral band of a multi-band data-cube, which makes sense. I'm not sure it would make sense to make it generic, like applying a function only to pixels with a specific coordinate on the X-axis...

**Comment by mkadunc** [comment]
Agree that this is unclear - maybe the parameter was an attempt to merge `apply` with `apply_dimensions` - in this case we'd have only `apply`, which could be used in both ways:
- without the `dimensions` — the callback would be applied on atomic scalar values, called `w * h * t * b` times
- with the `dimensions` parameters — the callback would be called with appropriate slices of the cube as input, for example:
   - all bands in a pixel - input shape is `[b]` and it would be called `t * x * y` times
   - per-timeslice for separate bands - input shape is `[h][w]` and it's called `b * t` times
   - whole timeslice, all bands - input shape is `[h][w][b]` and it's called `t` times
   - per-pixel timeseries of a individual bands - input shape is `[t]` and it's called `w * h * b` times
   - per-pixel timeseries of all bands - input shape is `[t][b]` and it's called `w * h` times

**Comment by jdries** [comment]
Ok, this explanation clarifies it. And I assume the shape of the output is the same as the shape of the input?

**Comment by m-mohr** [comment]
It's a left-over I forgot to remove after I introduced `apply_dimension` recently. I'll remove the `dimensions` parameter from `apply`.
