### ISSUE TITLE
Support applying a process to a neighbourhood of pixels

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#154]
Use case: run a machine learning model that works on 128x128 'patches' or 'tiles' of EO data, and retain only the 64x64  inner pixels as a result. So the resulting datacube is the combination of these 64x64 results, that can be computed in parallel.

Possible solution:
This sounds like an apply_dimension, but:
- x and y are separate dimensions, while we want to work on both of them
- it is not necessary to work on the 'full' space dimension, this could be very large, we simply want a small window

So:
- allow specifying more than one dimension in apply_dimension?
- or create a separate function to work on a 'window' of data. Where the extent and overlap of windows needs to be specified for each dimension. 

So my window would be:

1. all bands
2. 64 pixels along x and y, padded with 32 pixels on each side
3. 1 date

Similar function in xarray:
First 'chunk' the dataset:
http://xarray.pydata.org/en/stable/generated/xarray.Dataset.chunk.html
Then apply function to each chunk:
http://xarray.pydata.org/en/stable/generated/xarray.map_blocks.html

But also rolling:
xarray.DataArray.rolling

In fact I believe I need a combination of rolling and chunking in my use cases. Rolling provides the ability to 'pad' data in space and time, chunking allows me to for instance specify that I want to transform 64x64 tiles.

Earth Engine has this creative solution:
ee.Image.neighborhoodToBands
Which would help in some cases: for a time window, we could add the required dates as bands, maybe even in a udf. Then a reduction of the bands dimension would also have temporal info.

**Comment by m-mohr** [comment]
Isn't that exactly a use case for apply_kernel? Although I acknowledge that the `kernel` array is getting pretty large.

**Comment by jdries** [comment]
It's certainly related to apply_kernel, but that process is restricted to 2D convolutions, while I want to do a more generic transformation. So I would maybe not overload apply_kernel with this behavior.

**Comment by m-mohr** [comment]
I think it was supporting your usecase in 0.4, but we restricted it for 1.0 (can't remember why).

I'm still not 100% sure what is missing from apply_kernel so maybe you could propose a draft process in a PR? We could discuss that in the next dev meeting or so. I feel like it should be a separate process to also not overload apply_dimension.

**Comment by jdries** [comment]
I added a pull request for a 'chunk' process. Advantage is that we do not need to modify/overload existing processes.
Disadvantage is that people may expect chunking to have an effect on certain other processes, that we did not or do not foresee ourselves. So we'll need to try and document this.

**Comment by m-mohr** [comment]
I'm just wondering: 
1. Would apply_neighbourhood also need a border parameter like apply_kernel?
2. We should rename neighbourhood to neighborhood. We use American English in process names AFAIK and removing the u makes the word comply to AE (and easier to write?)

**Comment by jdries** [comment]
There's something to say for adding a border parameter, although less relevant compared to apply_kernel: this function will mostly be used with UDF's, so it's a lot easier for users to implement their own gap filling scheme. IMO default behaviour should remain to fill gaps with nodata.
Renaming to AE is fine.

**Comment by m-mohr** [comment]
So should we just say that missing values at the borders are always filles with nodata/null? 
I'll do the rename then.

**Comment by m-mohr** [comment]
This has now been merged and is scheduled to be released in 1.0.0.
