### ISSUE TITLE
raster <-> vector processes

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#155]
For an internal use case, we'd like to apply raster to vector conversion:
1. input is a raster datacube
2. output is a 'vector datacube'  that can be exported as geojson

This is not uncommon, so we'd like to see if we can provide this as higher level process. 
We will probably implement something internally first, to see how it can look like.

**Comment by m-mohr** [comment]
As soon as you have a process definition I'd suggest to open a draft PR so that we can shape it together.

**Comment by jdries** [comment]
Some inspiration for naming:

- GDAL has gdal_polygonize
- GEE has reduceToVector, and also has behaviour for the multiband case https://developers.google.com/earth-engine/reducers_reduce_to_vectors
- GRASS GIS has r.to.vect https://grass.osgeo.org/grass78/manuals/r.to.vect.html

**Comment by m-mohr** [comment]
Can we model this as reducer in openEO? If not, reduce would be a bit confusing, I think. polygonize only works if it's always working on polygons only. I think I'd prefer something easy to understand and aligned with other processes such as `create_raster_cube` like `vector_cube`, `to_vector` or `convert_cube`. I'm not set on anything yet.

**Comment by m-mohr** [comment]
@jdries We should complete the description and PR it for discussion.

**Comment by PondiB** [comment]
@jdries  and @m-mohr, is this being worked on?

**Comment by m-mohr** [comment]
VITO has an example implementation, but we still need to get a version into openeo-processes. @PondiB

**Comment by PondiB** [comment]
Cool, I will pick it up then.

**Comment by m-mohr** [comment]
Cool, please consider a survey of existing implementations, e.g. at VITO (already openEO), GRASSGIS, Python ecosystem (shapely?), R, ... @PondiB

**Comment by PondiB** [comment]
@m-mohr , Sure, will do that.
