### ISSUE TITLE
Allow udf-based transforms of vector data

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#156]
In processes like filter_spatial:
https://openeo.org/documentation/1.0/processes.html#filter_spatial

users can now specify a geojson object. In a number of cases, users want to transform a geometry before applying it. Currently, we often do this client-side, but this is less convenient when the geometry is an input parameter of a stored process. (Basically the process would be less self-contained.)

We do not yet have vector processes, but we do have run_udf, and the python UDF api specifies support for feature collections. So all that's needed seems to be that we extend the type of the geometries parameter in filter_spatial, to also allow callbacks?
This way we can start with simple support for vector data, without going into a full set of vector processes.

**Comment by m-mohr** [comment]
To me it feels like overloading the process a bit too much. Actually, we tried to not put callbacks and other data types into one parameter with 1.0. It could be a separate process, I think. Although I'm not quite understanding the exact use case. Could you give an example of an UDF? What would that UDF do? What's the difference to just making the filter_spatial in the UDF?

> Currently, we often do this client-side, but this is less convenient when the geometry is an input parameter of a stored process. (Basically the process would be less self-contained.)

Wait, I don't quite get that. What's the issue here?

**Comment by jdries** [comment]
Let me try to explain it better through the use case:
we're building a web service that allows a user to specify a point of interest, and will search for a 'parcel' in the neighborhood of that point. We're trying to do the full implementation through openEO, so no 'wrapper' web service for preprocessing of input parameters or postprocessing of the result. So the webservice call will be an openEO '/result' call and the process graph will reference a 'stored' user process graph, as we don't want to send along the full process graph.

A concrete example of preprocessing parameters in this case, is to convert the point into a bounding polygon of size X, around the point. And that logic should somehow go into the process graph. Hence my idea to allow callbacks.

Actually, by doing this use case, I'm starting to see a broader patter where every process parameter/variable that's now a constant could in fact also be a callback. This brings us a step further to have complete processing workflows encoded in the process graph.

Note that I'm happy to experiment with this further in our backend a bit, but it's important to check if supporting this would be somehow possible without breaking backwards compatibility with 1.0.

**Comment by m-mohr** [comment]
Thanks for clarifying. I think I understand a bit better, but I'm still not 100% sure why you need a callback. What would the filter_spatial process pass as parameter to the callback? If it is the raster-cube, why isn't this just another node on the same level as filter_spatial? Something like this (replace filter_bbox with filter_spatia, was just not available at the back-end):
![image](https://user-images.githubusercontent.com/8262166/84482312-cac26c80-ac97-11ea-9b86-7e0a2dd381e7.png)

**Comment by jdries** [comment]
Just wrote a sample to demonstrate my idea, the Python client code is a bit rough, as it's not really supported, but the process graph looks like this:
```
{
        'filterspatial1': {
            'arguments': {
                'data': {'from_node': 'loadcollection1'},
                'geometries': {'from_node': 'runudf1'}
            },
            'process_id': 'filter_spatial',
            'result': True
        },
        'loadcollection1': {
            'arguments': {
                'id': 'S2',
                'spatial_extent': None,
                'temporal_extent': None
            },
            'process_id': 'load_collection'
        },
        'runudf1': {
            'arguments': {
                'data': {'features': [{'geometry': {'coordinates': [125.6,10.1],'type': 'Point'},'type': 'Feature'}],'type': 'FeatureCollection'},
                'runtime': 'Python',
                'udf': 'def transform_point_into_bbox(data:UdfData): blabla'
            },
            'process_id': 'run_udf'}
        }
```

**Comment by m-mohr** [comment]
That's exactly what's shown above in my image and doesn't need any callbacks or so. That's supported already (and if not it's a bug in the implementation ;-) )

**Comment by jdries** [comment]
Also managed to render this:
![image](https://user-images.githubusercontent.com/5937096/84490158-09115900-aca3-11ea-890a-08aa35aae83c.png)

So that's good news, just means I indeed have to check my backend :-).
Can you confirm that this is the part of the spec that  basically allows this:
![image](https://user-images.githubusercontent.com/5937096/84490573-a3719c80-aca3-11ea-80a5-8cb6e0895d14.png)

**Comment by m-mohr** [comment]
> So that's good news, just means I indeed have to check my backend :-).

Great!

> Can you confirm that this is the part of the spec that basically allows this:
> ![image](https://user-images.githubusercontent.com/5937096/84490573-a3719c80-aca3-11ea-80a5-8cb6e0895d14.png)

No, that's not it. It's this:

![image](https://user-images.githubusercontent.com/8262166/84491289-9acd9600-aca4-11ea-941d-ec6d1f20dfbf.png)

Your snippet shows that { from_node: ... } etc can also be part of an array and thus parsers need to dive deep into all arguments ;-) For example (not the most meaningful though), you could actually do this, too:
```
{
  process_id: 'filter_spatial',
  arguments: {
    data: ...,
    geometry: {
      type: { from_parameter: 'geom_type' },
      geometry: { from_node: 'runudf' }
    }
  }
}
```


It's a bit strange that this is actually an "issue", because the thing that allows it is already "implemented" by you. The "from_node: runudf1" is nothing different than the "from_node: loadcollection1" ;-)

**Comment by jdries** [comment]
Thanks! Indeed, we have a pretty generic process graph parser in place already, so this migh 'just work'. I'll close the issue, I should just have read (or remembered) the current spec a bit better.
