### ISSUE TITLE
mixed tab/spaces indentation

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#158]
I found some mixed tab/spaces indentation here:

https://github.com/Open-EO/openeo-processes/blob/a7ec64d72de8f03e45eb59a8e3279df6e684dc16/examples/array_contains_nodata.json#L2-L10

https://github.com/Open-EO/openeo-processes/blob/a7ec64d72de8f03e45eb59a8e3279df6e684dc16/examples/array_find_nodata.json#L1-L4

**Comment by m-mohr** [comment]
Thanks, fixed.
