### ISSUE TITLE
Does linear_scale_range clip the values?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#159]
@clausmichele asked:

> I wanted to ask you a question about the linear_scale_range process: Does it also have to clip the data in output or not? If we set inputMin and inputMax differently from the real min and max, we won’t obtain data having outputMin and outputMax as output.

It doesn't seem to be documented so it's not clear and we need to define a behavior and document it. What do you think is the expected and most useful behavior? From the original use case (PNG/JPEG export), I think it should clip the values.

**Comment by clausmichele** [comment]
In my opinion we have two options:

1. Clip the data according to outputMin and outputMax
2. Set automatically inputMin and inputMax according to the input data

**Comment by m-mohr** [comment]
> 1. Clip the data according to outputMin and outputMax

That's the option I meant (which is basically the same as "Clip the data according to inputMin and inputMax").

> 2. Set automatically inputMin and inputMax according to the input data

I think we didn't do this as it's not always clear what the input min/max values are without reading all data upfront. So that's the reason the user needs to specify it.

**Comment by m-mohr** [comment]
Telco: Clarify that clipping should take place for input values.

**Comment by m-mohr** [comment]
A fix is available in #167, please review.
