### ISSUE TITLE
What about partially compliant processes?

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#17]
I just implemented a limited version of the 'reduce' process, in the sense that it only works on the temporal dimension. The simple technical reason for this is that this is supported out of the box by the underlying library, while a reduce on the 'x' dimension for instance, is something entirely new.

For me this is not really an issue, but users will not be able to discover this from the list of available processes, except that I could add written constraints on the usage.

- An option could be to list the supported values for the dimension parameter
- Another one: introduce reduce_temporal, with a less generic scope...

**Comment by m-mohr** [comment]
The processes are flexible, that's why we describe them using a pretty complex schema. Clients can generate a builder from them, the hub can check what is supported and propose fitting back-ends etc. So the way it is designed to be allows these differences. For example, the reduce operation is currently defined as such:
```json
{
    "id": "reduce",
    "summary": "Reduce dimensions",
    "description": "Applies a reducer to a data cube dimension by collapsing all the input values along the specified dimension into a single output value computed by the reducer.\n\nThe reducer must accept an array and return a single value (see parameter `reducer`). Nominal values are possible, but need to be mapped, e.g. band names to wavelengths, date strings to numeric timestamps since 1970 etc.",
    "categories": [
        "cubes",
        "reducer"
    ],
    "parameter_order": ["data", "reducer", "dimension"],
    "parameters": {
        "data": {
            "description": "A data cube.",
            "schema": {
                "type": "object",
                "format": "raster-cube"
            },
            "required": true
        },
        "reducer": {
            "description": "A reducer to be applied on the specified dimension. The reducer must be a callable process (or a set processes) that accepts an array and computes a single return value of the same type as the input values, for example ``median()``.",
            "schema": {
                "type": "object",
                "format": "callback",
                "properties": {
                    "data": {
                        "description": "An array with elements of any type.",
                        "type": "array",
                        "items": {
                            "description": "Any data type."
                        }
                    }
                }
            },
            "required": true
        },
        "dimension": {
            "description": "The dimension over which to reduce.\n\n**Remarks:**\n\n* The default dimensions a data cube provides are described in the collection's metadata field `cube:dimensions`.\n* There could be multiple spatial dimensions such as `x`, `y` or `z`.\n* For multi-spectral imagery there is usually a separate dimension for the bands such as `spectral`.",
            "schema": {
                "type": "string"
            },
            "required": true
        }
    },
    "returns": {
        "description": "A data cube with the newly computed values. The number of dimensions is reduced, but the resolution and cardinality are the same as for the original data cube.",
        "schema": {
            "type": "object",
            "format": "raster-cube"
        }
    }
}
```

You can simply add a constraint to the parameter schema, which tells the clients that only a specific value is supported. Of course, it would also be helpful to add an additional(!) note to the description of the parameter and/or the process description in general. See how the dimension specification has changed. Of course, this now limits to a single dimension, so if you have data sets with multiple temporal dimensions and different names, you can also extend the enum to more values for example.
```json
{
    "id": "reduce",
    "summary": "Reduce dimensions",
    "description": "Applies a reducer to a data cube dimension by collapsing all the input values along the specified dimension into a single output value computed by the reducer.\n\nThe reducer must accept an array and return a single value (see parameter `reducer`). Nominal values are possible, but need to be mapped, e.g. band names to wavelengths, date strings to numeric timestamps since 1970 etc.",
    "categories": [
        "cubes",
        "reducer"
    ],
    "parameter_order": ["data", "reducer", "dimension"],
    "parameters": {
        "data": {
            "description": "A data cube.",
            "schema": {
                "type": "object",
                "format": "raster-cube"
            },
            "required": true
        },
        "reducer": {
            "description": "A reducer to be applied on the specified dimension. The reducer must be a callable process (or a set processes) that accepts an array and computes a single return value of the same type as the input values, for example ``median()``.",
            "schema": {
                "type": "object",
                "format": "callback",
                "properties": {
                    "data": {
                        "description": "An array with elements of any type.",
                        "type": "array",
                        "items": {
                            "description": "Any data type."
                        }
                    }
                }
            },
            "required": true
        },
        "dimension": {
            "description": "The dimension over which to reduce.\n\n**Note:** This back-end currently only supports reduce on the `temporal` dimension.",
            "schema": {
                "type": "string",
                "enum": ["temporal"],
                "default: "temporal"
            }
        }
    },
    "returns": {
        "description": "A data cube with the newly computed values. The number of dimensions is reduced, but the resolution and cardinality are the same as for the original data cube.",
        "schema": {
            "type": "object",
            "format": "raster-cube"
        }
    }
}
```

**Comment by mkadunc** [comment]
I wouldn't go too deep into machine-readable meta-descriptions of capabilities of different back-ends. Documentation is good enough for things like this...

On machine level, a process graph with unsupported operations can just fail at submission time with a clear error message.

**Comment by m-mohr** [comment]
I don't agree with that. With the current approach, users can more easily switch between back-ends as it is actually possible to check in a central place (openEO Hub) which back-ends support your processes from a process graph. If you want to run a process graph on another back-end, you don't want to register with 20 of them just to realize most of them don't support exactly what you need. Also, clients can far better handle the processes and let users compose process graphs easier if they are well-described.

**Comment by mkadunc** [comment]
My only point was that describing back-end capabilities well is a lot of work, which I wouldn't treat with the highest priority right now.

I appreciate the benefits such descriptions would bring in the optimistic future scenario where there are more than 10 backends. We're not there yet, and having a standard that's more complex and more difficult to implement will not help us IMO...

**Comment by m-mohr** [comment]
Well, the work was basically already done by me. All the predefined processes are available in that format and back-ends just need to copy them over (and adjust them if necessary). But adjustments shouldn't be required in most cases. I think we need this functionality to be successful in the long run. But it's totally fine to have different opinions regarding this.

**Comment by m-mohr** [comment]
The initial question is answered, right?
