### ISSUE TITLE
apply_kernel - what to do with the borders pixels?

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes#170]
In the API it's specified that the returned array/datacube has the same x and y dimension, but it doesn't specify what to do with pixels on the border. Possibilities:

1. Keep border pixels untouched
2. Pad the data with zeros before applying convolution
3. Replicate border pixels (padding with same values) before applying convolution

There may be other solutions, let me know what do you think.

**Comment by m-mohr** [comment]
What is common ground in other software or research papers?

**Comment by clausmichele** [comment]
Have a look here
https://docs.opencv.org/4.3.0/d2/de8/group__core__array.html#ga209f2f4869e304c82d07739337eae7c5
or here
http://image.dask.org/en/latest/dask_image.ndfilters.html

**Comment by m-mohr** [comment]
It seems like an additional parameter would make sense?!

**Comment by aljacob** [comment]
I agree in an ideal case that should be user defined behavior, with maybe a documented default handling in the back-end implementation e.g. repeating last known value or fill with zeros

**Comment by m-mohr** [comment]
@claxn @jdries @soxofaan What's the default behavior you've implemented?

**Comment by soxofaan** [comment]
I'm not that familiar with current implementation (so for @jdries to confirm)  but as far as I understand:  we pad with NaN or 0 (which are practically equivalent here) before calculating the convolution.

**Comment by m-mohr** [comment]
Make PR with either 0 or reflect as default or set values that don't have a full window to null.

Also: Clarify how nulls are handled. Users may need to pre-process, but we should mention that in the docs.

Discuss again in Dev Telco.

**Comment by claxn** [comment]
@m-mohr : I haven't implemented this process yet, but when applying a kernel I would use convolution, where the following boundary cases are common (`fill`, `wrap`, and `symm`): [https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve2d.html](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve2d.html)

**Comment by m-mohr** [comment]
I'm now comparing the tools mentioned above (scypi, dask, opencv + R EBImage filter2; astropy seems to use scypi?) regarding possible border types and their defaults:

1. user-defined constant value `iiiiii\|abcdefgh\|iiiiiii` (scypi: fill 0, dask: constant, opencv: constant, r: *pass number*) -> openEO pass numeric value
2. repeat border value `aaaaaa|abcdefgh|hhhhhhh` (scypi: -, dask: nearest, opencv: replicate, r: replicate) -> openEO `replicate`
3. mirror from the border `fedcba|abcdefgh|hgfedcb` (scypi: symm, dask: reflect, opencv: reflect, r: -) -> openEO `reflect`?
4. mirror from the center of the last pixel `gfedcb|abcdefgh|gfedcba` (scypi: -, dask: mirror, opencv: reflect101, r: -) -> openEO `reflect_pixel`?
5. repeat image `cdefgh|abcdefgh|abcdefg` (scypi: wrap, dask: wrap, opencv: wrap, r: circular) -> openEO `wrap`

opencv additionally has: isolated (don't look outside of the data) and `transparent` (not sure, sounds like setting NAs?)

Defaults (nice how they all use something different):
* scypi: 1
* dask: 3 
* opencv: 4
* r: 5

**Comment by claxn** [comment]
Two minor comments:

- I would prefer `mirror` over `reflect` as a naming scheme
- I have not so much experience with EO data convolution, but I would favour fill with 0 as a default behaviour

**Comment by m-mohr** [comment]
> * I would prefer `mirror` over `reflect` as a naming scheme

Why? reflect seems more commonly used in software.
I'm currently drafting the parameter and the description is as follows:

> Determines how the data is extended when the filter overlaps the borders. Defaults to fill the border with zeroes.
>
> The following options are available:
> * fill with a user-defined constant number `n`: `nnnnnn|abcdefgh|nnnnnn` (default with `n` = 0)
> * repeat the value from the pixel at the border: `aaaaaa|abcdefgh|hhhhhh`
> * mirror/reflect from the border: `fedcba|abcdefgh|hgfedc`
> * mirror/reflect from the center of the pixel at the border: `gfedcb|abcdefgh|gfedcb`
> * repeat/wrap the image: `cdefgh|abcdefgh|abcdef`

**Comment by claxn** [comment]
That was only a suggestion from my language point of view. But I agree, we should try to align with the major naming scheme of existing software.  

Looks good, thanks!

**Comment by m-mohr** [comment]
Has been merged.
