### ISSUE TITLE
format errors for save_result

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#177]
from https://github.com/Open-EO/openeo-api/blob/draft/CHANGELOG.md:

> Removed all error messages with tag Processes (CRSInvalid, CoordinateOutOfBounds) or related to storing file formats (FormatUnsupported, FormatArgumentUnsupported, FormatArgumentInvalid, FormatUnsuitable) as they are usually defined directly in the process specification as exceptions.

should these format errors be listed in e.g. `save_result` ?

**Comment by m-mohr** [comment]
That would probably be good, although they also need to be added to load_uploaded files [i.e. all parameters with subtype output-format(-options) or input-format(-options)]
