### ISSUE TITLE
Format parameters or options?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#179]
this came up when working on #177/#178 and somewhat conflicts with it. It's also related to openeo-api, but I just filed it here to start.

The API uses  the term "format parameters" in documentation and field names, e.g.: 
https://github.com/Open-EO/openeo-api/blob/4e0f731d3579d7a68265a8c4abaf139b6487815f/openapi.yaml#L3602-L3604
https://github.com/Open-EO/openeo-api/blob/4e0f731d3579d7a68265a8c4abaf139b6487815f/openapi.yaml#L919-L931

The processes that use input/output formats use the term "format options", e.g.:
https://github.com/Open-EO/openeo-processes/blob/bd246a5e6e2ecba7f901552124ba90ce221f4cc5/save_result.json#L33-L37

I think this should be synchronized better, e.g. use "format parameters" in openeo-processes. Unless that is technically not an option (pun intended)

**Comment by m-mohr** [comment]
Yes, it's a good idea to align that better (although both are written for different audiences so may not be of high importance).
