### ISSUE TITLE
Clarify x and y in merge_cubes

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#184]
I would like to understand if x and y of the overlap resolver refer to cube1 and cube2 (x -> cube1, y -> cube2), since it is not explicitly stated in the API. This doubt comes from [some inconsistencies](https://github.com/Open-EO/openeo-earthengine-driver/issues/47) I got from testing with the GEE backend, which I'm not sure are due to the implementation or the definition of the process itself.

_Originally posted by @clausmichele in https://github.com/Open-EO/openeo-processes/issues/87#issuecomment-667095522_

**Comment by m-mohr** [comment]
Yes, x refers to a value from cube1 and y refers to a value from cube2. We should clarify that in the processes.

**Comment by claxn** [comment]
@m-mohr, @clausmichele : Thanks for the update. I have fixed it in the Python parser with the rule: 

- If the number of sub-parameters ('x', 'y', ...) is the same number as the input nodes in the parent process, then assume that, e.g.,  'x' refers to the first input node and 'y' to the second input node (`overlap_resolver` example: `{'process_id': 'subtract', 'arguments': {'x': {'from_node': '3_2'}, 'y': {'from_node': '4_4'}, 'result': True}`
- If the number of sub-parameters ('x', 'y', ...) is not the same number as the input nodes in the parent process, then assume that each input node is split up into 'x', 'y', ... by the back-end (`overlap_resolver` example: `{'process_id': 'subtract', 'arguments': {'x': [{'from_node': '3_2'}, {'from_node': '4_4'}], 'y': [{'from_node': '3_2'}, {'from_node': '4_4'}]}, 'result': True}`).

Would this be the intended behaviour? Or how can one figure out the correct `from_parameter` relation in this case?

**Comment by m-mohr** [comment]
I don't understand this explanation @claxn. You just need from_parameter for x and y?!

**Comment by m-mohr** [comment]
The corresponding PR is #186.

**Comment by claxn** [comment]
@m-mohr Sorry for the bad explanation. Lets do this with process examples: I wanted to know how one can recognize the difference between `reduce_dimension_binary`, where there is one input data cube (`"data"`) and two binary parameters `"x"` and `"y"`, and `merge_cubes`, where there are two input data cubes (`"cube1"` and (`"cube2"`)) and two binary parameters `"x"` and `"y"`. Comparing the process definition files I don't see a rule (except mine suggested above) two distinguish where `"x"` and where `"y"` point to. Is this somehow clear what I am trying to say?

**Comment by m-mohr** [comment]
Why do you need to do/guess that? Shouldn't that be implemented on a per process basis? It seems you are trying to do some magic in the background, which may lead to wrong assumptions for other potential processes.

**Comment by claxn** [comment]
Mmh you are probably right. I am referring to this issue: https://github.com/Open-EO/openeo-pg-parser-python/issues/23. The process graph parser intends to set/replace the "from_parameter" with the respective node ID's. @clausmichele expected the past behaviour to be wrong, e.g., (`{'process_id': 'subtract', 'arguments': {'x': [{'from_node': '3_2'}, {'from_node': '4_4'}], 'y': [{'from_node': '3_2'}, {'from_node': '4_4'}]}, 'result': True}`). But I agree, it is much easier and transparent if the process graph parser always fills in all input node ID's (like in the example before) and the back-end needs to define its strategy depending on the process. Lets discuss this in the next meeting and hopefully everyone agrees with this solution.

**Comment by m-mohr** [comment]
You can't replace the from_parameter with node IDs, there's no corresponding node ID. With the clarified merge_cubes (see PR in openeo-processes) it should be pretty clear how to handle that. You just pass overlapping values as x and y and the subprocess computes with them. The parser really has no stakes in that

**Comment by m-mohr** [comment]
PR has been merged, issue has been solved.
