### ISSUE TITLE
support of multi-process reducer in aggregate_spatial

### ISSUE THREAD

**Issue by kempenep** [Open-EO/openeo-processes#185]
To my understanding, the current API supports a single process for the aggregate_spatial. That is, a single reducer with a single process_id must be defined. For instance, we can calculate the "mean" aggregation for all pixels covered by the polygon. it can be useful to support a list of processes, e.g., ["mean", "stdev"]. Is this currently supported, and if not, can the API be adapted for this?

**Comment by m-mohr** [comment]
No, that understanding is correct. It doesn't even support just specifying the reducer as string, it must be a process graph. As such aggregate_spatial can be any combination of reducers. It's working like reduce, apply or other processes.
