### ISSUE TITLE
Which process for mean over a window with no overlap

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes#187]
I would like to take the mean over a window of a specified size. However, apply_kernel doesn't have a stride value to set, so it's not possible to have no overlap theoretically. I would like to know how you would handle this using the given processes and maybe if you can give an example.

Input:
[[1, 1, 1, 1, 1, 1],
           [2, 2, 2, 2, 2, 2],
           [3, 3, 3, 3, 3, 3]]

Output mean over a 3x3 window with no overlap (stride=3) : [[ 2, 2 ]]

**Comment by m-mohr** [comment]
apply* processes don't change the number of dimension labels / resolution. In openEO terms this is an aggregation. What you want is basically aggregate_spatial, but there you can only specify geometries. Another process that might somewhat work is resample(_cube)_spatial with the "average" method. (Interesting, there it's called average while the process is called mean.)
I doubt we have a really good way to process what you want. I guess for your use case we'd need a new aggregate_spatial_stride or so.

Disclaimer: I've never heard about strides before, so I had to read into this, but may have understood it incorrectly.

**Comment by clausmichele** [comment]
I was thinking about a process which could be named aggregate_spatial_window, where x and y dimensions will be different in output and the process will be applied over a window with dimensions specified by the user.
For example, input 9x9, window size 3x3, output 3x3
Or input 10x20, window 5x10, output 2x2
It would also need a parameter similar to apply_kernel for the border values, which specifies what to do when the window size is not multiple of the data size.

**Comment by jdries** [comment]
I would definitely go for resample_spatial  with the "average' method. Only downside seems to be that the user needs to compute the correct target resolution himself, but isn't that possible?

**Comment by clausmichele** [comment]
As I see it, I would still need to compute the window size from the data dimensions, which is something I shouldn't care as a user. I want to apply an operation on a given window size whatever I have as input, in my opinion the back-end should care about the rest.
Anyway, let's wait for the opinion of @m-mohr

**Comment by m-mohr** [comment]
On the one hand it feels like resample_cube_spatial can handle that, but it's not convenient at all and convenience is the aim of the processes. On the other hand, we would then have quite a lot of processes that do something with windows (apply_kernel, apply_neighborhood, aggregate_spatial_window, ... maybe more in the future?) and that bothers me a bit. So I have no strong preference here. The best way to propose new processes is to just create a PR with a JSON file to discuss.

**Comment by jdries** [comment]
I had a similar concern. There might be a compromise:
if we can access the spatial resolution of a cube, as a parameter or property, then the process graph can compute the target resolution that is required by resample_spatial, as that would be for instance original_resolution/3.
The formula is simple to specify in a callback graph, only need to specify where original_resolution is coming from?

**Comment by clausmichele** [comment]
Actually even apply_kernel would be good for my use case, but it would need an optional parameter for the stride and it should be allowed to return data with a smaller dimension in x and y.
Replying to @jdries , I think it totally depends on the back-end implementation the availability of the datacube dimensions...

**Comment by m-mohr** [comment]
We can't make that work for apply_kernel. apply by definition doesn't reduce the resolution and also doesn't change dimension labels. Also, I don't want to overload apply_kernel. It's better to have small self-container processes than very complex once that no one can implement (see merge_cubes for example). So if we can't find an easy way to make it work based on Jeroens proposal, a new process would be the way to go. Currently, I'm not sure yet how to do it in a good way...

**Comment by clausmichele** [comment]
Created a pull request for a new process https://github.com/Open-EO/openeo-processes/pull/191

**Comment by m-mohr** [comment]
I just realized we have count(dimension_labels()) which could be useful to compute the resolution, but still I feel a separate process would make it more convenient. People will likely not like to compute such stuff theirself.

**Comment by clausmichele** [comment]
but dimension_labels() returns just the labels in a specific dimension, which could be the band names I guess, it doesn't seem related to the spatial dimension of the data.

**Comment by m-mohr** [comment]
I'd expect that dimension_labels(data, "x") returns all locations or so, which you could then count.

**Comment by jdries** [comment]
I would also opt for a process that returns the physical 'pixel size' for a spatial dimension. Usually this is returned in the distance unit of the CRS. So degrees for lat lon, meter for utm.
But what would be a good name?

**Comment by m-mohr** [comment]
`dimension_ground_sample_distance` (a bit long) / `dimension_gsd` (not sure how intuitive it is)? That would be inline with our metadata (gsd in STAC).

**Comment by m-mohr** [comment]
For further discussions on datacube / dimension property retrieval see #195.

**Comment by m-mohr** [comment]
Process has been added to proposals
