### ISSUE TITLE
is_nodata([null, null])?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#189]
What is the behavior of `is_nodata` given an array of only nan/null values?

    is_nodata([null, null])

From current docs I guess the return value should be false, but it's not that clear I think

**Comment by m-mohr** [comment]
Yes, false.

It's indeed not very clear, but there's a reference to equals and `equals([null, null], null)` would also return false. I will make a PR for it.

**Comment by soxofaan** [comment]
thanks

> but there's a reference to equals

I didn't read the "equals" as a reference to the `eq` process (which indeed has in-depth rules), just as a "handwavy" verb.
Also: `eq` does not specify rules for NaN

**Comment by m-mohr** [comment]
It has a rule for it (null = nodata; NaN is not covered by is_nodata, see is_nan): 

> If any operand is null, the return value is null. Therefore, eq(null, null) returns null instead of true.

Indeed, I implied here that null will be casted to false.

**Comment by soxofaan** [comment]
I'm not sure If I should piggy back this issue or create a new one: but what about

    is_nan(null)

description of  `is_nan` says 

> All non-numeric data types MUST also return true.

as `null` is non-numeric, `is_nan(null)` should return True?

**Comment by soxofaan** [comment]
An while we're at it, let's also look at `is_valid`

Attempt to make a truth table of my current understanding of the docs

x | is_nan(x) | is_nodata(x) | is_valid(x)
----|----|----|----
null | True?  | True  | False
NaN | True | True | False
1 (finite int/float)  | False | False | True
"a string" | True | False | True
[1, 2]   | True | False | True
[null, null]) | True | False | True ?
[NaN, NaN] | True | False | True ?

is that correct?

**Comment by m-mohr** [comment]
You had it mostly correct:

| x                    | is_nan(x) | is_nodata(x) | is_valid(x) |
| -------------------- | --------- | ------------ | ----------- |
| null                 | True      | True         | False       |
| NaN                  | True      | False        | False       |
| 1 (finite int/float) | False     | False*       | True        |
| infinity             | False     | False        | False       |
| "a string"           | True      | False*       | True        |
| [1, 2]               | True      | False        | True        |
| [null, null])        | True      | False        | True        |
| [NaN, NaN]           | True      | False        | True        |

* True for values that have been declared no data in the metadata; STAC Extension tbd.

**Comment by soxofaan** [comment]
> True for values that have been declared no data in the metadata

Interesting, that was not obvious to me. It's worthwhile to make this more explicit in the docs I think.
Or the other way around: isn't that an implementation detail of the backend that should already have been abstracted away through the load_collection process?

**Comment by m-mohr** [comment]
Ideally, yes. It's completely optional for back-ends that may need to do that. If the metadata doesn't expose explicitly no-data values, it's only null.

I guess I could change the docs from

> , i.e. equals to any of the no-data values / null.

to 

> , i.e. equals to `null` or any of the no-data values specified in the metadata.

**Comment by m-mohr** [comment]
Now that I'm looking at the table, I'm missing a is_infinite process... And I also realized that is_number would have probably been a bit more intuitive than is_nan.

**Comment by soxofaan** [comment]
> I also realized that is_number would have probably been a bit more intuitive than is_nan

yes, but a common use case is probably creating a mask cube for the `mask` process, where you want True for the nan pixels (so they can be replaced), so `is_nan` is most useful there

**Comment by m-mohr** [comment]
Thanks for the review and the approval. Thus fixed with PR #190.
