### ISSUE TITLE
aggregate_temporal -> labels clarification

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#19]
Currently the definition of the labels parameter in aggregate_temporal is:

> Labels for the intervals. The number of labels and the number of groups need to be equal.

One of the most common cases IMO, is that the labels are again valid timestamps. This way, the time dimension is mapped unto a time dimension, and not something entirely new.

Not sure if this should be a hard constraint, but for me it's at least a recommended suggestion. Also an example can be provided. 
For me, it's also an option to use the first timestamp of each interval as the default label. That way the labels parameter is no longer mandatory, and the function becomes easier to use.

**Comment by m-mohr** [comment]
There are multiple potential changes in your text:
1. Allow timestamps for the labels:
    _Yes, that's a good idea. I added the corresponding string formats._
2. Add an example to the process.
    _I added an example._
3. Use the first timestamp of each interval as default label.
    _Sounds reasonable. As the current approach was discussed and decided on the VITO sprint, I'd like wait for more opinions on this one. Your proposal makes sense in some cases, in some it seems not so meaningful. As @mkadunc was a main driver of the current proporal, what's your opinion, Miha?_

The changes will be pushed to the repository in the next hours.

**Comment by jdries** [comment]
Thanks, one more question: can intervals overlap?

**Comment by mkadunc** [comment]
> they allow the backend to derive the new discrete time steps that are available after the aggregation, without actually having to run it.

It's hard to discuss this without a domain model of data cubes' meta-information...

But I agree with your suggestion - given that the time steps are already available from the intervals, additional `labels` parameter would only be for human consumption - programatically you'd do best to use whole intervals as labels for axis cells, and let the user do additional annotation or conversion on those (which tells us that we need some processes for manipulating data cube meta-information)

I also agree that dimension should be preserved across aggregation, but its axis should have different partitioning / sampling specification - we shouldn't automatically convert a regularly-sampled axis into interval-partitioned axis without changing some of its meta-attributes.

**Comment by m-mohr** [comment]
We discussed that for 0.4 we stick with the current proposal, but @jdries may just remove the ability to specify string-only labels as GepPySpark can't handle them. Moving the discussion to 0.5 or 1.0.

**Comment by m-mohr** [comment]
Let's revisit this issue: We now have [rename_labels](https://processes.openeo.org/draft/#rename_labels). I'm wondering whether we should just remove the labels parameter from aggregate_temporal completely and just handle it as in reduce: We just enumerate the labels by default based on the intervals (i.e. `[ [ "2015-01-01", "2016-01-01" ], [ "2016-01-01", "2017-01-01" ], [ "2017-01-01", "2018-01-01" ] ]` will have the labels `[0, 1, 2]`). Afterwards, a user can call rename_labels when required. @jdries @mkadunc 

Note to myself: I would need to allow the temporal string types in the `labels` parameter of `rename_labels`.

**Comment by m-mohr** [comment]
Note: aggregation assignments to groups are not necessarily unique any longer, see https://github.com/Open-EO/openeo.org/commit/4397fde48437cac58868f0fce13dfb9f9bf7bd3d  and https://github.com/Open-EO/openeo-processes/pull/107#issuecomment-573799546.

**Comment by m-mohr** [comment]
@jdries PR #122 makes the parameter labels optional.
Is there anything left to be done here? Otherwise I'd close after we have merged #122.

**Comment by jdries** [comment]
Agree to merge and close!
