### ISSUE TITLE
Get data cube / dimension information

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#193]
While discussing #187 and #192, we came across the need to get data cube metadata in the processes, like the number of dimension labels, the resolution, the CRS or so. We have dimension_labels() and count() for the number of dimension labels, but not much more. We should add more processes to get all the metadata.

cc @clausmichele @jdries

**Comment by clausmichele** [comment]
So, if a datacube is (time,bands,x,y) with dimension_labels() and count() we could get the first 2 right?

**Comment by m-mohr** [comment]
No, you'd need to call dimension_labels(data, "x") and then you can count the number of labels available (which is the same as counting values if you don't care for null/NaN/etc.).

**Comment by m-mohr** [comment]
Woops, closing as duplicate of #193.

**Comment by clausmichele** [comment]
> 
> 
> Woops, closing as duplicate of #193.

Duplicate of #195, 193 is this one
