### ISSUE TITLE
resample_cube_temporal behavior

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes#194]
In Eurac's use case we need to perform a temporal resampling (downsampling) of a timeseries to align with another one.
The question is: does the **resample_cube_temporal** definition let us pick the closest neighbor without applying any process on that? Because from the API it seems that the result should be some processed aggregate of data:

_method*
A resampling method to be applied, could be a reducer for downsampling or other methods for upsampling. A reducer is a single process such as mean or a set of processes, which computes a single value for a list of values, see the category 'reducer' for such processes._

Instead, we just want to pick the closest date without any additional processing. The method field is mandatory, but I was thinking to implement it in such a way, that without any method it will just pick the nearest neighbor.

**Comment by m-mohr** [comment]
resample_cube_temporal passes a *labeled-array* to the process passed to `method`. So you could use the labels (`array_labels`) to pick a date and return it. 

I proposed date-related processes some time ago, but the response wasn't too positive so they are missing yet and you need to rely on other processes (you can likely try `sort` and `first`/`last`) or we start defining the date-related processes again.

So something like this for method:
```
labels = array_labels(data);
lastDate = last(sort(labels)); // takes the last element, although first might be closer
return array_element(data, label = lastDate);
```

You can pick first or last, but can't pick the closest yet. Not sure exactly how you want to/can determine that.

**Comment by m-mohr** [comment]
We could also define `resample_temporal`, which could be defined very similarly to `resample_spatial`. Actually, I'm not really sure why we only have resample_spatial...

**Comment by clausmichele** [comment]
> 
> 
> resample_cube_temporal passes a _labeled-array_ to the process passed to `method`. So you could use the labels (`array_labels`) to pick a date and return the corresponding value.
> 
> I proposed date-related processes some time ago, but the response wasn't too positive so they are missing yet and you need to rely on other processes (you can likely try `sort` and `first`/`last`) or we start defining the date-related processes again.
> 
> So something like this for method:
> 
> ```
> labels = array_labels(data);
> lastDate = last(sort(labels)); // takes the last element, although first might be closer
> return array_element(data, label = lastDate);
> ```
> 
> You can pick first or last, but can't pick the closest yet. Not sure exactly how you want to/we can determine that, because we don't really know the border...

I'm sorry but I don't understand your sample code, could you expand with some more details?
Let's start with an easier case, where we have daily data:
1. Datacube SOURCE with dimensions (bands,time,x,y) (1,365,10,10), so with one band and daily data
2. Datacube TARGET with dimensions (bands,time,x,y) (1,12,10,10), again the same band but with data only once a month on the 1st day of the month

The goal is to resample the datacube SOURCE and "extract" only the data with corresponding dates to datacube TARGET. Is it possible with the current OpenEO processes?

The more complex case would be having datacube SOURCE with gaps, and having the algorithm picking the closest date.
I could handle both cases in Python easily, but I'm not sure it is something the current _resample_cube_temporal_ is intended for.

By the way, I've checked with the Web Editor EODC, VITO and GEE and there is no implementation of  _resample_cube_temporal_ available yet.

**Comment by m-mohr** [comment]
> I'm sorry but I don't understand your sample code, could you expand with some more details?

These are all openEO processes (see the docs). Which step exactly is not clear? I guess the confusion comes from labeled arrays. Have you understood what they are? Basically a sorted map with dimension labels (timestamps here) as keys and corresponding values. The example doesn't completely solve your issue though, but wanted to show it as a starting point.

> 1. Datacube SOURCE with dimensions (bands,time,x,y) (1,365,10,10), so with one band and daily data
> 2. Datacube TARGET with dimensions (bands,time,x,y) (1,12,10,10), again the same band but with data only once a month on the 1st day of the month

I don't understand the example. What are these values? The number of values? Or some values itself?

> The goal is to resample the datacube SOURCE and "extract" only the data with corresponding dates to datacube TARGET. Is it possible with the current OpenEO processes?
> The more complex case would be having datacube SOURCE with gaps, and having the algorithm picking the closest date.

So you somehow need the target in the method/process. That is actually a good point. We may need to pass some context to the method, e.g. the target dimension label in this case. Unfortunately, that is missing as of yet.

> I could handle both cases in Python easily, but I'm not sure it is something the current _resample_cube_temporal_ is intended for.

I can't really think of a solution yet. The closest you can get is what I posted above.

> By the way, I've checked with the Web Editor EODC, VITO and GEE and there is no implementation of _resample_cube_temporal_ available yet.

Yes, that is true, unfortunately.

**Comment by clausmichele** [comment]
> 
> 
> These are all openEO processes (see the docs). Which step exactly is not clear? I guess the confusion comes from labeled arrays. Have you understood what they are? Basically a sorted map with dimension labels (timestamps here) as keys and corresponding values. The example doesn't completely solve your issue though, but wanted to show it as a starting point.

Ok now I understand it.

> > 1. Datacube SOURCE with dimensions (bands,time,x,y) (1,365,10,10), so with one band and daily data
> > 2. Datacube TARGET with dimensions (bands,time,x,y) (1,12,10,10), again the same band but with data only once a month on the 1st day of the month
> 
> I don't understand the example. What are these values? The number of values? Or some values itself?

The values are the datacubes shapes, SOURCE has 365 values in the time dimension for example, one for each day.

> > The goal is to resample the datacube SOURCE and "extract" only the data with corresponding dates to datacube TARGET. Is it possible with the current OpenEO processes?
> > The more complex case would be having datacube SOURCE with gaps, and having the algorithm picking the closest date.
> 
> So you somehow need the target in the method/process. That is actually a good point. We may need to pass some context to the method, e.g. the target dimension label in this case. Unfortunately, that is missing as of yet.

Yes, so it would be enough to have a _nearest_neighbor_ process to apply on the temporal dimension in the _resample_cube_temporal_ method, this would solve my problem.

I'll prepare a sample implementation which fits our use case. It would be interesting to know what the others think about _resample_cube_temporal_ and why nobody implemented it yet.

**Comment by m-mohr** [comment]
> The values are the datacubes shapes, SOURCE has 365 values in the time dimension for example, one for each day.

Understood.

> Yes, so it would be enough to have a _nearest_neighbor_ process to apply on the temporal dimension in the _resample_cube_temporal_ method, this would solve my problem.

Yes, the issue is that nearest_neighbor needs more input than just the actual values/labels. So we can't just define the process. In the spatial processes, it's part of a list of pre-defined resampling methods. We need resample_temporal similar to resample_spatial to allow that. And I think we should try to define that....

> I'll prepare a sample implementation which fits our use case.

Great!

> It would be interesting to know what the others think about _resample_cube_temporal_ and why nobody implemented it yet.

It was defined by the consortium so they should be okay with it, but I guess nobody had a use case for it yet or time was missing?!

**Comment by clausmichele** [comment]
> > Yes, so it would be enough to have a _nearest_neighbor_ process to apply on the temporal dimension in the _resample_cube_temporal_ method, this would solve my problem.
> 
> Yes, the issue is that nearest_neighbor needs more input than just the actual values/labels. So we can't just define the process. In the spatial processes, it's part of a list of pre-defined resampling methods. We need resample_temporal similar to resample_spatial to allow that. And I think we should try to define that....

What do you think it the definition of nearest neighbour would need? I've implemented something which would satisfy our needs at the moment: it takes as input the target date/time labels, looks for the closest labels in the input datacube and returns a new datacube with the selected ones.

**Comment by m-mohr** [comment]
It needs the labels of the input data cube or the boundaries of the "window", but that is not available in the callback.
You could pass the dimension labels via the context parameter and then it should work.

**Comment by clausmichele** [comment]
So, the boundary could be a parameter like ±1 hour, ±1 day, ±1 week, ±1 month?
And for the labels, couldn't the process automatically retrieve the time labels? I think it is something that the backend should take care of in the implementation

**Comment by m-mohr** [comment]
No, the boundary should be the boundary of the original data that is resampled into a single value. 

The process could do it, but it is not defined that way and it's not easy to make breaking changes in the definition. It's easier to define new processes ;-)

**Comment by m-mohr** [comment]
As discussed in the recent dev telco, the process is not very well defined and is unclear. It is also (probably due to the bad spec) not really implemented yet, so we aim for a bigger (likely breaking) change. Nearest values can be a start for specific timestamps. We'll aim for a new definition and will work on it in a PR...

**Comment by m-mohr** [comment]
@clausmichele Please have a look at PR #244
