### ISSUE TITLE
null handling in `all`

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#199]
Some questions about description/definition of `all` process:

-   > if ... the array is empty ... the process returns null.

    what is the background reasoning here? FYI: in python `all([]) == True` (see .e.g. https://stackoverflow.com/questions/19601802/how-does-all-in-python-work-on-empty-lists)

-   > If only one value is given, the process evaluates to the given value.
   
    is it necessary to explicitly document the single value case? It conflicts a bit with the `ignore_nodata=True` case: if given `[null]`, should one use that single value, or ignore the `null` and handle it as empty list?  I know that it is the same (currently, see higher), but it makes it a bit confusing.

-   > .. so that null is a valid logical object

    what does this mean? Like a "third boolean value"?

-  > If a component is null, the result will be null if the outcome is ambiguous

    I don't know to handle the two if's in that sentence. And what does "ambiguous" mean here (how would the result be ambiguous)? 

(the same probably applies to `any`, but I haven't read it in that much detail yet)

**Comment by m-mohr** [comment]
> Some questions about description/definition of `all` process:
> 
> * > if ... the array is empty ... the process returns null.
>   
>   
>   what is the background reasoning here?

I can't remember the discussion, but I think the reasoning was: No data is given => no data value should be returned. For me this sounds more logical than assigning empty arrays to true or false, which both could be argued to be valid return values. It's likely also to be consistent with your example below `[null] => null`.


>   is it necessary to explicitly document the single value case?

What are you referring to?

> * > .. so that null is a valid logical object
>   
>   what does this mean? Like a "third boolean value"?

That just means that null can occur in a context that usually only expects booleans and need to be handled correctly. Indeed this sounds a bit strange. What is a "logical object"? Maybe it was meant to be "entity" or "value". Not sure. Maybe we should just remove " so that `null` is a valid logical object"? What do you think?


> * > If a component is null, the result will be null if the outcome is ambiguous
>   
>   
>   I don't know to handle the two if's in that sentence. And what does "ambiguous" mean here (how would the result be ambiguous)?
> 
> (the same probably applies to `any`, but I haven't read it in that much detail yet)

This refers to the following examples:
* `all(data = [false,null], ignore_nodata = false) => false` -> A single false will always lead to false independently of no-data (unambiguous). false/true and false/false are both false.
* `all(data = [true,null], ignore_nodata = false) => null` -> A single true is ambiguous and leads to null as the no-data value is not known. true/true => true, but true/false => false.

I guess we better change the "If a component is null, the result will be null if the outcome is ambiguous" to "If a component is null and the outcome is ambiguous, the result will be null".

**Comment by soxofaan** [comment]
> I can't remember the discussion, but I think the reasoning was: No data is given => no data value should be returned.

I understand, but I think an empty list and `null` are quite different flavors of "no data" as a general concept. A list can have an arbitrary length by design, and an empty list is as normal as a list with one or two items. In contrast, `null` (or Python's `None`) are special objects that have nothing in common with "real" values (like integers or strings).

I know that my standpoint is biased by the way it is implemented in Python, but I'm not a fan of conflating  "empty list" with "special no-data flag `null`". These resources give interesting background and reasoning on how to still define a boolean result for `any` and `all` on empty  lists: 
- https://stackoverflow.com/questions/19601802/how-does-all-in-python-work-on-empty-lists 
- https://stackoverflow.com/questions/3275058/reason-for-all-and-any-result-on-empty-lists 
- https://en.wikipedia.org/wiki/Vacuous_truth

**Comment by soxofaan** [comment]
> >    is it necessary to explicitly document the single value case?
>
> What are you referring to?

To this sentence in the description: 

> If only one value is given, the process evaluates to the given value.

I would just drop that, as it does not really clarifies anything (it might even make things more confusing as it reads a bit as a special case, while it isn't). Another nitpick: technically you are always giving one value anyway: an array :)

**Comment by m-mohr** [comment]
While I understand your point of view, too, I'm still unsure which is the better behavior. Also, it will be hard to change as it's a breaking change and thus should go through broader review.

I'll look into the "single value" sentence and likely remove it.

**Comment by soxofaan** [comment]
> Maybe we should just remove " so that null is a valid logical object"? 

Yes, unless you can link to a reference that defines the handling of `null` in boolean operations.

As a matter of fact, the truth table mentioned in the description looks like extension of the "and" operation (it's the same as in the description of `and`):
```
      || null  | false | true
----- || ----- | ----- | -----
null  || null  | false | null
false || false | false | false
true  || null  | false | true
```

Why is `false and null`  equal to `false`?  Why isn't `null` the [absorbing element](https://en.wikipedia.org/wiki/Absorbing_element), like in `add`, `multiply`, `subtract`, ...?

**Comment by m-mohr** [comment]
I just found the origin of all/any and it gives some context, hopefully: #85

**Comment by m-mohr** [comment]
> Why is `false and null` equal to `false`? Why isn't `null` the [absorbing element](https://en.wikipedia.org/wiki/Absorbing_element), like in `add`, `multiply`, `subtract`, ...?

no-data was basically used with the following meaning: "we don't know the value, could be anything". 

For all/any:

* all(data = [false,null], ignore_nodata = false) => false -> A single false will always lead to false independently of no-data (unambiguous). false/true and false/false are both false.
* all(data = [true,null], ignore_nodata = false) => null -> A single true is ambiguous and leads to null as the no-data value is not known. true/true => true, but true/false => false.

null is absorbing if the result is ambiguous.

For add/multiply etc you can never get an unambiguous result with an unknown second value. Thus there it is absorbing.

**Comment by soxofaan** [comment]
>     `all(data = [false,null], ignore_nodata = false) => false` -> A single false will always lead to false independently of no-data (unambiguous). false/true and false/false are both false.
>   ` all(data = [true,null], ignore_nodata = false) => null` -> A single true is ambiguous and leads to null as the no-data value is not known. true/true => true, but true/false => false.

Ok, I think this explains my confusion. For me, the concept of ambiguous/unambiguous in discussion about `all` and `any` is about the short-circuiting behaviour: "you walk through the array and once you know the result unambiguously without having to look at more items, you return" (e.g.: once you're `false` in `all` you can stop, once you're `true` in `any` you can stop).

However in the quote above, "ambiguous" is about not knowing the true value behind your `null` measurement, which is something else. I think this is not obvious.

**Comment by soxofaan** [comment]
Another thing about the truth table: it shows a binary operation between two values (`and` in this case), while `any` operates on an array of an arbitrary number of elements as a whole. It is currently not that obvious how to connect these two things.

**Comment by m-mohr** [comment]
It still is about short-circuiting. The additional null/no-data explanations were just for clarification (I hoped) of why short-cirtcuiting in the examples is a bit different with nulls.

I guess we could change the introduction from

> See the following truth table

to something like:

> See the following truth table for any two consecutive values in the array
