### ISSUE TITLE
aggregate_polygon: Output format

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#2]
Currently the zonal statistics process does not have a clear, standardized output format.
Having a json encoding would make most sense. You could also look into, or borrow concepts from, OGC TimeseriesML.

Here's an example of a simple json encoding that we currently use:

- totalCount and validCount refer to number of pixels encountered in the polygon.
- I'm not proposing this actual format, just trying to clarify what I'm talking about.

```
 {
  "results": [
    {
      "date": "2015-07-06",
      "result": {
        "totalCount": 1,
        "validCount": 1,
        "average": 0.8150000000000001
      }
    },
    {
      "date": "2015-07-16",
      "result": {
        "totalCount": 1,
        "validCount": 1,
        "average": 0.49
      }
    },
    {
      "date": "2015-07-26",
      "result": {
        "totalCount": 1,
        "validCount": 1,
        "average": 0.215
      }
    },
    {
      "date": "2015-08-02",
      "result": {
        "totalCount": 1,
        "validCount": 1,
        "average": 0.93
      }
    },
...
```

**Comment by mkadunc** [comment]
Given the discussion at Vito this week, about vector collections as arrays, I suggest we do the following:
- the most frugal way of structuring the response would be to keep the `zone` axis in the results in the same order as the geometries that came in, then we don't need the reference geometry
- possibly we could use IDs of zones (if they have IDs) to link to the zone geometries from the request
- don't return geometries in the result - they will be known by the caller (either by ID or position in output array)
- define properties to be returned as a dimension in the output array (`statsAxis = categorical_axis(["totalCount", "validCount", "min","max","mean"])`)
- zone  is another dimension (`zoneAxis = index_axis(N_zones)`)
- other dimensions can be arbitrary, depending on the process (`timeAxis = irregular_axis(datetime, [t0,t1..tN])`, `bandAxis = categorical_axis(N_bands)`)
- data is returned in a multi-dimensional array

In JSON, this could look like the following (modeled after NetCDF; the metadata part at the beginning is just a quick attempt at encoding relevant info into JSON)—note that there is no duplication of property names in the `data` part, so it should produce a much smaller file than using GeoJSON features:
```JavaScript
//openEOCubeJSON
{
	"axes": {
		"time": { 
			"type" : "regular",
			"data" : [{
				"variable" : "timestamp",
				"dataType" : "datetime",
				"range" : {
					"length" : 2,
					"offset" : "2015-07-06",
					"samplingDistance" : "P10D"
				}
			}]
		},
		"zone": { "type" : "index" },
		"band": {
			"type" : "categorical",
			"data" : [{
				"variable" : "name",
				"dataType" : "string",
				"values" : ["NDVI"]
			}]
		},
		"stat": {
			"type" : "categorical",
			"data" : [{
				"variable" : "name",
				"dataType" : "string",
				"values" : ["totalCount", "validCount", "min", "max", "mean"]
			}]
		}
	},
	"data": [
		{
			"variable" : "value",
			"axes" : ["zone", "time", "band", "stat"],
			"raster" : [
				//zone 0
			    [
					//time 2015-07-06
					[
						//band NDVI
						[9,8,0.58,0.99,0.86]
					],
					//time 2015-07-16
					[
						//band NDVI
						[9,8,0.40,0.57,0.49]
					]
				],
				//zone 1
				[
					[
						//band NDVI
						[9,9,0.78,0.98,0.975]
					],
					//time 2015-07-16
					[
						//band NDVI
						[9,9,0.37,0.51,0.425]
					]
				]
			]
		}
	]
}
```

Now if polygons or their IDs are needed, they could be returned in the `data` part of the `zone` axis information.

**Comment by edzer** [comment]
I like that. There is also CoverageJSON, see for instance the MULTIPOLYGON or POINT example in https://covjson.org/playground/ . What they call `domain` and `range`, you call `axes` and `data`. In their POINT example, they have in addition `parameters`, which kind of makes sense e.g. for different variable that have different measurement units.

**Comment by mkadunc** [comment]
Nice link - i completely forgot about covjson. My source was mostly [the NetCDF Data Model](https://www.unidata.ucar.edu/software/netcdf/netcdf/The-NetCDF-Data-Model.html#The-NetCDF-Data-Model)

Some observation/comparison of the two:
- what covjson calls `parameters`, I call `variable`,
- covjson parameters are specified in advance, which allows a parameter to be defined outside of any data matrix; my variables are all specified inline along with 'raster' or 'values',
- their parameter doesn't include the dataType — it's only available in "ranges" alongside the values,
- i don't like that their data arrays are 1-dimensional; nested arrays are IMO better for human-readable JSON (for non-human consumption, we will probably use some binary format anyway)
- while I think it's nice that the data arrays can be linked from external source, it would be better if the shape (or at least the dimensions) of the array and its data types would be known in the main JSON document
- they have many domain and axis types that encode different types of geospatial rasters; in my proposal (and netCDF) all axes have simple integer indexing, and any additional info about the axis values is provided in variables. I included axis type as a way of hinting that axis values may be reordered (categorical), extended (regular / irregular / categorical), aggregated (regular / irregular), compared (regular / irregular) - just something I think might be useful for defining operations of a datacube algebra.

`covjson` is definitely something we should look at - maybe it could also help model those parts of image collection metadata that aren't handled by STAC

**Comment by m-mohr** [comment]
There is also CF-JSON, which seems somewhat similar: http://cf-json.org/specification

**Comment by jdries** [comment]
Didn't know this, but NetCDF also supports it:
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch09.html
They are now even working on a way to encode the geometries inside netcdf:
https://github.com/cf-convention/cf-conventions/blob/master/ch07.adoc#geometries

However, browsers will not like such a binary format, so I still see a clear use case for something based on json.

**Comment by m-mohr** [comment]
3rd year planning: @jdries will look into CovJSON and CFJSON (fka NCO-JSON, see https://github.com/cf-json/cf-json.github.io/issues/10). Related discussions: https://github.com/covjson/specification/issues/86 and https://github.com/pangeo-data/pangeo-datastore/issues/3#issuecomment-463129782

**Comment by soxofaan** [comment]
CovJSON output format has been implemented for aggregate_polygon in VITO backend (still to be deployed at the moment) through PRs Open-EO/openeo-python-driver#23 and Open-EO/openeo-geopyspark-driver#25


Usage example against my localhost setup of the VITO backend
(note the `save_result(format="CovJSON")` to enable the CovJSON output format):

```python
import json
import shapely
import openeo

connection = openeo.connect("http://localhost:8080/openeo/0.4.2/")

polygon1 = shapely.geometry.Polygon([(3.71, 51.01), (3.72, 51.02), (3.73, 51.01)])
polygon2 = shapely.geometry.Polygon([(3.71, 51.015), (3.725, 51.025), (3.725, 51.03), (3.71, 51.03)])
geometry_collection = shapely.geometry.GeometryCollection([polygon1, polygon2])

cube = (
    connection
        .load_collection('CGS_SENTINEL2_RADIOMETRY_V102_001')
        .filter_temporal('2019-07-15', '2019-07-30')
        .polygonal_mean_timeseries(polygon=geometry_collection)
        .save_result(format="CovJSON")
)

result = cube.execute()
print(json.dumps(result))
```


output: 
```
{
  "domain": {
    "axes": {
      "composite": {
        "values": [
          [
            [
              [
                3.71,
                51.01
              ],
              [
                3.72,
                51.02
              ],
              [
                3.73,
                51.01
              ],
              [
                3.71,
                51.01
              ]
            ]
          ],
          [
            [
              [
                3.71,
                51.015
              ],
              [
                3.725,
                51.025
              ],
              [
                3.725,
                51.03
              ],
              [
                3.71,
                51.03
              ],
              [
                3.71,
                51.015
              ]
            ]
          ]
        ],
        "coordinates": [
          "x",
          "y"
        ],
        "dataType": "polygon"
      },
      "t": {
        "values": [
          "2019-07-20T00:00:00Z",
          "2019-07-23T00:00:00Z",
          "2019-07-25T00:00:00Z",
          "2019-07-28T00:00:00Z",
          "2019-07-30T00:00:00Z"
        ]
      }
    },
    "domainType": "MultiPolygonSeries",
    "type": "Domain",
    "referencing": [
      {
        "coordinates": [
          "x",
          "y"
        ],
        "system": {
          "type": "GeographicCRS",
          "id": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
        }
      },
      {
        "coordinates": [
          "t"
        ],
        "system": {
          "type": "TemporalRS",
          "calendar": "Gregorian"
        }
      }
    ]
  },
  "ranges": {
    "band0": {
      "values": [
        8279.030674846626,
        6925.279187817259,
        null,
        null,
        647.3476972527749,
        606.1746575342465,
        null,
        null,
        598.0162638242506,
        539.5157878068092
      ],
      "axisNames": [
        "t",
        "composite"
      ],
      "type": "NdArray",
      "dataType": "float",
      "shape": [
        5,
        2
      ]
    },
    "band2": {
      "values": [
        7540.171779141105,
        6389.071065989848,
        null,
        null,
        878.138968409422,
        825.1263001014713,
        null,
        null,
        816.8533253265275,
        744.4639429928741
      ],
      "axisNames": [
        "t",
        "composite"
      ],
      "type": "NdArray",
      "dataType": "float",
      "shape": [
        5,
        2
      ]
    },
    "band1": {
      "values": [
        7925.613496932516,
        6670.365482233503,
        null,
        null,
        844.6788709758425,
        798.5987760020295,
        null,
        null,
        792.2864935194916,
        728.3024861441013
      ],
      "axisNames": [
        "t",
        "composite"
      ],
      "type": "NdArray",
      "dataType": "float",
      "shape": [
        5,
        2
      ]
    },
    "band3": {
      "values": [
        9019.067484662577,
        7498.243654822335,
        null,
        null,
        2178.021344985184,
        2224.413654236428,
        null,
        null,
        2106.431366661662,
        2155.113032462391
      ],
      "axisNames": [
        "t",
        "composite"
      ],
      "type": "NdArray",
      "dataType": "float",
      "shape": [
        5,
        2
      ]
    }
  },
  "type": "Coverage",
  "parameters": {
    "band0": {
      "observedProperty": {
        "label": {
          "en": "Band 0"
        }
      },
      "type": "Parameter"
    },
    "band2": {
      "observedProperty": {
        "label": {
          "en": "Band 2"
        }
      },
      "type": "Parameter"
    },
    "band1": {
      "observedProperty": {
        "label": {
          "en": "Band 1"
        }
      },
      "type": "Parameter"
    },
    "band3": {
      "observedProperty": {
        "label": {
          "en": "Band 3"
        }
      },
      "type": "Parameter"
    }
  }
}

```

**Comment by m-mohr** [comment]
What would be the actual return value of aggregate_polygon? A general "vector-cube", which can be passed to the save_result process or would it return directly covjson or so? How should the schema for the return value of the function look like?

**Comment by mkadunc** [comment]
> What would be the actual return value of aggregate_polygon?

vector-cube

JSON should be considered just as an output encoding, similar to "GTiff" in save_result

**Comment by m-mohr** [comment]
So coming from the point (see #68) that we generally don't support vector-cubes at the moment, would it be enough to only support vector cubes in aggregate_polygon, save_result, load_result and maybe load_collection, add_dimension, drop_dimension and rename_dimension? Or so I miss something?

**Comment by mkadunc** [comment]
IMO the only thing we need to do in order to have vector-cubes support is allow objects as dimension labels (currently we only allow number, string, date, date-time and time). Then vector-cube is just a cube with simple-feature-geometry as dimension labels on the single spatial dimension. If we go for this approach, we already support vector cubes in all processes (but we treat the spatial dimension as nothing special).

We could also ignore vector-cubes altogether (for now), returning a raster cube with an ordinal dimension to encode the index of the corresponding polygon. This should be quite intuitive for the user...

**Comment by m-mohr** [comment]
Moved discussions about vector cubes to #68

**Comment by jdries** [comment]
FYI I implemented netcdf as output format for timeseries. I used the simple orthogonal multidimensional array representation, and converted polygons to their points to make life easier. (Support for polygons in netcdf is worked on, but seems less standard.)
Otherwise the representation seems quite promising, and also can be converted to nco-json.

**Comment by m-mohr** [comment]
@jdries Sounds good. Do you plan to support nco-json anytime soon? If so, I think I'd also try to implement it for GEE.

**Comment by jdries** [comment]
I'll give nco-json a try, but will have to install the nco dependencies for that, as I haven't found a python library yet that does the conversion. It's a bit of a side thing, so not sure when I'll be able to finish.
Also working on that example!
