### ISSUE TITLE
mask by polygon/feature collection and 2D mask

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#20]
A common operation is to mask using polygons or feature collections. Can we add a process for that?
Something like:
mask(datacube,geometry,replacement)

**Comment by m-mohr** [comment]
How should such a thing be provided? A multi-dimensional array? A GeoJSON geometry/vector data cube? Both?

**Comment by jdries** [comment]
I just came across this process:
https://github.com/Open-EO/openeo-processes/blob/master/filter_geometry.json
I believe it almost contains everything, but doesn't explicitly state that the output is also masked.

**Comment by m-mohr** [comment]
@jdries filter_geometry drops data and therefore reduces the cardinality, masking does not. It has similarities though. It's probably easy to add a geometry mask to the mask process, but how would you define a 2D mask?

**Comment by jdries** [comment]
A 2D mask would just be a single geometry/featurecollection? I would think a 3D mask is the harder case?

**Comment by m-mohr** [comment]
We discussed to either just add a new parameter for a geometry - or make it a separate process, depending on the outcomes of #26.

**Comment by m-mohr** [comment]
Added mask_geometry and I am wondering now what exactly they are replacing. Do we need a `dimension` property?

**Comment by m-mohr** [comment]
A polygon mask (GeoJSON or vector data cube) is now allowed to be specified as mask. Please review https://open-eo.github.io/openeo-api/v/0.4.0/processreference/#mask
