### ISSUE TITLE
Combination of mulitple filter_bbox proceses 

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#201]
say you have this process graph :
```
"load": {"process_id": "load_collection": ...
"bbox_a": "{"process_id": "filter_bbox", "arguments": {"data": {"from_node": "load"}, "extent": A ...
"bbox_b": "{"process_id": "filter_bbox", "arguments": {"data": {"from_node": "bbox_a"}, "extent": B ...
```

With these bounding boxes (and intersection bbox C):
```
A
+------+
|      |   B
|  +-------+
|  | C |   |
+------+   |
   |       |
   +-------+
```

What bbox should the *result* have?
- just intersection C?
- bbox B, with nodata everywhere except in intersection C?

Same question applies to `filter_temporal` and `filter_bands`.

**Comment by soxofaan** [comment]
Related question (but probably more an implementation detail): what bbox should be *loaded* initially?
- bbox A
- bbox C
- envelope bbox of A and B

In this example it is not a very interesting question, but when there are additional processes in between the `filter_bbox` processes (e.g. `apply_kernel`), it might cause differences.

**Comment by m-mohr** [comment]
It will just contain intersection C. 

Initially loaded should be the whole world as no extents have been specified there, but of course back-ends can do optimizations if no processes are in-between that actually "request" the data...
