### ISSUE TITLE
Basic array functions (Allow adding calculated band(s) without UDF)

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#202]
A number of use cases like this one:
https://github.com/Open-EO/openeo-usecases/blob/master/TUW_Radar_Image_Compositing/Python/gee_uc1_pol.py

use reduce_dimension on bands to compute a new band, and then go on to merge the new band back into the original datacube.
With a UDF on the other hand, it is possible to use apply_dimension, and simply write a function that returns the original bands  together with the calculated band(s).
It would be nice if this could also work for predefined processes, especially given that the merge_cubes function is not easy nor widely supported. (In the vito backend, it works, but is relatively slow because of the spatial join.)

Solution proposal:
a new process that basically constructs an array, so you can do something like:
array(input_array.array_element[0], input_array.array_element[1],input_array.array_element[0] - input_array.array_element[1])

another proposal would be to allow appending elements to an existing array:
input_array.append(input_array.array_element[0] - input_array.array_element[1])

both may be valid usecases: the second has the advantage that you do not need to explicitly list all elements in the original array, the first allows you to rewrite the bands entirely in one process.

**Comment by m-mohr** [comment]
I agree that our array functions are too limited. 

There is [a number of fundamental array operations](https://www.tutorialspoint.com/data_structures_algorithms/array_data_structure.htm), which should be available:

- Traverse − Visit all the array elements one by one: array_apply
- Insertion − Adds an element at the given index: Missing
- Deletion − Deletes an element at the given index: Missing
- Search − Searches an element using the given index or by the value: array_filter, array_find, array_element, array_contains, ...
- Update − Updates an element at the given index: Missing

I'd propose to add the following new processes. The processes has the same semantics as the array_element process regarding the index/label parameters.

- `array_create(?mixed value = null, ?integer length = 0)` (to create arrays)
    Creates an empty array if no parameter is given, otherwise fills the array with `length` elements, each having the value `value`.
- `array_set(array data, mixed value, ?integer index, ?mixed label)` (for insertion and update)
    If none of the parameters is given for array_set, it's added at the end. index = -1 could add at the beginning, if it is found to be useful.
- `array_drop(array data, ?integer length = 1, ?integer index, ?mixed label)` (for deletion)
    Optionally we can add the length parameter, which then drops from the given index or label the number of elements (e.g.  and `array_drop([1,2,3,4], 2, 1)` would result in `[1,4]`).
- `array_merge(array data1, array data2)` (for concatenation)


> a new process that basically constructs an array, so you can do something like:
> array(input_array.array_element[0], input_array.array_element[1],input_array.array_element[0] - input_array.array_element[1])

The only issue with this process is that our process description doesn't really support variable arguments (i.e. a ranom number of arguments passed to a function).

**Comment by jdries** [comment]
Yes, makes a lot of sense to me.
Some of these might be easy enough for me to try out in our backend, to further validate the proposal.
Also agree on priority: will simplify some use cases, and having them at MS1 makes them available for usecase work in MS2.

**Comment by m-mohr** [comment]
Open questions:
- Should array_create allow to set/assign "labels" (i.e. arrays with subtype labeled-array)?
- Should array_merge keep or discard array labels?

**Comment by m-mohr** [comment]
Additionally, the parameters (`"?mixed label``) to insert/update/delete from labeled arrays have the issue that then the processes just return an "array", not necessarily a "labeled-array", which can be an issue when typechecking. So either the processes need to have two schemas for the return value (array or labeled-array) or we need to remove the labeled array parameter and potentially make two separate processes for labeled arrays.

**Comment by soxofaan** [comment]
> This process has some "hidden" use cases, e.g. passing an empty array as one of the parameters duplicates an array

What's the point of duplicating an array? You only have non-mutable values in openEO, so copying values without any transformation makes little sense. Labels will be removed indeed, but  that  this only a side effect and it seems very strange to say to users: "to remove labels use `array_merge(a, [])`

**Comment by m-mohr** [comment]
Indeed, both have likely nearly no real added benefit, at least I'm not sure when either of the use cases would be required to do. So I guess we can leave the parameter required and not speak too much about it at all. The process itself just gives an example but doesn't speak about it in the descriptions.

**Comment by m-mohr** [comment]
5 new processes have been added: 
    - `array_append`
    - `array_concat`
    - `array_create`
    - `array_find_label`
    - `array_modify`
    - `date_shift`
    - `is_infinite`
    - `nan`
