### ISSUE TITLE
aggregate_zonal - definition + name

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-processes#21]
Since the input is one (or more) polygon(s), and because of the world 'zonal', I think of aggregating in the (x,y) dimensions. With this, it is my assumption/understanding that a polygon is (i) a 2-D shape, and (ii) usually lying in the (x,y) plane. However according to the process' description, (i) the dimension needs to be specified and (ii) it is singular in the description while I would expect to have a 2-element list, e.g. ['x', 'y'].
If not, what would be the application of aggregate_zonal in one dimension? And what could be the application of another combination of (2D) dimensions other than (x,y) ?

**Comment by m-mohr** [comment]
Yes, I think we can remove the dimension parameter.

**Comment by lforesta** [comment]
one more thing, zonal (and meridional) have specific meanings in meteorology (implying east-west and north-south directions), while the input polygon(s) is more generic so what about changing the name to aggregate_polygon or similar?

**Comment by m-mohr** [comment]
This name basically comes from map algebra (local, focal, zonal, global, see https://gisgeography.com/map-algebra-global-zonal-focal-local/) and also bases on one of our inital processes (zonal_statistics). I'm personally happy with both. What do the others think about it?

**Comment by jdries** [comment]
I always had the impression that 'zonal statistics' was widely used. Not sure if the term would be that confusing, but I don't have any meteorologists around to ask :-).

**Comment by lforesta** [comment]
It's fine to leave it as it is for now, we can change it at a later point in case a number of people mention it.

**Comment by m-mohr** [comment]
I asked @jwagemann and she told me it could indeed lead to some confusion and as we have a suitable replacement with `aggregate_polygon` I'd say let's rename it.
