### ISSUE TITLE
Better ML/AI integration?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#211]
User feedback included the desire for better integration with ML/AI workflows and having pre-defined processes for common tasks. This is not a concrete proposal, but an issue to keep track of requirements and ideas.

**Comment by jdries** [comment]
These use cases will need to be supported by SRR3 (march 2022) so initial processes will need to be defined around october 2021:
- regression models
- random forest models training + inference

**Comment by m-mohr** [comment]
This looks interesting as a base line for models in the API: https://github.com/radiantearth/geo-ml-model-catalog

**Comment by m-mohr** [comment]
Closing for now, fundamental processes are avaiuleble. We should open more specific issues to cater for additional requirements.
