### ISSUE TITLE
apply_dimension: Keep dimension labels if labeled array is returned?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#217]
One thing I recently noticed when working on #202 is that apply_dimension won't retain the dimension labels, even if the array returned from the process is labeled. That's inconvenient and we may want to consider changing this.

**Comment by soxofaan** [comment]
I don't completely understand the issue. From current docs:

> The dimension labels are preserved when the target dimension is the source dimension and the number of pixel values in the source dimension is equal to the number of values computed by the process. Otherwise, the dimension labels will be incrementing integers starting from zero,


So you mean that the labels of the resulting cube *dimension* are chosen following the above rule (take original dimension labels or do auto-increment), regardless of what labels are returned by the `process` child callback in `apply_dimension`?

It could be indeed useful to make sure the (new) dimension of the `apply_dimension` result cube  takes over the labeling of the   result arrays from the `process` child callback. That would be cleaner than an additional `rename_labels` process.

Problem is that there could be labelling inconsistencies between all the different child `process` calls for the same cube and how you resolve or prevent that.

**Comment by m-mohr** [comment]
> It could be indeed useful to make sure the (new) dimension of the `apply_dimension` result cube takes over the labeling of the result arrays from the `process` child callback. That would be cleaner than an additional `rename_labels` process.

Yes, the issue is exactly about this. So whether we should enable this or not. PR #218 is more working towards the direction to not enable it as otherwise processes will get more complicated to define as they also need to return labeled arrays and nor just arrays. The rename_labels is likely a bit annoying, but it's also not easy to enable returning array labels. If we merge #218 as it is right now, this issue would basically be obsolete with the decision to not enable returning array labels.

**Comment by m-mohr** [comment]
Seems we go for #218.
