### ISSUE TITLE
load_result: Align with load_collection 

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#220]
`load_result` (and `load_uploaded_files`) can only load a full result, but not filter extents like in load_collection. Should load_result be aligned (i.e. add spatial, temporal extents and metadata filters?)

**Comment by soxofaan** [comment]
We have already processes like `filter_temporal`, `filter_bbox`, `filter_bands`  to cover that, no?

> load_result can only load a full result, 

abstractly speaking yes, but a backend can work in a lazy-loading approach and limit the actual loading within the constraints provided by subsequent  `filter_` processes. Lazy loading is of course less straightforward to implement than handling direct `load_result` arguments.

The same question can be raise about `load_uploaded_files`, FYI

**Comment by m-mohr** [comment]
> We have already processes like `filter_temporal`, `filter_bbox`, `filter_bands` to cover that, no?

Yes, but the argumentation for adding those parameters to load_collection was that you have to load all data first just to discard a lot of data afterwards. Thus we added them and I think this argumentation is still valid, although I'm aware that VITO optimizes filter_ operations more than other back-ends.

> The same question can be raise about `load_uploaded_files`, FYI

Indeed!

**Comment by m-mohr** [comment]
Related issue: https://github.com/Open-EO/openeo-api/issues/376

**Comment by m-mohr** [comment]
With the recent discussions around #241 and read/get_vector in the Python driver, I'm wondering whether we should aim for something generic that doesn't care about the actual place the data is stored and can load cubes from different sources. I'm not sure we actually need to have specific functions for all of them. It would avoid the issue in #241 a bit at least.

Something like load_collection, but instead of specifying a collection ID, you specify either a URL, file on the back-end user workspace or a result (is basically also just a URL where you check whether it's accessible by the current user). 

`import(location, spatial_extent, temporal_extent, bands, filter) -> raster/vector cube`

**Comment by soxofaan** [comment]
that sounds like an interesting solution

but then the "collection_id" (or "location" in your snippet) probably has to become a more complex argument: a string that's a traditional collection_id or some kind of URL. Or optionally also an object that allows setting additional load options (e.g. filename globs, file type whitelists or blacklists, ...)

The next problem is then probably that you need a new "capabilities endpoint" where a backend can declare which kind of "locations" are supported

**Comment by m-mohr** [comment]
I'm not sure that is clear, but I'd leave load_collection untouched and not allow (internal) collection IDs in import.

The location could be defined as follows in schema:

```json
{
	"name": "location",
	"description": "...",
	"schema": [
		{
			"title": "Multiple files on server-side user workspace",
			"type": "array",
			"subtype": "file-paths",
			"items": {
				"type": "string",
				"subtype": "file-path"
			}
		},
		{
			"title": "Single file on server-side user workspace (we may want to remove this for simplicity)",
			"type": "string",
			"subtype": "file-path"
		},
		{
			"title": "Remote files (Absolute URL)",
			"type": "string",
			"subtype": "uri",
			"pattern": "^(http|https|s3)://"
		},
		{
			"title": "Batch Job ID",
            "type": "string",
            "subtype": "job-id",
            "description": "A batch job id, either one of the jobs a user has stored or a publicly available job.",
            "pattern": "^[\\w\\-\\.~]+$"
		}
	]
}
```

Yes, we have the issue that we overload some data types a bit in a number of processes.

**Comment by m-mohr** [comment]
@aljacob @lforesta @sophieherrmann I heard this (load_result) being discussed today as being required by a use-case. I didn't have that on my list as being required for UC3 or 6 in openEO Platform. Could you please clarify?
