### ISSUE TITLE
run_udf: "locally stored UDF"?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#225]
from https://github.com/Open-EO/openeo-processes/blob/75059c6566a7c8951d04467665252e74d5bb9c3a/run_udf.json#L4:

```
The process can either:

   1. load and run a locally stored UDF from a file in the workspace of the authenticated user. The path to the UDF file must be relative to the root directory of the user's workspace.
```

The use of "locally" and "workspace" is quite confusing here I think. This read like the user can work with a UDF file locally on their laptop/computer, and just send the (relative) path, which makes no sense

"workspace" is also quite ambiguous in this context: it could also be interpreted as the "work environment" the user is working in (e.g. local laptop or a remotely hosted jupyter notebook).

I think we have to find a more precise name for "workspace" to avoid ambiguity in these kind of docs. e.g.: "backend workspace"?

**Comment by m-mohr** [comment]
Ouch, I meant to make a PR, but accidentally pushed to the wrong branch.

@soxofaan Could you please verify that commit 3f3460e4 works better for you?

**Comment by soxofaan** [comment]
yes, the explicit "server-side user workspace" leaves no room for ambiguity
