### ISSUE TITLE
dimension properties in apply_dimension after labels have been discarded

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#234]
So if the callback in apply_dimension doesn't return the same array length as the source array, the labels get discarded (i.e. enumerated). That may work well for some dimension types like bands, but could an issue for the temporal dimension as the temporal reference is not available anymore. Should the dimension type be changed to `other` in this case?

**Comment by soxofaan** [comment]
While enumeration does not fit the usual calendar date/time structure, it could still be relative or symbolic time in some sense, so I don't think it is a problem to still call it a "temporal" dimension

**Comment by m-mohr** [comment]
Yes, but then you also need to reset the TRS (ISO 8601 / Gregorian calendar / UTC), too. And after renaming the labels you'd need to set the TRS again.

**Comment by soxofaan** [comment]
I'm not sure if I understand you correctly, but  you probably mean that the labels of a temporal dimension "MUST be strings compliant to ISO 8601"? So an dimension with enumerated labels can not be of type "temporal"?


in openapi.yaml I also found this https://github.com/Open-EO/openeo-api/blob/81dd248b9e8b8caeedbdd96c6a9dd8f3f56d0eb7/openapi.yaml#L4386-L4389 :
>  Data not compliant    with ISO 8601 can be represented as an             *Additional Dimension Object* with `type` set to             `temporal`.

I'm not sure though how to interpret this. Maybe this is a  leftover that became inconsistent?

**Comment by m-mohr** [comment]
I'm not sure myself what the implications of a temporal dimension are, but it probably must refer somehow to a specific instance in time that can be resolved, otherwise the default TRS (gregorian calendar) can't apply. A dimension with enumerated labels can surely be temporal if the TRS defines how to map them to time.

The part you found in the Collection spec is referring to the Data Cube Extension in STAC and has nothing to do with our data cube model. In STAC a dimension that is compliant to the temporal dimension json schema must be specified in metadata using ISO8601, but that doesn't imply anything to our data cubes. It's just a schema thing. An "Additional Dimension Object" can still specify a temporal dimension using another trs.
