### ISSUE TITLE
unify categories for mask and mask_polygon

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#238]
https://github.com/Open-EO/openeo-processes/blob/75059c6566a7c8951d04467665252e74d5bb9c3a/mask.json#L5-L7

https://github.com/Open-EO/openeo-processes/blob/75059c6566a7c8951d04467665252e74d5bb9c3a/mask_polygon.json#L5-L8

**Comment by m-mohr** [comment]
Thanks, fixed
