### ISSUE TITLE
`if`: branching behavior?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#246]
This came up while thinking about #241 

openeo-processes defines the `if` process as:
> `if(boolean|null value, any accept, ?any reject) : any`
> If the value passed is true, returns the value of the accept parameter, otherwise returns the value of the reject parameter.
> This is basically an if-then-else construct as in other programming languages.

However, it is defined as a regular process (think "function"), and not as a control structure as in other programming languages. The difference is subtle but can have large impact.
In a traditional "if" control structure you have something like an "if" expression and an "else" expression, and only one of these expressions is evaluated, depending on the condition.
As a regular a function however, you have no expressions, but an "if" _value_ and and "else" _value_. In a straightforward or naive implementation of evaluating functions or processes, you implicitly assume that _both_ values are calculated before you apply the function itself. In case of "if" this is probably not what a user expects or wants.

For example in #241, the "if" would be used to convert a given value in different ways, depending on it's type. In this case you first want to pick the desired conversion approach and apply it to the input. Not the other way around: first apply all conversion approaches and then pick the desired output.

**Comment by m-mohr** [comment]
The `if` process indeed is a special case that process graph parsers should consider and run just what is required to run. We don't have control structures in openEO and thus this depends on the back-end implementation. The back-ends probably want to implement this to stay competitive wrt costs...
Alternative would be to put everything in callbacks, but that seems to make things more complex then they need to be from the user perspective....

**Comment by soxofaan** [comment]
FYI: the VITO backend currently does not give `if` special treatment at the moment, so both the "if" and "else" value are calculated regardless of the condition. 
In principle it should be feasible to add it as a special case, but things might get complicated because when we process a process graph we first do a dry run before the real wet run to extract information that could be relevant for load_collection nodes. In the dry run we would not have a concrete value for the condition, so we would be forced to follow both the "if" and "else" branches. However, if the dry run and wet run are different we might in get trouble elsewhere.

It would be interesting to know how other backends handle `if` in this regard. @lforesta  @aljacob ?

**Comment by soxofaan** [comment]
I see a couple of paths to close this case:

 1. don't change anything. This would implicitly mean that it's up to the backend to interpret how if should be implemented
 2. don't change behavior but explicitly mention in docs that it's up to the backend to choose how it's handled (calculate both branches naively or calculate only the relevant branch)
 3. specify that a backend implementation should only calculate the branch that corresponds with the condition
 4. specify that a backend implementation should always calculate both branches

I'm not sure what's the best option at the moment

**Comment by m-mohr** [comment]
I'd say it's either 2 or 3.

1 is basically 2, but I don't see why adding a clarification is bad. So I see no point in choosing 1.
2 is easy to do, but bad for comparability/reproducibility.
3 is more complex to implement.
4 doesn't make much sense to force back-ends to compute not needed data.

**Comment by m-mohr** [comment]
An implementation guide has been added.
