### ISSUE TITLE
Specify default resampling method in sar_backscatter

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#249]
@jdries:
> The best resampling method for SAR backscatter is apparently bilinear.
> Given that it can not be set by the user, the process documentation should mention that bilinear interpolation is used.
> 
> @gmilcinski @aljacob Any expert advice on how to correctly describe this parameter, or is there a reference to literature?

@aljacob:
> This paper gives a nice overview: https://doi.org/10.3390/data4030093 It is from the developers of pyrosar. They also use bilinear resampling. Important is also stated in the paper that DEM and backscatter are interpolated in the same way. Which was also pointed out by Magdalena during the meeting with her.

@jdries:
> So we want something like:
> Implementations of this process are strongly encouraged to use bilinear interpolation, both for resampling the DEM, and the backscatter. This paper motivates this choice of parameter in detail: https://doi.org/10.3390/data4030093 .

**Comment by m-mohr** [comment]
Such a recommendation is not good for interoperability and unit tests. Either we should require bilinear resampling or introduce a parameter that has bilinear as default value.

**Comment by jdries** [comment]
Fine for me to make it mandatory.

**Comment by m-mohr** [comment]
PR is up for review: https://github.com/Open-EO/openeo-processes/pull/250

**Comment by m-mohr** [comment]
Merged.
