### ISSUE TITLE
load_collection and polygon, return only data inside the polygon?

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes#256]
I am wondering if by API definition, when providing a polygon in load_collection, we need to return the masked data or just the data contained the minimum bbox of the polygon.

**Comment by m-mohr** [comment]
The process says:

> The process puts a pixel into the data cube if the point at the pixel center intersects with the bounding box or any of the polygons (as defined in the Simple Features standard by the OGC).

I'm understanding that as follows (and it was meant this way): The data cube has the extent of the box of the polygons. All pixels that do not intersect with the polygon(s) contain no-data / null values. All other values that intersect with the polygon(s) contain data from the given collection.

Would you understand it differently from the description? If yes, how can we improve the descriptions?

**Comment by clausmichele** [comment]
No it's fine, it is also as I understand it. But maybe we can clarify that outside the polygon we have to set data to no-data/null, which is not clear (I was wrongly setting them to zero).

**Comment by m-mohr** [comment]
Okay, I added some clarifications to load_collection: https://github.com/Open-EO/openeo-processes/commit/58268036307454c80ffb0ea3d5cc0f8b0eab709f
