### ISSUE TITLE
aggregate_temporal(_period): handling of empty intervals

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#263]
One use case for aggregate_temporal is to create data with fixed time intervals. Meaning if I set the period to 'week', I want exactly one observation every week. In practice, this is often combined with e.g. linear interpolation, to fill nodata values in case a given observation was clouded.

However, with the current spec, it is not clear what needs to happen if a given interval doesn't intersect with data in the input datacube? Does the returned datacube have an observation filled with 'nodata' for that interval, or is there no observation at all?

For my current use case, I would like it to be filled with nodata, but this is not necessarily the default case (not sure there).
Do we need a parameter or clarification to pin down the desired behaviour?

**Comment by m-mohr** [comment]
VITO is the only implementation right now, so it seems reasonable to simply clarify the behavior in the process. For me, no-data seems to be the most reasonable choice.

What other options would a parameter allow? The default can still be no-data so if there's no other use-case yet, I'd just stick with no-data and add the parameter with no-data as default once required.

**Comment by m-mohr** [comment]
Actually, this is implicitly clear: All reducers return null (no-data) if an empty array is passed. So it's a user-defined behavior, reducers should also be called for "empty" intervals and pass an empty array. It's then up to the reducer to decide what to do. By default, this is null (no-data). So I'm not even sure we need to do something here, maybe only clarify that empty array should still be computed?

**Comment by m-mohr** [comment]
See #265
