### ISSUE TITLE
Buffer process

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#264]
Request from VITO: A buffer process.

Something like `buffer(data:vector-cube, distance:number, unit:string="meters")`

**Comment by mkadunc** [comment]
IMO it would make more sense to have a more atomic operation:
- buffer for single geometry: `buffer(geojson:object, distance:number, unit:string="meters")` to be then mapped over an array, or
- buffer for array of geometries: `buffer(array[geojson:object], distance:number, unit:string="meters")`

Unless we've settled on `vector-cube` as the way to represent (arrays of) geometries in openEO, in which case 💯👍 .

**Comment by m-mohr** [comment]
> * buffer for single geometry: `buffer(geojson:object, distance:number, unit:string="meters")` to be then mapped over an array, 

What would this actually return so that it's useful? GeoJSON again? A raster cube (i.e. a mask)?

> Unless we've settled on `vector-cube` as the way to represent (arrays of) geometries in openEO, in which case 💯👍 .

I think we should finally settle on something. The next step is probably to write a PSC proposal for vector cubes and then start defining processes based on it?!

**Comment by jdries** [comment]
The return type should be the same as the input vector type.

As for the input type: if geojson implies that it can only be in EPSG:4326, then maybe it's better to define a proper, more abstract, vector-cube.
For me, a vector cube should probably be something like a feature collection at this moment, and not define too much properties yet, to allow for some evolution.

**Comment by m-mohr** [comment]
> The return type should be the same as the input vector type.
> As for the input type: if geojson implies that it can only be in EPSG:4326, then maybe it's better to define a proper, more abstract, vector-cube.

So that would be GeoJSON then, which is EPSG:4326 only, yes. 
https://github.com/opengeospatial/ogc-feat-geo-json (which is adding CRS to GeoJSON) is just staring and thus not an option in the near future. Also, GeoJSON doesn't really scale well for very large collections.

**Comment by edzer** [comment]
> So it seems reasonable to write up something about vector cubes...

[here](https://keen-swartz-3146c4.netlify.app/datacube.html#vectordatacubes) is @jonathom 's figure. Vector cubes are arrays with feature geometries associated to (at least) one array dimension. You can put them in GeoJSON or in gpkg, but NetCDF is a more natural form. Anyway there'll be little support of software able to read such arrays whatever the format, so optional output in the form of the long table with records (feature geometry, time, band, pxel value) is more likely to be useful to many users. That long form is a usual simple feature set, with feature geometries repeated for time & band.

Let me know if you have ideas how to improve a write up, and where this should go.
