### ISSUE TITLE
Improve merge_cubes definition

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes#266]
I would suggest to modify this string from https://processes.openeo.org/#merge_cubes since it does not specify anything about the overlap resolver for the last case.

from
> Merging a data cube with dimensions x, y, t with another cube with dimensions x, y will join on the x, y dimension, so the lower dimension cube is merged with each time step in the higher dimensional cube. This can for instance be used to apply a digital elevation model to a spatiotemporal data cube.

into

> Merging a data cube with dimensions x, y, t with another cube with dimensions x, y will join on the x, y dimension, so the lower dimension cube is merged with each time step in the higher dimensional cube. This can for instance be used to apply a digital elevation model to a spatiotemporal data cube. **An overlap resolver is required to resolve the overlap for all pixels.**

**Comment by m-mohr** [comment]
Yes, that makes a lot of sense to me. Will issue a PR.

**Comment by jdries** [comment]
Not in all cases: when merging a DEM band with other bands, the DEM is simply concatenated.
So maybe we should split up in two cases: 
1. x,y,t + x,y  (requires overlap resolver)
2. x,y,t,bands + x,y,bands (this is the DEM case that is given here as example, no overlap resolver)

**Comment by m-mohr** [comment]
@jdries Then the bullet point overall is pretty misleading and should be rewritten.

**Comment by m-mohr** [comment]
Thinking a bit more about it, I think we have the following cases:
1. x,y,t + x,y (requires overlap resolver)
2. x,y,bands + x,y (requires overlap resolver)
3. x,y,t,bands + x,y (requires overlap resolver)
4. x,y,t,bands + x,y,bands falls into multiple categories. Depending on how the bands are structured. If they have the same bands, they need an overlap resolver. Bands that do only exist in one the cubes, get concatenated.

That results in the following for 1, 2 and 3:
> 4. Merging a data cube with dimensions `x`, `y`, `t` / `bands` or `x`, `y`, `t`, `bands` with another cube with dimensions `x`, `y` will join on the `x`, `y` dimension, so the lower dimension cube is merged with each time step and band in the higher dimensional cube. This can for instance be used to apply a digital elevation model to a spatio-temporal data cube. An overlap resolver is *required* to resolve the overlap for all pixels.

4. can be derived from the other examples, I think. I may be on the wrong track here though.

**Comment by m-mohr** [comment]
See PR #267
