### ISSUE TITLE
Reverse array_find

### ISSUE THREAD

**Issue by Bart92** [Open-EO/openeo-processes#269]
I'm currently working on a use case in which I'm trying to calculate the start and end of growing season in a rather simplified way by basically just putting a threshold on the amplitude of a vegetation index. The array_find function has proven useful for finding the start, but finding the end would require the reverse of the array [::-1]

**Comment by m-mohr** [comment]
Thanks, this is interesting. Could you make use of `array_filter` to extract the data you need?

In theory, there's also the `rearrange` process to change the order of the array, but that feels overly complicated for this use case. 
So if you can't make use of array_filter, I'd say the next step would be to include either `array_reverse` or add a parameter `reverse` to `array_find`.
