### ISSUE TITLE
Keep GeoJSON (vector) properties

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#270]
Re 3: In general, it would be very useful to keep the GeoJSON properties so that people can actually identify the Features they've provided in the results. I'm not sure if the processes describe this well enough, but we can probably clarify this in general for vector file formats that handle properties.

_Originally posted by @m-mohr in https://github.com/Open-EO/openeo-geopyspark-driver/issues/84#issuecomment-876430614_

**Comment by clausmichele** [comment]
After some discussion, we agreed that this feature is crucial in the following scenario:
1. We need to train a ML model
2. We create a geoJSON containing the polygons with associated classes (for classification) or target values (for regression)
2.1 (Optional) We use the (still to be defined) process polygon_to_points process to extract several points from the geometries.
3. We use aggregate_spatial to create the input vector-cube for the ML model training process.

The ML model training process will need to distinguish which one is the class/target from the output of aggregate_spatial (back-end specific?).

For other scenarios where we do not define the labels/classes/target by ourselves inside the geoJSON but use instead two different rasters the problem does not persist.

**Comment by m-mohr** [comment]
I'm wondering whether it would be the easiest solution to add a new parameter `keep_properties` (default: false) that can be enabled to add this behavior? Or do we assume that this should be possible by default and just "clarify" that keeping the properties is the expected (but baldy documented) behavior of the existing process?

**Comment by jdries** [comment]
I'm considering to start keeping them by default in our processes, mainly to avoid that users would suddenly have to specify this extra argument. Keeping those properties should also not break existing code.
Backends that do not keep them yet, but also do not support training ML models, would not be hugely impacted.

**Comment by jdries** [comment]
Dev telco: avoid adding a parameter, try to implement in the backends.
Process documentation would need to be updated.

**Comment by m-mohr** [comment]
Would a simple addition such as "Vector properties are preserved for vector data cubes and all GeoJSON Features." be good enough?

cc @soxofaan

**Comment by soxofaan** [comment]
yes, I would not overthink it for now. We can finetune it if actual implementation details become more clear

**Comment by m-mohr** [comment]
Done, see commits above (and potentially below).
