### ISSUE TITLE
run_udf exceptions

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#273]
https://github.com/Open-EO/openeo-processes/blob/3dc5e7853139b8d7a03d70dd0da3c7c70704b758/run_udf.json#L93-L97

Why only an exception for invalid version, but not for invalid runtime?

Possible solutions: 
- add `InvalidRuntime`
- rename to `InvalidRuntime` to cover both invalid versions and runtimes
- cover everything with standard `ProcessParameterInvalid`

**Comment by m-mohr** [comment]
Adding InvalidRuntime seems like a simple solution. See 203c1b6a
