### ISSUE TITLE
quantiles: Unify probabilities and q

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#293]
Originated in https://github.com/Open-EO/openeo-processes/issues/278:

The quantiles process is old and has the issue that one of two optional parameters is required, which we try to avoid nowadays in openEO (then only array_element would be left). Also, the naming is a bit confusing to some communities.

The proposal is to merge probabilities and q into a single parameter `q`:
```
{
  "name": "q",
  "description": "Quantiles to calculate. Either a list of probabilities or the number of intervals:\n\n* Provide an array with a list of probabilities to calculate quantiles for. The probabilities must be between 0 and 1 (inclusive).\n*Provide an integer to specify the number of intervals to calculate quantiles for. Calculates q-quantiles with equal-sized intervals.",
  "schema": [
    {
      "title": "List of Probabilities",
      "type": "array",
      "items": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      }
    },
    {
      "title": "Number of Intervals",
      "type": "integer",
      "minimum": 2
    }
  ]
}
```

By itself, this is a breaking change. If we want to change this earlier without breaking anything, we could simply change the schema for q as proposed above and deprecate the parameter probabilities. @soxofaan I think I'd like that...

**Comment by m-mohr** [comment]
Hmm, `probabilities` is listed before `q` in the parameters. The resulting calls in JS (i.e. non-named parameter languages) would become `quantiles(x, undefined, [0,5])` - unfortunate.

**Comment by soxofaan** [comment]
can't we just update the definition of `probabilities` and deprecate `q`?

**Comment by m-mohr** [comment]
Sure, that's also possible. I thought the `q` was preferred by the Python community due to the xarray implementation so did not consider that. But works for me. I can make a PR for that.
