### ISSUE TITLE
Which quantile type?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#296]
Related: while looking up example definitions and descriptions I stumbled on this:
https://blogs.sas.com/content/iml/2017/05/24/definitions-sample-quantiles.html referencing https://www.amherst.edu/media/view/129116/original/Sample+Quantiles.pdf

> there are nine definitions of sample quantiles that commonly appear in statistical software packages. 

If we want consistency across backends, we probably have to pick which flavor of  "sample quantiles"  we want.

at the moment I  have no idea which flavor that's currently used in VITO/EODC backends for example

_Originally posted by @soxofaan in https://github.com/Open-EO/openeo-processes/issues/294#issuecomment-952671519_

**Comment by dthiex** [comment]
The Sentinel Hub Statistical API is not yet connected with openEOP but there we use the  'higher' method as described on the [numpy.percentile function](https://numpy.org/doc/stable/reference/generated/numpy.percentile.html).

Maybe we can use by default the same interpolation method on all backends but if backends support multiple interpolation methods allow this to be set as an optional parameter?

**Comment by jdries** [comment]
VITO uses this:
https://commons.apache.org/proper/commons-math/javadocs/api-3.5/org/apache/commons/math3/stat/descriptive/rank/Percentile.html
Here:
https://github.com/Open-EO/openeo-geotrellis-extensions/blob/develop/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/OpenEOProcessScriptBuilder.scala#L666

And it seems we can choose which type to use:
https://commons.apache.org/proper/commons-math/javadocs/api-3.5/org/apache/commons/math3/stat/descriptive/rank/Percentile.EstimationType.html

**Comment by m-mohr** [comment]
Thanks all, I'll take this as a baseline for a clarification/improvement.

**Comment by m-mohr** [comment]
@edzer You probably have the most experience with statistics, is there any type that you'd think is the most reasonable (default) choice in our openEO context?

Surveying the defaults from other environments right now, Python seems pretty set on linear, R seems to have another default, but is configurable.

**Comment by m-mohr** [comment]
PR #303 is up for review.
