### ISSUE TITLE
load/save_model for ML models

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#300]
Propose two processes load_model and save_model to load and store ML models. Should be similar to load_results with loading from job id and URL. The input could be STAC items described with the (upcoming) ml-model extension: https://github.com/stac-extensions/ml-model

**Comment by jdries** [comment]
I guess this is the metadata spec that we're referring to:
https://github.com/radiantearth/geo-ml-model-catalog
?

**Comment by m-mohr** [comment]
The Geo-ML-Model-Catalog was the first attempt from Radiant to write this specification *not* based on STAC, but this evolved somehow into a work-in-progress STAC extension: https://github.com/stac-extensions/ml-model
I'll check with Jon what the long-term plan is with the Geo-ML-Model-Catalog repo is.

**Comment by m-mohr** [comment]
> The STAC extension one is now the main repo. The GMLMC one will be archived after we [have] transfer[ed] everything.

**Comment by m-mohr** [comment]
@jdries @aljacob Do you have an idea what metadata would be minimally required for our use case?

**Comment by jdries** [comment]
Really minimally, the model just needs a name. But we'll probably also specify the type of model file, so we can determine if it's compatible with our software.

**Comment by m-mohr** [comment]
Thanks and good to know, but I guess I should have asked what you need minimally (so that I can ensure this is at least available) and what other information would be useful in addition? @jdries 

From what you have listed right now, we may not really need a model extension yet.
- The name is either the STAC id and/or title.
- The generating software could be exposed via the processing extension although you'd run into issues if the software can generate multiple types so maybe a model file type would need to be part of a new extension. Looking at standardization: How could we ensure that model types match between implementations? Like is there a common name for each model type that we could refer to? Otherwise, implementations may choose different type names although they refer to the same thing.
