### ISSUE TITLE
parameter naming in linear_scale_range

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#302]
https://github.com/Open-EO/openeo-processes/blob/60fb5e22579f34010de42af71c3d2d70f2dea906/linear_scale_range.json#L20

Parameter names of `linear_scale_range` use "dromedaryCase": `inputMin`, `inputMax`, `outputMin`, `outputMax`.
I think we standardized on "snake_case" for both process names as parameter names.

Fixing this will obviously be a breaking change, but maybe it could be tackled together with changing the process name too (and deprecating "linear_scale_range"). I always found "linear_scale_range" a bit strange: there is no verb and it has two very similar nouns "scale" and "range". Moreover, it could make sense to include the clipping feature (#159) in the new name too.

**Comment by m-mohr** [comment]
Nice catch, I never realized this. I can recall that I was requested to rename the process at the VITO sprint (it had a different name before) and since then the process hasn't changed a lot. Although I'm always up to align and make things nice, it's a bit of an annoyance and interoperability issue to "duplicate" the process.

**Comment by jdries** [comment]
This one is rather actively used, so deprecating it means in practice that you then need to continue supporting two versions. This happened with a lot of OGC implementations, where even entirely new service implementations are forced to continue implementing 'deprecated' things.
So for usability, I think it's easier to really just improve our clients, which is what most people actually interact with.

**Comment by soxofaan** [comment]
yeah, I'm not pushing to tackle this asap, just reporting this to be considered for a future major/breaking release

**Comment by m-mohr** [comment]
We'd now have the chance to update this with 2.0, but I'm actually not sure we should do this. Might be one of those cases where we can just acknowledge that nobody is perfect and that this is just part of how it evolved. Most of the programming languages have these kind of "old" weird things... Especially looking at you, PHP! ;-)
