### ISSUE TITLE
Sampling

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#313]
For several use cases such as ML training, one or more sampling processes could be useful. 

This came up in the discussions around #295 

Related work: 
- https://eo-learn.readthedocs.io/en/latest/eolearn.geometry.sampling.html
- https://developers.google.com/earth-engine/apidocs/ee-image-sample?hl=en

Alternative: 
- polygon_to_point?
- #155

**Comment by clausmichele** [comment]
The sampling process could also allow to "extract" all the valid points setting a parameter. This would cover the case where we select some polygons (filter_spatial) and we want to keep all the pixels inside of them for training.

Some questions that come up in my mind:
1. Is the output a vector-cube?
2. Does it keep x,y information about the points or do we discard them?

**Comment by clausmichele** [comment]
The sampling will be performed using a new process called polygon_to_points:
- polygon_to_points takes as input a geoJSON (or other supported formats, TBD) and returns the same structure with point coordinates
- possible parameters are:
1. Sampling strategy: random, fibonacci, ...
2. Max number of points to extract
3. Other?

**Comment by m-mohr** [comment]
* We still need to verify which name to choose, they should be somewhat aligned between vector processes.
* Input should probably be GeoJSON or vector cube, as usual.
* Would it be useful to also pass lines and get points for them or should this be purely polygon focused?
* Sampling strategy could be a callback (so random and Fibonacci would be separate processes) or a given set of methods.

**Comment by clausmichele** [comment]
Sorry for being not so clear, with same structure I was referring to the geoJSON or vector-cube structure/data format, not the content itself.

**Comment by m-mohr** [comment]
Thanks for the clarification, @clausmichele.

I thought about basing percentages around the pixel centers. You should have a known number of pixels and could create a list of points for the pixel centers, right?

**Comment by clausmichele** [comment]
From the last meeting I understood that the process should take as input geometries (geoJSON) and output also geometries to be used in aggregate_spatial, that's why I firstly called it "polygon_to_points". The output would be a list of points which can be used in aggregate_spatial to create a vector-cube for training the ML model.

@mattia6690 @jdries can you comment on this? Do I remember correctly?

**Comment by m-mohr** [comment]
Ah, okay! Then I misunderstood or remembered incorrectly. I can change that. That makes the process simpler by only creating points from a shape without directly combining them with the values from the raster cube. That's also fine for me, just didn't fully understood the idea then. Stay tuned for an updated version... :-)

**Comment by m-mohr** [comment]
I've added another process `vector_to_points` to support the use case you have described. So depending on what we want, we can choose one of the processes in this PR and discard the other one. Or if both processes are potentially useful, merge both.

@clausmichele Is the new process okay for you?

**Comment by ValentinaHutter** [comment]
> From the last meeting I understood that the process should take as input geometries (geoJSON) and output also geometries to be used in aggregate_spatial, that's why I firstly called it "polygon_to_points". The output would be a list of points which can be used in aggregate_spatial to create a vector-cube for training the ML model.
> 
> @mattia6690 @jdries can you comment on this? Do I remember correctly?

I am working on an implementation of `aggregate_spatial` at EODC. Is there an example of `aggregate_spatial` being used with `vector_to_random_points` or `vector_to_regular_points` somewhere?

**Comment by clausmichele** [comment]
This is my implementation of it https://github.com/SARScripts/openeo_odc_driver/blob/d1383aa872bdef5a8bde37f5d48b1f7a56cdd57e/openeo_odc_driver.py#L566

There's a lot of room for improvements, the properties are not kept for example. I will provide you also an example using vector_to_*_points soon.

**Comment by ValentinaHutter** [comment]
Thanks a lot, that's great! :)
