### ISSUE TITLE
filter_temporal: allow multiple extents

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes#320]
**Process ID:** filter_temporal

**Describe the issue:**
I currently have to use multiple times filter_temporal in order to get a set of particular dates from a datacube. I need to use merge_cubes multiple times to merge the obtained results. This leads to an unnecessary complex process graph:
![image](https://user-images.githubusercontent.com/31700619/153892173-7996098d-6cce-400f-aba6-b0fcde316ab2.png)

**Proposed solution:**
Allow multiple time ranges in filter_temporal. Already proposed here: https://github.com/Open-EO/openeo-processes/issues/88#issuecomment-555005938

**Comment by m-mohr** [comment]
What you do sounds like a use case for aggregate_spatial. I'm wondering whether you could use that. It should reduce complexity by a lot. Should we have a call and check whether we can make that work instead?

**Comment by clausmichele** [comment]
I see, but I would not need to apply any reducer to the selected data, whereas aggregate_temporal requires it

**Comment by m-mohr** [comment]
@clausmichele You could just return with "constant".

**Comment by m-mohr** [comment]
Michele will try to use aggregate_temporal with array_element (index: 0). That should fulfill the usecase good enough for now.
