### ISSUE TITLE
rename_labels: confusion between target and source

### ISSUE THREAD

**Issue by Ardweaden** [Open-EO/openeo-processes#321]
**Process ID:** rename_labels

**Describe the issue:**

The definition states:

>  If the dimension labels are not enumerated and the `target` parameter is not specified, the `LabelsNotEnumerated` exception is thrown. 

Similarly later, by the information about the `target` parameter:

> The dimension labels in the data cube are expected to be enumerated if the parameter `target` is not specified.

I fail to understand this. Firstly, `target` is a required parameter. Secondly, one would expect that  `source` is necessary if the labels are not enumerated and if not, the error would make sense.  

**Proposed solution:**

Perhaps `source` was meant in both cases.

**Comment by m-mohr** [comment]
Thanks for bringing this up. Indeed, `source` was meant in both cases.

**Comment by m-mohr** [comment]
Fixed in https://github.com/Open-EO/openeo-processes/commit/f12ffb2a0a14f1aa45f452d615af2aa39ce4eef2
