### ISSUE TITLE
Vector cube usage in `aggregate_spatial`, `filter_spatial`, `mask_polygon`, ...

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#323]
Processes `aggregate_spatial`, `filter_spatial`, `mask_polygon` have a `geometries` (or `mask`) parameter that currently is of type `geojson:object`. Likewise, `load_collection` and `load_result` have a `spatial_extent` parameter that can be `geojson:object` (among other options).

Once we improve support for loading/processing vector cubes (e.g. #322)  these processes should also allow `vector-cube` as data type for these parameters,
so that a user can  pass the geometries with a file/url instead of embedding geojson in the process graph

**Comment by m-mohr** [comment]
Yes, that's on the todo list for sure.

**Comment by clausmichele** [comment]
Should we have then a `load_vector_cube` process to load a vector data from an URL?

**Comment by clausmichele** [comment]
Allowing `aggregate_spatial` to get vector-cube as input is necessary to proceed with the random_forest pipeline. In the meanwhile I will modify the process locally for some tests.
![image](https://user-images.githubusercontent.com/31700619/154451507-534ad1b4-e8d9-4ab3-84cd-6bc9d7510dff.png)

**Comment by m-mohr** [comment]
Closely related: #343 and #346 

I'm not sure I'd add vector-cube as input for load_result and load_collection. These are compromises of simplicity and utility.
You may then just add it to filter_spatial as a dedicated process that can be used to filter based on vector cubes.
