### ISSUE TITLE
round: confusing definition of rounding

### ISSUE THREAD

**Issue by Ardweaden** [Open-EO/openeo-processes#326]
**Process ID:** round

**Describe the issue:**
Documentation states:

> If the **fractional part of x** is halfway between **two integers**, one of which is even and the other odd, then the even number is returned. This behavior follows [IEEE Standard 754](https://ieeexplore.ieee.org/document/8766229).

However, based on the definition in the standard, I'm not sure this should hold for integers _only_. I would expect this would be used at arbitrary point, e.g. `round(x=0.25, p=1) => 0.2` and `round(p=0.35, p=1) => 0.4`.

**Proposed solution:**
Clarify that the number should be rounded to the one with even least significant digit.

**Comment by m-mohr** [comment]
Yes, I agree. I'll issue a PR.

**Comment by m-mohr** [comment]
Please see PR #327
