### ISSUE TITLE
Unit in vector processes

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#330]
With mostly all vector processes we hit the point where you need to specify a length/distance/... and that needs to be specified in a specific unit. So we have seen different proposals across the PRs:

1. Always meters
2. Always degree
3. Unit of the SRS (usually either meter or degree)

There are several issues with the options:
1. What does "meters" mean specifically? e.g. https://github.com/Open-EO/openeo-processes/pull/314#discussion_r792528112 This is probably the most user-friendly option?
2. What does "degree" mean specifically? e.g. https://github.com/Open-EO/openeo-processes/pull/315#discussion_r814799187
3. Users need to explicitly understand the SRS, which is the least user-friendly option.

I think it's not a good idea to discuss this for every new process. So what's the preferred option that we adopt in general?

PS: In existing (raster) processes we have:
- apply_neighborhood: unit of srs or m or px
- resample_spatial: unit of srs

**Comment by mkadunc** [comment]
From my experience the "default distance is the unit of CRS" just leads to a lot of errors made by users. I suggest making the `unit` parameter mandatory from the start, which will ensure that the users understand what the number they're inputting means.

If backends don't want to convert or if there's ambiguity in how the conversion happens, an error can be thrown in case the specified unit doesn't match the CRS unit.

**Comment by edzer** [comment]
I agree. And also: `degree` can never be a distance unit.

**Comment by soxofaan** [comment]
So if I understand correctly, the "unit = unit of CRS"  approach is not a favorable option, even when it's just an initial solution?

> I suggest making the `unit` parameter mandatory

Instead of a separate `unit` parameter, I would be more in favor of defining the distance as an object containing both the value and unit, e.g. like 
```json
    "distance":  {"value": 10, "unit": "m"},
```
We already use that approach in `apply_neighborhood`. I think it's schema-wise easier and more self-contained.

**Comment by mkadunc** [comment]
"unit_of_crs" would also be acceptable, though not needed IMO (almost all CRSs will have either degree or meter as units, and it shouldn't be too difficult for the user to pick the correct one).

I prefer the syntax with an object — `distance: {"value": 10, "unit": "m"}`.

Re Edzer's opposition to having 'degree' as a distance unit — not sure what to do when CRS is geographic... Users will treat 'degrees' as just another unit, so it will be very hard to dissuade them, unless we come up with a name for this quantity that isn't "distance" (but e.g. "quasiEuclidean2NormOfCoordinateDifference" 😉 ). This is probably not a discussion for this issue, but something that should be addressed elsewhere.

**Comment by m-mohr** [comment]
Quick survey:
- apply_neighborhood: value/unit object
- date_difference + date_shift: value + unit parameters
- vector_buffer + vector_to_regular_points: no unit, required in unit of srs

**Comment by m-mohr** [comment]
Vector processes only allow distances in meters.
- Vector data has CRS with unit: meter -> use vector process
- Vector data has CRS with unit other than meters: -> throw error (or parameter later?) -> use reproject function to convert to a CRS with meters -> use vector process then

"meters here means the meters as defined by the CRS, not necessarily actual meters"

e.g. in vector_buffer would change from "The distance of the buffer in the unit of the spatial reference system." to "The distance of the buffer in meters as defined by the SRS." and keep the parameter numerical.

For GeoJSON this may need explicit reprojection? -> #412

**Comment by m-mohr** [comment]
The decision from https://github.com/Open-EO/openeo-processes/issues/414#issuecomment-1492003851 also applies here. We are strict with the errors and throw an error if not meters. We add a chapter to the implementation guideline that back-ends can diverge from this and still implement more.
