### ISSUE TITLE
 array_interpolate_linear: clarification of return values

### ISSUE THREAD

**Issue by zcernigoj** [Open-EO/openeo-processes#333]
**Process ID:**  array_interpolate_linear

**Describe the issue:**
The documentation (https://docs.openeo.cloud/processes/?#array_interpolate_linear) says that the return value for this process can be array or `null`.
> **Return Value**
> An array with no-data values being replaced with interpolated values. If not at least 2 numerical values are available in the array, the array stays the same.
>
> Data type: `number`, `null`

The problem is that it's not really clear when a `null` should be returned.

E.g. it doesn't say if the `null` should be propagated if `data` itself is `null`.
For an empty array I would assume that an empty array should be returned ("_If not at least 2 numerical values are available in the array, the array stays the same._")

**Proposed solution:**
Add more info to the documentation / change the documentation.

**Additional context:**
/

**Comment by m-mohr** [comment]
Good catch. Actually, the return value is completely wrong. It should be array<number|null> instead and then I think it should be clearer what happens, right? See the commit above for the fix.

**Comment by zcernigoj** [comment]
Thanks, the changes make it clear now.
