### ISSUE TITLE
rename_labels finetuning

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#335]
https://github.com/Open-EO/openeo-processes/blob/a4704b2fe35ad21225e359e1a1b84868c21f6442/rename_labels.json#L4

> If the array for the source labels is empty (the default) ...  The number of the source and target labels must be equal.

It's a confusing to have these two statements in the same paragraph, without an "otherwise" or something alike

On a more general note, is there a particular reason that `[]` is used as special value to trigger the handling of "enumerated labels"  instead of `null`?

https://github.com/Open-EO/openeo-processes/blob/a4704b2fe35ad21225e359e1a1b84868c21f6442/rename_labels.json#L39

> The names of the labels as they are currently in the data cube. The array defines an unsorted and potentially incomplete list of labels that should be renamed to the names available in the corresponding array elements in the parameter `target`.

It feels like these two sentences can be condensed more efficiently. Also, I find the adjective "unsorted" confusing in this explanation, as the label order is essential for the operation.
Suggestion:

> Original names of the labels to be renamed to corresponding array elements in the parameter `target`. It is allowed to only specify a subset of labels to rename, as long as the `target` and `source` parameter have the same length.

**Comment by m-mohr** [comment]
> It's a confusing to have these two statements in the same paragraph, without an "otherwise" or something alike

Reworded, see PR #340.

> On a more general note, is there a particular reason that `[]` is used as special value to trigger the handling of "enumerated labels" instead of `null`?

I guess it was just leading to a simpler schema and [] had no meaning so...

> It feels like these two sentences can be condensed more efficiently.

Okay, I don't have a strong preference for either of the variants. 

> Also, I find the adjective "unsorted" confusing in this explanation, as the label order is essential for the operation.

I added another sentence explaining the "unsorted", i.e. the order is important between source and target (=> captured by your "corresponding"), but the order of the given labels doesn't need to match the order of the labels in the data cube.
