### ISSUE TITLE
Keep/add or deprecate GeoJSON input type?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#343]
With the introduction of vector data cubes there's the question whether the geojson type should still be used and added in vector processes or not.

Options:
1. Keep GeoJSON Schema in existing processes and add to new processes
2. Deprecate GeoJSON schema in existing processes and don't add GeoJSON schema to new processes. Then we'd want to add a new process to load/convert GeoJSON to a vector cube (see #346 ).

I'm not sure what I prefer. In processes, it could be easier to not have it, in (my) tooling/implementations it is probably a bit easier to have it.

Origin: https://github.com/Open-EO/openeo-processes/pull/315/files#r814788548

Closely related to #323

**Comment by m-mohr** [comment]
The more I'm thinking about this the more I'm leaning towards option 2...

**Comment by soxofaan** [comment]
yes, imagine that everywhere where you can now pass a raster cube, you would also be able to pass a multi-dimensional array construct like `[[[1,2,3], [4,5,6], ...`

**Comment by m-mohr** [comment]
Also, there are not a lot of processes affected by the deprecation. I'm only sure we'd deprecate in aggregate_spatial. I'm not sure about filter_spatial and mask_polygon.

**Comment by clausmichele** [comment]
By the way, for UC8 I think that we'll use the old geoJSON spec, which allows different projections specifying the "crs" value.
Therefore, this geoJSON will be directly passed to fit_regr_random_forest in the process graph.

This can be replaced by a load_vector_cube process once it will be ready.

**Comment by m-mohr** [comment]
I'll try to draft a process soon as this would indeed make other process descriptions easier.

**Comment by m-mohr** [comment]
Draft proposal available in PR #412.
