### ISSUE TITLE
array_contains: Incorrect example

### ISSUE THREAD

**Issue by Ardweaden** [Open-EO/openeo-processes#348]
**Process ID:** array_contains

**Describe the issue:**
Description states:
> All definitions for the process [eq](https://docs.openeo.cloud/processes/#eq) regarding the comparison of values apply here as well. A null return value from [eq](https://docs.openeo.cloud/processes/#eq) is handled exactly as false (no match).

where
> If any operand is null, the return value is null. Therefore, eq(null, null) returns null instead of true.

`Example #4` says:

> array_contains(data = [1,2,null], value = null) => true

**Proposed solution:**
Correct example would be `array_contains(data = [1,2,null], value = null) => false`

**Comment by m-mohr** [comment]
You are right, this should be fixed. (Nevertheless, this is really unintuitive.)

**Comment by m-mohr** [comment]
Fixed in e4df864846e833dda4669e190669a2db5b365c62
