### ISSUE TITLE
default for train/validation split in fit_class_random_forest

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#350]
https://github.com/Open-EO/openeo-processes/blob/e4df864846e833dda4669e190669a2db5b365c62/proposals/fit_class_random_forest.json#L27-L33

Maybe this has been discussed before, but can't we pick a sensible default for the training-validation split? e.g. 80% / 20%?

**Comment by m-mohr** [comment]
Sure, what is a sensible default?

**Comment by soxofaan** [comment]
Python [sklearn's train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) seems to default to a split of 75% train - 25% test/validation

But most articles I checked from a quick google suggest 80% train - 20% validation as good default.

**Comment by m-mohr** [comment]
dev telco: Remove this parameter completely
