### ISSUE TITLE
apply_dimension: Clarification of behaviour

### ISSUE THREAD

**Issue by Ardweaden** [Open-EO/openeo-processes#357]
**Process ID:** apply_dimension

**Describe the issue:**
Documentation states:

> The target dimension is the source dimension if not specified otherwise in the target_dimension parameter. The pixel values in the target dimension get replaced by the computed pixel values. The name, type and reference system are preserved.

>There are three cases how the dimensions can change:
>...
>2. The source dimension is not the target dimension and the latter exists:
The number of dimensions decreases by one as the source dimension is dropped.
The target dimension properties name and type remain unchanged. All other dimension properties change as defined in the list below.

We don't understand how this is supposed to work.

For example what would the result be in the following case:
```python
data = DataCube([[1,2],[3,4]], dimensions=("temporal", "band"))
apply_dimension(data=data, process, dimension="band", target_dimension="temporal") -> ?
```

**Comment by soxofaan** [comment]
good point, you can not just "drop" a dimension without describing how the values along that dimension are "reduced"

**Comment by m-mohr** [comment]
Yes, I think this was meant to say something like that:

> The source dimension is not the target dimension. The target dimension exists with a single label only:
The number of dimensions decreases by one as the source dimension is "dropped" and the target dimension is filled with the processed data that originates from the source dimension.

So this is more a: move the data from source to target after processing it, but target must basically be empty / have a single label only.

**Comment by soxofaan** [comment]
Just wondering: what is the use case that makes this "target_dimension" feature in `apply_dimension` necessary? It can be implemented with `drop_dimension` + `rename_dimension` anyway, right?

**Comment by m-mohr** [comment]
I think the initial use-case was to "convert" data, e.g. you go in with a e.g. temporal dimension and your result is non-termporal data. So you'd need to specify another dimension that could hold the data. I think that is still valid.

As far as I know, apply_dimension was spec'ed before drop and rename were defined so the alternative was not present.
