### ISSUE TITLE
is_nan(3.14) = True?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#360]
https://github.com/Open-EO/openeo-processes/blob/d0ce91fcd347360b907ea2d9589d7564a2c1e1e3/is_nan.json#L4

>    Returns `true` for numeric values (integers and floating-point numbers), except for the special value `NaN` as defined by ...

Must be "Returns `false`" I guess?

> All non-numeric data types MUST also return `true`, including arrays that contain `NaN` values.",

The "including arrays with NaN values" is a redundant statement I think. I think the intention was to add "including arrays that contain normal numerical values".

**Comment by m-mohr** [comment]
See PR #363 for a fix/clarification.
