### ISSUE TITLE
process for metadata changes (e.g. no-data value)

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#364]
This came up in an internal use case: 
user wants to change the no-data value of a datacube (e.g. in an exported GeoTiff so that it can be processed with another tool that assumes certain no-data setting).

Should we create a new process for meta-data manipulation?
Or could this be standardized as some kind of output format option?

**Comment by m-mohr** [comment]
For no-data values, this is likely an output format option, because some may support no-data directly and some require setting a specific value. The processes themselves don't really need the differentiation.
