### ISSUE TITLE
drop `target_dimension` in `aggregate_spatial`?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#366]
While working on a vector cube implementation with `aggregate_spatial` I started wondering about the point of the `target_dimension` parameter: what is that for actually and how should that work?

aggregate_spatial starts from a raster data cube (e.g. x-y-t-bands) and aggregates spatially to a vector cube e.g. with dimensions geometry-t-bands. 
So you start from a raster data cube and generate a completely new vector cube. You are not updating or appending to the original raster data cube, which this `target_dimension` seems to suggest in a way.

I don't think we need `target_dimension`. Unless that is about naming the "geometry" dimension (or whatever we are going to standardize on, I can't find the related issue at the moment)?

**Comment by m-mohr** [comment]
The new definition in #382 should clarify what target_dimension is used for in the future. Happy to receive feedback about it.

**Comment by soxofaan** [comment]
ok thanks. With #382 being the way forwards, I think we can close this one
