### ISSUE TITLE
load_ml_model: user uploaded files

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#367]
https://github.com/Open-EO/openeo-processes/blob/589bfd29667f8bfa4dd40992ca4f5edcb2d753d2/proposals/load_ml_model.json#L30

`User-uploaded Files` is a bit confusing in plural form, while the argument `id` just expects a single path (without any globbing support I guess)

**Comment by m-mohr** [comment]
Fixed.
