### ISSUE TITLE
Filter by point process

### ISSUE THREAD

**Issue by GreatEmerald** [Open-EO/openeo-processes#37]
We discussed in the telco that it might make sense to have a process to filter by point, like we have a filter by polygon.

The use case we're thinking of is to quickly get all relevant data about a particular point in the world. What that entails is not entirely clear though and probably depends on what filtering by polygon does, so as to maintain consistency. Right now filtering by polygon effectively is defined as a `crop`/`clip` function, and the same could be done for filtering by point.

There are three more alternatives: to have it work as an `intersect`, so that dimensions of features or rasters are not changed but anything not touching (i.e. not relevant to) the point is discarded (that's how it works in GEE); to have it work as an `extract`, so that the space dimensions are collapsed (you get e.g. a time series); or to not have either of the filtering options altogether and just provide `clip`/`crop`, `intersect`, and `extract` as their own processes.

**Comment by jwagemann** [comment]
For climatological applications, point retrieval is an important process. It is currently still too cumbersome to retrieve point information over long time-series data.

**Comment by jdries** [comment]
What is a point exactly in a raster data cube context? A mathematical point, specified by geographic coordinates, can still be positoned on the point where two or more pixels (data cube cells) touch. In some use cases, points are also converted into square or circular bounding boxes, with a specific size. This tends to make the desired result more reproducable.

**Comment by edzer** [comment]
Good points, we need to define all this somewhere. I think the usual (= GDAL) semantics about this is that one corner point and two sides belong to the pixel, the other sides / corners not. If y index increases downward (y cellsize negative) the top left corner and left and top sides belong to the pixel, so a point on this corner / these points intersect with the pixel; this way a grid is different from a set of polygons polygonizing the pixels.

As I mentioned in the telco, querying a raster data cube on a set of points is not an openEO filter operations, as all filter operations return a raster cube, and this returns a vector data cube (points x time). The closest in our typology is [aggregate_polygon](https://open-eo.github.io/openeo-api/v/0.4.0/processreference/#aggregate_polygon), which takes a raster data cube and a vector data cube, and returns a vector data cube. The aggregation function (reducer) would be the identity function. It's somewhat contrived, and we may want to pick a different name for this; `resample`, or even `sample` comes to mind.

**Comment by GreatEmerald** [comment]
Yes, that's what in the R `raster` package they call `extract`. `resample` would be very confusing because it implies resampling from one raster into another with a resampling method function. `sample` does make sense in this context, but the name is quite ambiguous (in R it means to take a sample of values from an array, for instance).

I also agree that it makes sense for a process like that to not change the type of the cube, so in essence to just do a `crop`. A `crop` of a single point is perhaps not the most obviously useful thing to have, but it may nevertheless be useful for getting the information at the location in a raster format rather than a vector format. But then maybe we should call it `crop` rather than `filter`.

Andrei also suggested that it would make sense to have all point operations be aliases to the equivalent polygon operations, just having the polygon consist of a triangle whose points are all the same. In that case, if it touches two pixels, then what you do is the same as what you do if a polygon touches (or e.g. covers) several pixels. (What to do in that case is a question of its own.)

**Comment by m-mohr** [comment]
> As I mentioned in the telco, querying a raster data cube on a set of points is not an openEO filter operations, as all filter operations return a raster cube, and this returns a vector data cube (points x time x whatever_else).

Yes, if you work on multiple points it would be a vector cube. I thought the process would be limited to a single point and just give a list of values for which the pixel area intersects with the point. If the point intersects with multiple pixels you'd specify a reducer to get only a single point. If you don't have additional dimensions than space and time, you'd basically get a time series, which could be a (simple) raster cube again. I think this would be very similar to what @GreatEmerald mentions. But maybe this is too naively thought out by me.

**Comment by edzer** [comment]
going from a raster data cube to a vector data cube changes the type of cube. How about `spatial_join`?

**Comment by m-mohr** [comment]
3rd year planning: Wageningen stressed again that this process is required for a use case. We need to come up with a definition. Maybe @GreatEmerald or Milutin (GitHub handle?) can come up with a proposal?

**Comment by GreatEmerald** [comment]
From the use case (=user) point of view, we need a way to get the values of the time series at given mathematical points. Whether that is called a filter, or some other name (spatial_join), doesn't matter much. If the point falls on the boundary between cells, return the mean. (It can also be an option to return a weighted value from four neighbouring pixels always, because that may be more representative than the nearest neighbour if we approach the cell border.)

Given multiple dimensions (e.g. bands), return multiple columns, so we have e.g. time and bands as rows and columns.

While cropping to the cells is theoretically nice in that it returns a raster cube still, I can't think of any relevant application.

**Comment by jdries** [comment]
To me this sounds a lot like an aggregate polygon: you pass in a list of points and as a result you get a vector data cube where the vector geometries are the original points.

The thing is that you could already do that by converting your points into small bounding boxes, could even be a client-side utility function. Would that help?

Or we could define the behavior of aggregate_polygon in case you pass in a set of points? Currently it is undefined, but we could clarify in the process definition that they are basically converted into bboxes of one pixel? That would be easy for the backend because we usually know the datacube resolution. Or would that be too much of a hack? (It would at least allow us to explore the use case without expanding the api.)

**Comment by GreatEmerald** [comment]
If we define a point as a bounding box of one pixel, we need to keep in mind that the pixel can have a different size depending on the resolution of the collection in question.

In the end, from the users' perspective it doesn't really matter how it's implemented, as long as the user can define a set of points (or upload a file containing those) and get the time series under that point back, with all bands and from multiple collections. The naming on the client side does matter for discoverability; `aggregate_polygon` would be a very counter-intuitive name for an extraction function over points. (That said, GEE uses the name `reduceRegions` for that, which is just as undiscoverable...)

For offloading some of the functionality to the clients, it's certainly possible but I'm a bit wary that it will make the creation of any new potential clients cumbersome (we have a lot of decisions of "the client can handle it", but as far as I know we don't have a list of those anywhere), as well as duplicate the efforts on each of the clients. The R client specifically autogenerates the list of processes from what the backend returns, so making a client-side process to emulate polygons from points would be tricky without some hardcoding...

**Comment by m-mohr** [comment]
I think it's a bit hacky to solve it with aggregate_polygon and agree with @GreatEmerald. Depending on how the process should be defined (i.e. what it actually does), I would prefer to have a better name such as filter_point or so. @GreatEmerald, could you actually come up with a proposal as discussed in the 3rd year planning? That means defining a full process including inputs and outputs etc? I think that would help a lot in discussing this issue.

**Comment by GreatEmerald** [comment]
OK, I can bring it up in our next internal meeting.

**Comment by GreatEmerald** [comment]
We discussed it today and came up with the idea that we indeed need two processes here.

One process, called `crop`, that would take a datacube and vector geometry (coordinates/point/line/polygon) as input, and return a datacube as an output, cropped to that geometry. (A point on the border between two cells would return both, or optionally the process can accept a reducer to apply when that happens, so we can do a mean; including a mean over polygons, in other words zones.) If it is vectorised (so the input is multiple points/polygons), then it would return a list of datacubes, one per geometry.

Then, we need another process that would produce a table from something like that; think zonal_statistics output from the previous API versions. It's something that would either join the values into a vector datacube (so the `spatial_join` idea) or just return values in some format that is convenient (the time series format that we were discussing elsewhere or whatever can be ingested by a UDF in a convenient way). It could only be allowed to take as an input a raster that is one pixel in size per layer, or perhaps also allow specifying a reducer, it could be seen a vector equivalent to `crop`. So in the end the output could be downloaded as some sort of table or vector with an attribute table.

One consideration here is also to make sure we have something that would not take too much processing time for UDFs, i.e. a UDF that takes a time series as an input should be efficient to apply to every pixel of a pretty large raster. Though we may already have other processes that allow doing so?

**Comment by m-mohr** [comment]
@GreatEmerald Could we discuss this on the next telco on 12/12/19 @ 9:30 - 12:00 with you?

**Comment by GreatEmerald** [comment]
Yes, OK.

**Comment by lforesta** [comment]
Telco conclusion:
create new process "filter_spatial" which includes functinalities of filter_bbox and filter_polygon, plus also point feature
deprecate filter_bbox and filter_polygon
@GreatEmerald to create PR

**Comment by m-mohr** [comment]
Should be aligned with the changes in #107. Why is filter_bbox to be deprecated?

**Comment by lforesta** [comment]
the idea was that filter_spatial will cover both bbox and polygon cases.
@GreatEmerald , how do we cover the point feature without forcing the user to know where a pixel is? We could get the closest pixel to that point? (if one wants interpolation at that point, the new aggregate_spatial should be used I think).
Should this process support line objects too? This may be useful for getting raster data along a flight track (I'm thinking e.g. comparing airborne and satellite data)

**Comment by GreatEmerald** [comment]
Yes, and yes. If you filter by point/line, any pixel that touches it gets selected. That's how it works in GEE too.

**Comment by m-mohr** [comment]
I think I wouldn't deprecate filter_bbox as it's a welcome simplification to specifying a polygon. I always struggle to create a polygon from a bbox as I can't remember to to create the coordinates array correctly.

I'm fine with touching, but it should be consistent with polygons, too. Otherwise, it sounds better to have separate processes for it (see also #107).

**Comment by m-mohr** [comment]
@GreatEmerald won't make it for the next release due to time constraints. Can any one take over? Otherwise I'd probably make a PR based on the outcomes in PR #107

**Comment by m-mohr** [comment]
There's now a proposal in PR #131
