### ISSUE TITLE
count:  `condition=false`?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#375]
https://github.com/Open-EO/openeo-processes/blob/d0ce91fcd347360b907ea2d9589d7564a2c1e1e3/count.json#L56-L64

`count` supports, apart from a full process graph, two special values for `condition`:
- `null` as shortcut for `is_valid`
- `true` as shortcut for count all

The schema of `condition` in the docs at e.g. https://processes.openeo.org/#count say
```
process-graph:object|boolean|null
```

Which also include the boolean value `false`, but its is undefined in the docs.

possible definitions:
-  always count 0  (which is conceptually the cleanest I think, given the behavior of `true`)
- count invalid  values   (feels very adhoc, but would be a useful shortcut I think)

**Comment by soxofaan** [comment]
> false is not allowed as input value according to the spec. The part that is defining that is "const: true" in the boolean schema. 

Indeed, I see that from the spec in JSON, but the docs are misleading, because they say "boolean" in general
![Screenshot from 2022-06-30 17-32-25](https://user-images.githubusercontent.com/44946/176717551-6209b1ef-8edd-4842-8fa7-6cca278b57d6.png)

**Comment by m-mohr** [comment]
Yes, but that is normal behavior in programming language signatures?! It just lists the types/classes without value constraints, otherwise you'd also need to list all other constraints in the signature, e.g. min and max values for numbers or allowed string values for strings.

**Comment by soxofaan** [comment]
I understand, it's just very weird to see "boolean" as type, but `false` is illegal.

Also note that the representation of these union schema's (I don't know the correct terminology) in the docs is pretty obscure.
Because I've been already exposed to a bit of JSON schema, I kind of get it, but I wonder what the less-initiated user makes from this visual structure:

![Screenshot from 2022-06-30 17-52-29](https://user-images.githubusercontent.com/44946/176722886-448c54b0-5b0f-4abf-b048-4e2746667f45.png)


Anyway, I think we should add an explicit note in the docs that `false` is (currently) not supported

**Comment by m-mohr** [comment]
> Also note that the representation of these union schema's (I don't know the correct terminology) in the docs is pretty obscure.

Yes, I agree. Please open an issue in openeo-vue-components with suggestions and we can try to improve it.

**Comment by m-mohr** [comment]
ToDo: Explicitly mention that `false` is not allowed.

**Comment by soxofaan** [comment]
>  Please open an issue in openeo-vue-components with suggestions and we can try to improve it.

Is that something we have much control over? I thought this just part of the doc building tool

**Comment by m-mohr** [comment]
That is something we have control over, the doc building tool is based on the openEO vue components and developed by me :-)

**Comment by m-mohr** [comment]
Yes, we do. For the API. But our processes have nothing to do with OpenAPI. :-)
The processes are something custom in mainly JSON Schema. The DocGen for the Processes ist just a slightly extended version of the Process(es) Vue Component that we also use in the Web Editor etc.
