### ISSUE TITLE
load_stac_collection

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#377]
**Proposed Process ID:** load_stac_collection

## Context
An openEO backend now only supports predefined collections, but properly configured STAC collections can also be loaded. This avoids the need for static config, and simplifies use cases like running an openEO backend out of the box.

There's a few bigger questions here:
- How will we deal with authentication headers? Can we do something generic?
- Would it be useful to be able to override collection metadata? This would provide a workaround for catalogs that don't provide sufficient metadata, like the openeo:gsd values to determine resolution per band.

## Summary
Loads a collection from a STAC catalog.

## Description
Loads a collection from a STAC catalog by its id and returns it as a processable data cube. The data that is added to the data cube can be restricted with the parameters spatial_extent, temporal_extent, bands and properties.

## Parameters

(copy some from load_collection/load_result
### `collection_id` 

**Optional:** no

#### Description
The STAC collection id to use when querying the catalog

#### Data Type
string

### `access_token` 

**Optional:** yes

#### Description
Some catalogs may require an authorization header to be sent along with requests, both for catalog access and for data access.

#### Data Type
string

### Description
A data cube for further processing. The dimensions and dimension properties (name, type, labels, reference system and resolution) correspond to the collection's metadata, but the dimension labels are restricted as specified in the parameters.

### Data Type
raster-cube

## Categories (optional)
* Cubes
* Import

**Comment by jdries** [comment]
@LukeWeidenwalker  this would be the basis for the 'User collections' concept right?

**Comment by m-mohr** [comment]
API keys can be provided via the URL as query parameters.

Later, we can discuss an option where you can pass an object with headers to load_stac for authentication.
