### ISSUE TITLE
Cropping cumbersome

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#378]
Feedback from METER group is that cropping to a GeoJSON is cumbersome as you need to run two processes:
- [filter_spatial](https://processes.openeo.org/#filter_spatial) and
- [mask_polygon](https://processes.openeo.org/#mask_polygon)

Might be a client improvement, but maybe we can also enforce implicit filtering in mask_polygon or implicit masking in filter_spatial? Not sure yet...

**Comment by soxofaan** [comment]
FYI: In VITO back-end we allow just specifying `mask_polygon` and automatically  inferring the spatial extent for `load_collection` from that, e.g. see https://github.com/Open-EO/openeo-python-driver/commit/9548306e5392d4a2787f9fc4ffbf4dd0bf27ced1

**Comment by m-mohr** [comment]
I think there is no feasible solution right now:
- mask_polygon: Here you can't crop as it would conflict with this `inside` parameter
- filter_spatial: Here it is just filtering on the bbox and masking can't happen

I guess we can make a `crop_polygon` UDP available that combines these both processes.

**Comment by m-mohr** [comment]
See https://github.com/Open-EO/openeo-community-examples/pull/5
