### ISSUE TITLE
HTTP status code for per-process errors

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#380]
https://github.com/Open-EO/openeo-processes/blob/d0ce91fcd347360b907ea2d9589d7564a2c1e1e3/add_dimension.json#L59-L63

Should we specify the HTTP status code corresponding to these per-process errors (like in https://github.com/Open-EO/openeo-api/blob/master/errors.json)?

**Comment by m-mohr** [comment]
You can do that (`http` property in the API spec for processes), but it defaults to 400 and I think (mostly) all exceptions should result in a 400, right?

**Comment by soxofaan** [comment]
ah ok, so this: https://github.com/Open-EO/openeo-api/blob/16b1122c7090cc4fedcabace48686a4f73c1c876/openapi.yaml#L5112-L5118

I didn't look that far. It's probably 400 in most cases indeed
