### ISSUE TITLE
inspect: naming of process and parameters is confusing/unintuitive

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-processes#383]
I'm not sure why this process isn't simply called `log` because it doesn't inspect, it _logs_.

Its parameter `code` is also far from obvious. It acts as a label for a bunch of log entries that belong together so why not just name it `label` instead?

**Comment by m-mohr** [comment]
Here's some context: https://github.com/Open-EO/openeo-processes/pull/310

- There's already process called log (logarithm): https://processes.openeo.org/#log
- code (and the other parameters) is aligned with how the fields are named in the API responses.
