### ISSUE TITLE
load_ml_model id: overlap between batch job id and file path?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#384]
https://github.com/Open-EO/openeo-processes/blob/be148835a725966fbf1fff65215dbf2bca82a4a7/proposals/load_ml_model.json#L23-L33

Batch job id has regex `"^[\\w\\-\\.~]+$"` and user-uploaded file has regex `"^[^\r\n\\:'\"]+$"`.
Both regexes will match on simple things like `foo-bar`, so a back-end will not be able to determine if given `id` is intended as job id or a user uploaded file? Or is a back-end supposed to try the available options and pick the first match?

**Comment by m-mohr** [comment]
True, that's not ideal.

**Comment by m-mohr** [comment]
The only thing I could think of right now is to require e.g. a "./" at the beginning of file paths.
Alternatively, back-ends would need to be given a priority list, I guess... Any opinions or ideas?

**Comment by soxofaan** [comment]
another option is requiring some kind of  scheme prefix when there is risk of confusion, e.g. `workspace://mymodel.foo`,  which extends easily to other storage solutions or "namespaces" (`s3://...`, `https://...`, ... or even `job:...` and `job://otherbackend/...`)

**Comment by m-mohr** [comment]
Yeah, I thought about that too, but I found that even more confusing/unexpected. 🤔

**Comment by m-mohr** [comment]
Maybe define two processes?

**Comment by m-mohr** [comment]
Solved by #413, I think.
