### ISSUE TITLE
aggregate_temporal - Add time-series aggregates, e.g. seasonal

### ISSUE THREAD

**Issue by jwagemann** [Open-EO/openeo-processes#39]
In climatology, time-series aggregates in multiple ways are of high interest.

1. Example: create climatology from a time-series: let’s say we have time-series data of 10 years (2000-2010). We would like to retrieve the mean of each month of this time series → resulting into a data set of 12 months

2. Example: Seasonal aggregates: common seasons are “DJF”, “MAM”, “JJA”, “SON”. For tropical countries, wet and dry season is often differentiated.  A user might be interested in the mean of the specific season, for one year or even in the general mean of a longer time series.

**Comment by m-mohr** [comment]
_Thanks for porting this over from our discussion. Here's also my ported response:_

We need to check whether the filters allow to achieve the examples. For examples, we don't have date/time operations on the back-end yet and expect that the clients generate intervals for aggregate_temporal (or use multiple filter_temporal). If aggregate_temporal works well with client libraries, we may just extend filter_temporal to also passing more then one interval. That's probably a way that would work to solve (1).

For (2) we nay need specific processes depending on how these seasons are defined. I assume the normal date/time libraries are not covering this. Once we have the ERA5 data for GEE we could probably just sit together and define these processes.

**Comment by pramitghosh** [comment]
Yes, these rolling aggregations are common in quite a few domains including oceanography.

However, I was wondering if it is a good idea to define all sorts of possible processes in the backend since it would be a never-ending list. Anyway, isn't the UDF service a better option since it is specifically designed for custom requirements of the user such as the operations @jwagemann mentioned? For example, both these operations could be done using the UDF service (definitely in my [R UDFs](https://github.com/Open-EO/openeo-r-udf)) in its current state (leaving aside the scalability bit).

**Comment by m-mohr** [comment]
> However, I was wondering if it is a good idea to define all sorts of possible processes in the backend

Of course not and the back-ends can still choose which they'd like to add. But if a process is "common in quite a few domains" it feels reasonable if it can't be achieved easily with other processes. As I don't know the meaning behind “DJF”, “MAM”, “JJA”, “SON” yet, I can't really judge what's the best way to go, but I already wrote in my first comment that it may also be possible with aggregate_temporal and we need to check what's the best way out.

I personally don't see the UDF service as a better option here as it's quite a common task and shouldn't require UDFs. UDFs for me are more a tool to process highly specialized things, e.g. using bfast or so.

**Comment by jdries** [comment]
A colleague of mine just requested support for this specific use case. I believe allowing multiple time intervals as temporal extent would already get us a long way.
Translations from domain specific indicators to the actual intervals is something that can be done on the client side in a lot of cases.

**Comment by m-mohr** [comment]
> I believe allowing multiple time intervals as temporal extent would already get us a long way.

@jdries  aggregate_temporal already supports multiple time intervals. What is missing?

> Translations from domain specific indicators to the actual intervals is something that can be done on the client side in a lot of cases.

Yes, but would that be something that (1) needs to be implemented in our client libraries or (2) is already available as external library? How do we ensure that you can do things in all clients? It should never happen that you can run something on R but not on Python and vice-versa.

**Comment by jdries** [comment]
I also thought of using aggregate_temporal, but it would mean that we would still load too much data first, only to discard part of it in aggregate_temporal. So having the exact intervals available in filter_temporal would be an optimization.

The conversion of the domain specific intervals is something that would not be part of the core client libraries. In most cases people just write the translation logic themselves.

**Comment by m-mohr** [comment]
Oh, you are speaking about filter_temporal. That wasn't clear and would probably need its own issue. Anyway, load time optimization based on filter_temporal is back-end specific for VITO, I think. If you want to have multiple temporal intervals in filter_temporal, we'd also have it in load_collection. But then: Why not also allow multiple spatial extents? And would that make load_collection too complicated?

**Comment by m-mohr** [comment]
See #145 for a related PR.

**Comment by m-mohr** [comment]
I think this is solved with aggregate_temporal_period.
