### ISSUE TITLE
run_udf on vector cubes: define allowed Python representations

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#398]
We need to standardize on a  Python representation for vector cubes, specifically for use with UDF's.

For rasters, we use Xarray, and to some extent this would work for vector cubes except that geometries are probably not supported as dimension labelds.
Geopandas would be another candidate.

We currently use a simple Python dict but this is then basically an entirely custom data structure that the user needs to know.

**Comment by m-mohr** [comment]
I'm not sure that this is something that the processes need to define. Isn't this specific to the UDF runtime? 
In the R UDFs you'd get a stars object and have native vector cube support, in Python it is not natively supported yet, but it seemed there was something going on recently: https://discourse.pangeo.io/t/vector-data-cubes/2904

**Comment by jdries** [comment]
Interesting! Problem is, it somehow needs to be standardized, and the 'Python udf runtime' repo is basically unmaintained. The UDF related classes that are considered public api are now in the openEO python client. 
I could move the issue in there, but wanted to specifically discuss standardization here...

Of course, given that XArray is already supported by the current API, it's perhaps the easiest way to go, and will allow easy migration into something like xvec
