### ISSUE TITLE
is_nan process

### ISSUE THREAD

**Issue by claxn** [Open-EO/openeo-processes#40]
I think the boolean values were interchanged in the examples and the major description of the `is_nan` process (see [`is_nan`](https://open-eo.github.io/openeo-api/v/0.4.0/processreference/#is_nan)). In my opinion it should be something like:
...All non-numeric data types MUST also return `true`.
and
`is_nan(x = 1) => false`
`is_nan(x = 'Test') => true`

**Comment by m-mohr** [comment]
Ouch, thanks for spotting this. Fixed.
