### ISSUE TITLE
Generalize `load_geojson`

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#415]
I considered raising this in #412 or #322 but maybe it's better to keep this a separate thread:

`load_geojson` (as introduced in #412)  is closely tied to GeoJSON (by name and supported format), which has the following problems:
- it's out of line with other `load_` processes which support multiple formats, and use `/file_formats` to express that
- it supports loading data from inlined data in the process graph and from remote URLs, but remote vector data might also come in other formats (geopackage, shapefiles, next generation GeoJSON, ...), so why not support that too? (Inline data can also come in other formats actually: WKT string, CovJSON, ...)

Couple of lines of thought:
- generalize `load_geojson`, e.g. to `load_vector`, to also support other vector formats
- generalize  even further to e.g. `load_cube` to also support raster data, not only something like a remote GeoTIFF, but also some kind of inline raster data cube construct (also see #204)
- generalize, but split the inline and external URL case (to avoid some schema specification issues) :
    -  `load_inline`  which could support inline GeoJSON, WKT, other JSON based vector format (e.g. CovJson),  some kind of inline raster data format (again see #204), ...
    - `load_external` to load from a URL

**Comment by jdries** [comment]
A reminder perhaps, but another issue with a specific process like load_geojson is in UDP's where the data to load is a parameter, and the UDP designer would like a user friendly approach to allow loading vector data from different sources without having to make a complex construction inside the UDP.
Could potentially be solved by simply having a vector cube as a udp parameter but then we do have more reliance on the ability to construct vector cubes loading logic client side.

**Comment by m-mohr** [comment]
@jdries Yes, a vector cube should probably be passed in. geojson as subtype has be deprecated (except for load_geojson, if accepted).
