### ISSUE TITLE
run_udf docs should reference udf spec

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#42]
The explanation in the run_udf process should more clearly reference the UDF spec that we use (https://github.com/Open-EO/openeo-udf).
We also do not yet describe how the what input will be provided to the UDF and what output is expected. This also depends on the context in which the UDF is used.

**Comment by jdries** [comment]
Seems related to: https://github.com/Open-EO/openeo-udf/issues/4

**Comment by m-mohr** [comment]
Well, I think yes and no. The UDF spec at the moment seems more aimed towards implementors and the processes are more aimed towards users (though I always need to find the sweet spot between users and implementors when specifying the processes). I feel that linking to the UDF spec as of now, it would confuse users quite a lot. I think we need two separate UDF documentations, one for users (e.g. an extended version of what currently is available as "Coding UDFs", but also for R) and one for implementors and then we should link to the UDF documentation for the users. (Also I feel we should separate the UDF documentation [maybe integrate it in the openEO API] and the Python reference implementation, but that's a separate issue.)

Indeed, the UDF processes are quite unclear. Reason is probably that I don't work with the UDFs and have not written the specification. So at the moment, I need support there in form of concrete proposals or PRs.

**Comment by m-mohr** [comment]
Moving to 1.0-final, maybe at some point we can link to UDF documentation on openeo.org.

**Comment by m-mohr** [comment]
Unfortunately, it seems there's no user-oriented UDF documentation coming up soon (i.e. until the end of the month), so moving to future.
