### ISSUE TITLE
Old and new process graph examples (reduce, band math, labeled data)

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#43]
In the new 0.4.0 process graph example, 'dimension_data' is used in some places, but this is not yet clearly documented (afaik).
I'm also a bit confused about the name, could it be that this name was chosen in the context of the initial confusion around data cubes?

**Comment by m-mohr** [comment]
Also, I changed the examples in the documentation to a full and up-to-date EVI example, see https://open-eo.github.io/openeo-api/v/0.4.0/processgraphs/#example and also the openAPI spec.

**Comment by m-mohr** [comment]
Moved to a later release, I think we are fine with this for a first version. Otherwise we would potentially need to change quite a lot, which we don't have the time for. So let's make experiences with this and evolve it in the next versions.

**Comment by jdries** [comment]
I now support the EVI example in the python client:
https://github.com/Open-EO/openeo-python-client/blob/274aac31a04b329eedaceb94b104d162579b2df3/tests/test_bandmath.py#L45
It generates this result:
https://github.com/Open-EO/openeo-python-client/blob/274aac31a04b329eedaceb94b104d162579b2df3/tests/evi_graph.json

On the Python side, I was able to make it look very simple. Of course, this relies on the assumption that the backend supports this style of process graph.
The resulting graph is fairly long compared to the input, this also made it hard to debug while developing it. Also on the backend side, I would be fairly lost if I received a 150 line process graph. Some minor optimizations could help in this respect.
Once this functionality in the python client is documented, we may also want to reference it from the process description docs.

**Comment by m-mohr** [comment]
Oh, that looks awesome in the Python client, but I'm concerned that it bases on too many assumptions and doesn't work generally. I'm interested to learn how that works.

The process graphs are not meant to be consumed by users so I don't see a general problem here. Though, we have the process graph to model converter from the web editor, which we could release as a single app so that you could simply convert a process graph to a human-readable model (and vice-versa). I think this could help with debugging.

Which optimizations?

**Comment by m-mohr** [comment]
@jdries I just had a look at the process graph, it doesn't have a filter_bands to order the bands, so array_element won't work as expected. You would probably work with the wrong bands.

**Comment by m-mohr** [comment]
@jdries I just had a look at the process graph, it doesn't have a filter_bands to order the bands, so array_element won't work as expected. You would probably work with the wrong bands. 

It would work without filer_bands if we specify that the bands are by default ordered as specified in the STAC metadata. Then you could simply pass the corresponding array index to array_element. Nevertheless, I'm currently not sure where to define such global definitions.

**Comment by jdries** [comment]
Thanks!
It uses the band metadata from the backend to determine band order. It does assume that the order of the bands in the metadata corresponds to the actual order. Another option would be to have a callback function that retrieves a band by name, instead of array index. It would help a lot for readability if this could be included inline.
In general, it assumes that a reduce on 'spectral_bands' is supported by the backend, and that basic math functions are available. Do you see any other assumptions?
The result:false is indeed a bit of a side effect of my current implementation. 

As you know, I also care a lot about developer-friendliness, as an open source project always relies on a healthy and sustainable community of developers. The whole 'my unreadable format is not meant for humans' argument is an OGC classic, and would mean we don't need something like STAC, because we already have Inspire Metadata.
I believe allowing inline declarations could help to some extent, only problem is that the client would also have to be smart enough to construct a better process graph. The other option is simply a dedicated band math function, that parses expressions on the server side.

**Comment by m-mohr** [comment]
> It uses the band metadata from the backend to determine band order. It does assume that the order of the bands in the metadata corresponds to the actual order.

I'd assume the same, but we have not specified it anywhere and I'm not quite sure where to specify it. Maybe load_collection (+ load_results and ...?) would be the appropriate place?

> Another option would be to have a callback function that retrieves a band by name, instead of array index. It would help a lot for readability if this could be included inline.

It's not only the bands, but generally labeled data such as temporal or vertical dimensions, e.g. grouped levels or whatever "nominal" data. But in this version we don't have it yet, so I guess we should aim for that after the first version in May.

> In general, it assumes that a reduce on 'spectral_bands' is supported by the backend, and that basic math functions are available. Do you see any other assumptions?

Fair enough to expect the processes to be available. The band order is an assumption and maybe more, but I still need to find the actual implementation.

> As you know, I also care a lot about developer-friendliness

I'd say: me, too. But maybe I have other priorities here ;-)

> The whole 'my unreadable format is not meant for humans' argument is an OGC classic, and would mean we don't need something like STAC, because we already have Inspire Metadata. [...] The other option is simply a dedicated band math function, that parses expressions on the server side.

Primarily, STAC is not meant to be human-readable either, so I don't buy that argument. STAC is much simpler than INSPIRE in many regards and who wants to mix XML and JSON? The problem with our process graphs is that we are working with JSON here and that always get's quite verbose. If we'd really want to have it human-readable we should remove that constraint and make something like the WCPS language.

Having a band math process would make this use case simpler, but not all the of the others. It would mean we need convenience processes for everything. So why not specify an EVI function similar to the NDVI function? Would make it simpler, too. (I'm not actually mandating here to do so.)

> I believe allowing inline declarations could help to some extent, only problem is that the client would also have to be smart enough to construct a better process graph.

Could you give an example? Not quite sure yet what inline declarations are for you.

**Comment by jdries** [comment]
We can indeed clarify in load_collection that the band order corresponds to the metadata, seems like a good place.
As for the code, you can find it here:

**Comment by m-mohr** [comment]
Thanks. Some Python magic going on with operator overloading and so on, it seems?!

> We can indeed clarify in load_collection that the band order corresponds to the metadata, seems like a good place.

I'll do that!

> I also discovered a big assumption in a TODO: it assumes that you are combining bands that are already part of the same data cube. So you can not yet add two bands with an entirely different lineage, although I believe that might even be possible.

I don't think that is allowed by the processes anyway, you'd need to resample and merge beforehand and then you can use all bands (in case the names don't collide - should we have a process to rename dimension values? See #50).

> As for the rest of the discussion, it's probably bringing us too far for 0.4.0, so let's get that out of the door first

Would like to, waiting for #44 to be solved ...

**Comment by m-mohr** [comment]
Is this solved? I don't have a clear to do for now...
