### ISSUE TITLE
filter_spatial: clarify behaviour

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes#469]
The filter_spatial process definition https://processes.openeo.org/#filter_spatial is not clear, since it mentions keeping only the pixels intersected by the geometry and later, under the geometries parameter, mentions that no masking is applied.

We need to decide what's the expected output.
Is it only a filter_bbox process that automatically extracts the AOI from the bounds of the geometries?
Is it the same as mask_polygon?

@jdries said that on their side masking is applied, code here: https://github.com/Open-EO/openeo-geopyspark-driver/commit/4e3ef048550bf37b9ed43152d6b8733363cd0f63

We are waiting for a clarification to proceed with this PR: https://github.com/Open-EO/openeo-processes-dask/pull/170

Tagging some other people for opinions:
@ValentinaHutter @dthiex @soxofaan @SerRichard

**Comment by m-mohr** [comment]
I just looked at the git history and it's relatively clear that masking should be applied. The confusing part was added with the datacube changes, i.e. only in 2.0.0 rc1 and thus we should clean that up again to align with the 1.x defintion.

**Comment by m-mohr** [comment]
PR is here: #470

**Comment by soxofaan** [comment]
Indeed I found this discussion where it is clear that intent is to have masking included:
https://github.com/Open-EO/openeo-processes/pull/131#discussion_r368863643

**Comment by clausmichele** [comment]
So the main difference with `mask_polygon` is that filter_spatial may reduce the spatial dimensions and `mask_polygon` not?

@masawdah At the implementation side I think that filter_spatial becomes filter_bbox + mask_polygon internally.

**Comment by soxofaan** [comment]
> So the main difference with mask_polygon is that filter_spatial may reduce the spatial ~~dimensions~~ extent and mask_polygon not?

Indeed.
And note that in the VITO backend implementation we even  infer the spatial extent from `mask_polygon` if no other spatial extent filtering is present in the process graph.

**Comment by m-mohr** [comment]
Yes, and that mask_polygon has additional options, of course.
