### ISSUE TITLE
clip: Document edge cases

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#472]
**Process ID:** clip

**Describe the issue:**

During the test suite creation, I identified that the clip process doesn't mention what happens if min > max for example.

**Proposed solution:**
We should check the tests and document what's missing, e.g. throw an error if min > max? Check what similar processes do, e.g. between.

**Additional context:**
Tests in #468

**Comment by m-mohr** [comment]
What do backends do? @soxofaan @guss84 @clausmichele @LukeWeidenwalker

**Comment by clausmichele** [comment]
In the xarray/dask implementation, if max < min, no error is raised. The base function is provided by numpy, and they explicitly mention this [in the docs](https://numpy.org/doc/stable/reference/generated/numpy.clip.html):
_No check is performed to ensure a_min < a_max._

Anyway, we can agree to raise a predefined error if this happens.

**Comment by soxofaan** [comment]
I don't think we have a check either.
Specifying to throw an error makes most sense to me too

**Comment by m-mohr** [comment]
PR: #477
