### ISSUE TITLE
`aggregate_spatial`: vector cube with different CRS than raster cube

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes#516]
**Process ID:** `aggregate_spatial`

**Describe the issue:**
From the definition it not clear if the `aggregate_spatial` process should work if the CRS of vector and raster cube are not matching.
- If not, how do the user know the raster cube projection to align the vector cube with it (using `vector_reproject`)? Only using `resample_spatial` before would allow to know the projection as  far as I know.
- If yes, should the vector cube be reprojected automatically to match the raster cube CRS?

**Comment by soxofaan** [comment]
I think this is basically this discussion, right?
- https://github.com/Open-EO/openeo-processes/issues/499

**Comment by clausmichele** [comment]
Yes, I didn't see it. Let's continue the discussion over there.
