### ISSUE TITLE
Array process dimensions

### ISSUE THREAD

**Issue by claxn** [Open-EO/openeo-processes#52]
While implementing the processes I am struggling with the definition and input dimensions of the data for processes tagged with _Arrays_. Do they necessarily have to be a list/one dimensional array? I would prefer to make it more generic and use an n-dim array. This means:

- `array_element`: As the index is an integer it must be also one dimensional (except using internal mapping, which would not be very useful). So here we could specify a tuple as a second parameter for indexing the data. 
- `min`, `max`: Both are the only statistical functions tagged as _Arrays_. What about `mean` and the other reducers? These functions implicitly work with n-dim arrays through the `reduce` process, so no changes are needed.
- `sort`, `order`, `rearrange`: If an n-dim array is passed, we need to pass an dimension/axis parameter, which should be used for sorting along. 

I was not involved during the design of these processes, so I do not know if it is intended to be one dimensional.

**Comment by m-mohr** [comment]
Multi dimensional arrays are basically just called data cubes in our world. It is indeed intended as it is and what you are looking for are probably the cube processes such as apply, apply_dimension, filter and reduce.

array_element: I guess filters would be what you are looking for.

min/max: I should probably remove them from the array category, which was meant to just hold general-purpose processes that accept more than a single data type. The array-of-numbers processes are combined in the reducer category.

sort/order/rearrange: What you are looking for is apply_dimension, e.g. `apply_dimension(data, sort(), "temporal")`.

**Comment by claxn** [comment]
Thanks for making this clear. I was thinking on an array level at the back-end and therefore was confused.
