### ISSUE TITLE
aggregate_polygons: coordinate ref system

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#53]
The aggregate_polygons method spec does not mention the handling of the coordinate system of the provided polygons. There are some options:
- Assume by default that polygon crs matches datacube crs
- allow specifying a crs explicitly
- I believe that a geojson featurecollection can have a crs

**Comment by m-mohr** [comment]
The process allows two data types:
* GeoJSON: GeoJSON is always WGS84 as specified in their spec (RFC 7946, ch. 4), so a projection may be required depending on the projection set for the input raster data cube.
* Vector Data Cube: We haven't really spoken about them yet, but I would imagine that they hold CRS information. That would be in line with how we handle raster data cubes.

Maybe we need to clarify the output CRS, but I'd guess it is either restricted by the the output format (if GeoJSON for example) or will be just the CRS of the input polygons.
