### ISSUE TITLE
mask: optional parameter 'mask-dimensions'

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-processes#55]
While writing the process graph for use case 1 with @claxn, we had to mask two cubes with dimension (x,y,t_1,s_1) and (x,y,t_2,s_2)

The mask needed is defined in dimensions (x,y), but following the 'mask' process definition, it has to have the same dimensions as the input raster cube to be masked. So in the process graph, we create the 'same' mask twice.

What about adding an optional argument to the process definition <mask-dimensions:(dim_1, dim_2, ...)>
If this option is present, the back-end knows in which dimensions the mask is defined and will apply it to the input cube for all elements of the other dimensions (t and s in the example above). And if it isn't specified, it would work as currently defined and the back-end would expect the mask to have identical dimensions and cardinality as the raster cube to be masked.

What do you think?

note: the name 'mask-dimensions' can be interpreted in two opposing ways, so if people like the idea, we may come up with a better name for this option.

**Comment by m-mohr** [comment]
Add a parameter dimensions that name which dimensions the mask applies to.

**Comment by jdries** [comment]
Isn't this something that can be inferred by the backend? At least applying a 2D mask to a 3D datacube seems straightforward. 
We could for instance say that the dimension names of the mask should match the ones in the datacube, and missing dimensions simply means that the mask is to be applied for each label of the missing dimension.
Seems to me that this would be easier to use.

**Comment by lforesta** [comment]
this works when the mask is a datacube with its dimensions and I'm happy with this suggestion.

What about when a user want to use a user-uploaded raster as mask? We need to create a cube with dimensions out of it before applying the mask?

**Comment by m-mohr** [comment]
> What about when a user want to use a user-uploaded raster as mask? We need to create a cube with dimensions out of it before applying the mask?

Yes, accepted types for the mask are: geojson, raster-cube (, vector-cube). There's no simple "raster" data type in openEO?!

**Comment by mkadunc** [comment]
I agree with Jeroen - if mask axes are a subset of data axes, we can automatically apply it. If mask has extra dimensions, we should probably fail. Same if mask has missing labels on any of the common axes.

**Comment by m-mohr** [comment]
Anyone up for a PR? I'm a bit lost what the conclusion is...

Is it the following? @mkadunc @jdries @lforesta 
1. Don't add a new parameter?
2. The data cube and the mask have to be compatible, but dimensions can be missing in the mask.
3. Each dimension available in mask must be available in the data cube with the same name, type, reference system, resolution and labels.
4. Missing dimensions in mask means that the mask is to be applied for each label of the missing dimension in the data cube.
5. A GeoJSON is applies on the x and y axis (and z if available in both). 
6. In all other cases the process fails.

**Comment by jdries** [comment]
Yes, looks good to me.

**Comment by m-mohr** [comment]
Okay, waiting for approvals on #110 so that I can base further changes on that.

**Comment by m-mohr** [comment]
See also https://github.com/Open-EO/openeo-processes/pull/110#discussion_r365336523

**Comment by m-mohr** [comment]
Solved in PR #119.
