### ISSUE TITLE
save_result: bands

### ISSUE THREAD

**Issue by claxn** [Open-EO/openeo-processes#59]
I am interested how different back-ends plan to interpret the given data cube in `save_result` and if we need further (optional) parameters for it. For GeoTIFFs it is straightforward, because you can save as many bands as there are in the data cube (if you want to adjust it, you could use a `filter_bands` before). However, for other formats (e.g. PNG) you would need to select the bands that will be used as gray (single-band) or RGB values (three bands). Two suggestions from my side:

- The back-end always interprets three bands as RGB and one band as gray values, e.g.:, if we want to create an RGB image from a multi-band cube, we could first select the bands with `filter_bands` and then order them with `apply_dimension` and the process `order`. 
- The second option would be to have an optional parameter, which directly specifies the selection and mapping of the bands to the colour values, e.g., ['B1', 'B2', 'B3'] -> [R, G, B] (internal mapping) or explicitly, {red: 'B1', green: 'B2', blue: 'B3'}.

What do the (other) back-ends think about this?

**Comment by m-mohr** [comment]
As this is a format specific issue it should be handled as format parameters.
For PNG/JPEG we could do the following:
If there's no band dimension or a single band: Create grayscale image.
If there are more bands: Ask the user to provide explicit mapping in the parameters as you proposed with your second option, e.g. `{red: 'B1', green: 'B2', blue: 'B3'}`.

**Comment by m-mohr** [comment]
I think there's no todo here. Feel free to reopen if I am wrong.

**Comment by lforesta** [comment]
Currently I think save_result() is a bit too undefined. 
The general question for me is, when the output of a job is a datacube with more dimensions than simply (x,y) - i.e. when there are essentially n rasters - should the back-end save one file with n rasters or n files with 1 raster?
With a Gtiff you could do either, and I guess with many (all?) other formats too.

**Comment by m-mohr** [comment]
That's up to be described in /file_formats. Save results is file format agnostic and therefore shouldn't describe such things. Also, this may be back-end dependent.

**Comment by mkadunc** [comment]
I agree that this depends on the file format, but nevertheless we should have some guidelines on how to convert a generic data cube into most common data formats such as geotiff.

Right now we make the following assumptions:
- `x` and `y` dimensions are spatial, encoded into output image columns and rows, respectively
- `t` dimension is used for naming the resulting files (one output file per `t` dimension value)
- `band` dimension results in layers/components/bands of the resulting images

We use `datatype` option to specify encoding of the values in the data cube (values are consistent with GDAL's `GDT_*`).

**Comment by m-mohr** [comment]
Telco: @lforesta will write a best practice and add it here. Afterwards, we put it into the API best practice document, which I'll initiate once I finished https://github.com/Open-EO/openeo-api/issues/231

**Comment by lforesta** [comment]
Currently, users have no knowledge of how many files they will receive (and what exactly will be in it/them) after using save_result, as the behavior of this process is left to the back-end.

Let's assume that the job output is composed by more than one raster, i.e. it is a datacube with dimensions (x,y,A,B, ...) where dimensions A, B, ... have more than one element (a typical example is a timeseries with multiple bands).
We agreed on the following:
- the back-end freely decides how to save and return job outputs, but it MUST expose on /output_formats information on how datacubes with mutliple dimensions will be offered to the user (e.g. one file per timestamp per band; one file per timestamp with n bands in each, etc ...)
- generally we define best-practice to save one file per timestamp (each file may contain multiple bands, or whichever other dimension)

**Comment by m-mohr** [comment]
Follow-up at https://github.com/Open-EO/openeo-api/issues/241
