### ISSUE TITLE
Make aggregate_polygon more general

### ISSUE THREAD

**Issue by kempenep** [Open-EO/openeo-processes#62]
https://github.com/Open-EO/openeo-processes/blob/cee65f77dece8568e350e65a67c9761a254e1aca/aggregate_polygon.json#L1

I would like to suggest to rename the process aggregate_polygon to aggregate_spatial
Some motivation:
1) more in line with aggregate_temporal, where we aggregate in spatial rather than temporal domain
2) polygon parameter should not necessarily be of "polygon" type. Different type of features can be used. Even point features might be useful here. 

An extra parameter "buffer" could also be useful (positive: polygon gets extended, negative: polygon is reduced ). In case of point features, a positive buffer allows to calculate zonal statistics around the specified points

**Comment by m-mohr** [comment]
This is made to align with filter_polygon, because we are also discussing to add filter_point etc. There could also be aggregate_point then. They may have different semantic and parameters.

The buffer parameter is another issue that should be in a separate issue.

**Comment by kempenep** [comment]
My preference would still be the more generic "aggregate_spatial", as it does not restrict to a single feature type. For instance, we might want to aggregate SQLite vectors that combine different feature types (polygons, points, ...) in different layers.

**Comment by m-mohr** [comment]
Could you please propose a concrete and complete process definition according to our /processes endpoint, incl parameters and schemas for it? 

If we change, it we should also tackle filter_spatial and #37.

**Comment by kempenep** [comment]
I do not seem to have write permission to create new feature branch:
remote: Permission to Open-EO/openeo-processes.git denied to kempenep.

Attached the process definition candidate

Op vr 7 jun. 2019 om 15:14 schreef Matthias Mohr <notifications@github.com>:

**Comment by m-mohr** [comment]
Attachment via mail didn't get through, unfortunately. You can get write permissions or fork an PR or use the GitHub Web interface to upload to this issue.

**Comment by lforesta** [comment]
Telco conclusion
create a new process "aggregate_spatial" that accepts any type of feature, including point
deprecate current "aggregate_polygon"
@kempenep to create PR

**Comment by m-mohr** [comment]
I'm curious to see in that PR how aggregations for points and line strings work. Without defining those cases clearly, it doesn't make sense to change the processes at all.

**Comment by lforesta** [comment]
it basically would be an interpolation at that point or the points on the line

**Comment by m-mohr** [comment]
Thanks. In that sense, we could also apply the more general rule also to mask, filter_polygon and load_collection.

**Comment by kempenep** [comment]
Pull request created.

**Comment by m-mohr** [comment]
There's a new proposal in PR #131
