### ISSUE TITLE
Rename apply_dimension? 

### ISSUE THREAD

**Issue by kempenep** [Open-EO/openeo-processes#63]
https://github.com/Open-EO/openeo-processes/blob/cee65f77dece8568e350e65a67c9761a254e1aca/add_dimension.json#L8

in apply_dimension, the parameter 'dimension' refers to: "The name of the dimension to apply the process on." Would it not be more consistent to also use "dimension" in add_dimension (instead of "name")?

**Comment by m-mohr** [comment]
I'm grouping the processes into two categories:
1. Processes that work on pixel values (e.g. apply, apply_dimension, reduce, resample_* etc.) - These are all using `dimension` as parameter name.
2. Processes that alter the data cube model (e.g. rename_dimension, add_dimension, etc.) - These are all using parameter names without dimension included as it should be clear that the context is a dimension.

Therefore, this is consistent in my opinion. I rather would say apply_dimension is a bad name for the process and may want to rename it.

**Comment by kempenep** [comment]
Agreed, renaming apply_dimension seems a good idea

**Comment by m-mohr** [comment]
What would be a suitable name?

**Comment by kempenep** [comment]
One option would be to just use one name "apply" for both and make behavior depending on the parameter "dimension", which would then be optional. A similar behavior can be seen in numpy, with the parameter "axis", e.g., numpy.sum()

**Comment by m-mohr** [comment]
That doesn't work very well because of the different types of callbacks (single value VS array of values), I think.

**Comment by lforesta** [comment]
what about simply apply_nary or apply_n-ary ?

**Comment by m-mohr** [comment]
`nary` doesn't seem to be very commonly known, I think. We all know it from the process specification process, but I am not sure whether it would be well understood by our target audience.

**Comment by MilutinMM** [comment]
Maybe apply_along_Dimension?
