### ISSUE TITLE
apply_kernel: clarify documentation

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#69]
Some feedback after implementing apply_kernel:
* There actually seem to be multiple ways in which a kernel can be applied, but I believe we are referring to a 2D convolution. This can be mentioned more explicitly. Probably may make sense to reference more elaborate explanations like: http://www.songho.ca/dsp/convolution/convolution2d_example.html
* The spec says that the kernel should have the same dimensions as the datacube. The most logical case however is to have a spatial 2D kernel, and to apply that kernel on the 2 spatial dimensions. We can then also allow backends to support xD kernels, if they want to do that. This reduces complexity for the user and backend implementors, as they don't have to worry about higher dimensional kernels.
* Applying a kernel is only properly defined if the kernel has uneven dimension. Currently my implementation throws an exception when trying for instance to use a 2x2 kernel. The docs can mention this, or we should come up with a convention on how to handle kernels with even dimensions.

**Comment by m-mohr** [comment]
Solved in PR #118
