### ISSUE TITLE
filter_daterange: Detail time intervals

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-processes#7]
Please detail how time_intervals are to be interpreded in filter_datarange.
Note that halfopen intervals: [from,to[ are very convenient when needing to specify subsequent, non-overlapping time ranges. This is almost impossible with closed intervals, unless if you know the exact temporal resolution at which the intervals are evaluated.

**Comment by edzer** [comment]
I agree with @jdries that for time, left-closed intervals (containing the minimum but not the maximum) are the way to go. It corresponds to how ISO 8601 interprets time intervals.

**Comment by m-mohr** [comment]
I consider this solved until any further comment comes up.

**Comment by m-mohr** [comment]
> I agree with @jdries that for time, left-closed intervals (containing the minimum but not the maximum) are the way to go. It corresponds to how ISO 8601 interprets time intervals.

@edzer Do you have a source for this? I can't really find any full-text PDF for the ISO standards, but the excepts that I find actually seem to indicate the opposite (i.e. the maximum is included)
