### ISSUE TITLE
inverse trigonometric process - id inconsistency?

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-processes#71]
I just realized the inverse trig functions names seem inconsistent, is this behavior wanted?

**arc**cos
**arc**sin
**arc**tan
**arc**tan2
arcosh -> **arc**cosh
arsinh -> **arc**sinh
artanh -> **arc**tanh

Else we could update the names of the last three in the list

**Comment by m-mohr** [comment]
I followed ISO 80000-2, see https://people.engr.ncsu.edu/jwilson/files/mathsigns.pdf page 25.
