### ISSUE TITLE
create 0.4.2 tag

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#76]
I guess openeo-api and openeo-processes grow and live in synchronicity but there is no 0.4.2 tag for openeo-processes at the moment:

![Screenshot from 2019-09-05 10-00-17](https://user-images.githubusercontent.com/44946/64323068-07a05b00-cfc4-11e9-85a3-7eb2caa3204b.png)

(also, minor issue: on openeo-api the `v0.4.2` tag starts with `v` while the others do not, do we follow a convention for tagging?)

**Comment by m-mohr** [comment]
Oh, thanks for spotting the missing release. Seems I missed that. I guess the releases here should start also with a v although we don't have a convention. Is it important for anything you are working on?

A note on versioning: The processes and the API versions are not necessarily aligned, i.e. there may be a 0.4.3 on any side without a parallel version on the other repository.

**Comment by soxofaan** [comment]
> Is it important for anything you are working on?
not really at the moment, it just looks inconsistent

> The processes and the API versions are not necessarily aligned
Aren't they tied implicitly because proceses is a submodule in api and the way the documentation is built?

**Comment by m-mohr** [comment]
Yes, still somewhat tied, but looking for ways to improve that and have them less coupled.
