### ISSUE TITLE
"Common" band names

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-processes#78]
In the documentation for `filter_bands` it should be mentioned that "common names" refers to **the STAC spec's** common names.

(So far it's only a "See also" link -- if a hint to that would be directly in the parameter's description that would be a lot more prominent/helpful.)

**Comment by m-mohr** [comment]
Commits https://github.com/Open-EO/openeo-api/commit/2e283eab843aee95eca389d3a359de9c75d1d4a5 and e27a460cbe3fde72f2e4437ede6794615ba5577d should solve this issue.
