### ISSUE TITLE
Reduce with multiple return values

### ISSUE THREAD

**Issue by claxn** [Open-EO/openeo-processes#81]
@m-mohr and I struggled finding a clear definition of what happens with the dimension when a reducer returns multiple values. In my opinion the dimension over which is being reduced is either replaced if no `target_dimension`  is given or a new dimension is created. The requested dimension should then contain the outputs of the reducer. E.g. for a datacube with the dimensions `x,y,t,b` and a reducer `extrema` with a target_dimension `p` applied on `t` you should get an updated datacube with `x,y,p,b` as the new dimensions and `min` and `max` as values/indizes along the new dimension `p`. Do other backends agree with this approach or have you implemented it already in a different way?

This brings me to my second question. At the end of the process graph you can save the computed results. Continuing with the example from above it will be necessary to reduce dimension `p` in the end if you want to visualise the `min` OR `max` value for different bands along `b`. But if you want to finally reduce over the bands to be able to visualise the `min` or `max` for one band,  what should happen with the datatype of the remaining dimension? I would suggest that if no dimension with the datatype `band` is available anymore the last dimension gets automatically labelled with the datatype `band`.

**Comment by m-mohr** [comment]
So this seems to be mostly a documentation update.
One thing to clarify: How do we determine the dimension values (min and max in the example above)? extrema returns an array with the min, max values, but other processes have a different semantic.

**Comment by claxn** [comment]
@m-mohr : If the return values of the process are clearly defined I would go for a strict labelling, e.g. `{"min", "max"}`. If not, I would use a range of integer values equal to the length of the returned values.

What I am still not sure about: 
In the end, when you want to save the result, what dimensions are you allowed to specify to visualise the result? I would say it is allowed to specify any dimension, as long as the result is unique, i.e. the data cube has been filtered before. How should we handle (the) spatial dimension(s)?

**Comment by m-mohr** [comment]
@claxn What does "strict labelling" mean? Is the return value of `extrema` an object instead of an array? That is problematic, we don't have processes to work with object. Or do we pass dimension values (min, max) in the reduce process?

I don't get the last issue, but it seems to be not related to this issue and should be discussed separately.

**Comment by claxn** [comment]
@m-mohr: I thought `extrema` returns two arrays which are located along the reduced dimension. The first one is labelled with `min` and the second one with `max` ("strictly" defined by the process itself, which could be specified in the process description). This would also align it in a way how GEE handles such operations. If a user does not like this labelling, he/she could rename it afterwards with a process, which is currently not defined (similar to `rename_dimension`, but working with the actual dimensional values).  Does this make sense?

My second concern is related to my second question at the beginning (but yes, maybe it would make sense to create a separate issue):
E.g. there is one image/layer in my data cube, which has the dimensions x(...),y(...),t(2016-01-01),b(1). Now I want to save/visualise it and for doing so I could use: 
- b=1
- t="2016-01-01"
In my opinion both should be possible, as long as the requested "image" is 2D, i.e. unique along other dimensions than space.

**Comment by m-mohr** [comment]
@claxn Extrema returns two numbers, see the examples: https://open-eo.github.io/openeo-api/draft/processreference/#extrema

**Comment by claxn** [comment]
@m-mohr: Yes, but I think this should differ in the context of a reducer. reducer -> extrema should trigger a labelling as suggested above. I don't know whats the best solution to achieve this, but then at least it could be easier to address dimensional values after a reduce operation.

**Comment by m-mohr** [comment]
Telco: The dimension labels will just be enumerated. So for extrema, the resulting dimension will have labels 0 and 1, where 0 is basically min and 1 is basically max. With a new process it will be possible to rename the labels afterwards.
