### ISSUE TITLE
Separate binary operators (add, multiply...) from reducers (sum, product...) and revise definitions

### ISSUE THREAD

**Issue by mkadunc** [Open-EO/openeo-processes#85]
When implementing the reducer processes — `sum`, `subtract`, `multiply`, `divide`, `and`, `or` and `xor` — we realized that both the description of the processes and their usage would benefit from separating the binary case from the aggregate (reducer) case. We have a couple of arguments:

- `ignore_nodata` as default is intuitive and useful in the aggregate case (`a1 + a2 + a3 ...`). However, when evaluating an expression with two distinct values (e.g. `B08 + B04`), as a user I expect a `no_data` input to yield a `no_data` output, and I believe this should be the behaviour for all binary operators and that we don't even need to have the `ignore_nodata` flag in the binary case.

- `divide` and `subtract` should not be reducers — in both, the first element is special and treating repeated division (or subtraction) as an aggregate operation will confuse many users (there's the additional problem of how `no_data` should be ignored when it's the first value in the array) - we've decided against positional arguments in openEO, and we're forcing them back through this weird division and subtraction processes

- `xor` as a reducer should either be removed, or renamed to `oneTrue` or `oneHot` or similar. Repeated application of `⊻` to a list of booleans gives `true` iff the list contains an odd number of `true` values (e.g. `(T ⊻ T) ⊻ T = F ⊻ T = T`), which is different from the current openEO xor definition. This discrepancy could unnecessarily cause problems in implementation of the processes and in their usage.

- results of boolean operations are not well defined when all elements are `no_data` (the text suggests that `and[no_data]` should return `FALSE` which is inconsistent with both the requirement that an empty array should yield `no_data`, and with maths, which suggests that `and[] = TRUE` to satisfy associativity)

- `sum` and `multiply` needlessly require at least two elements, and throw an exception otherwise - the aggregate functions should be useful in a dynamic process graph where the user shouldn't have to guarantee that a certain number of elements will be present (data availability is not predictable, especially in e.g. cloud-filtered time series) - I believe that `no_data` result would be the best compromise for an empty array (mathematically, `sum[]` could also be 0, but if we make it consistent and define `multiply[] ==1` that might be counter-intuitive)

I suggest the following names for the above-mentioned processes:

| binary | reducer  |
|--------|----------|
| and     | [all](https://www.rdocumentation.org/packages/base/versions/3.6.1/topics/all) |
| or       | [any](https://www.rdocumentation.org/packages/base/versions/3.6.1/topics/any) |
| xor |  |
| add | sum |
| multiply | product |
| subtract | |
| divide | |

**Comment by mkadunc** [comment]
Adding a couple of links for potential discussion around using neutral values as a result of reducing an empty array:
- [Wikipedia - Empty product](https://en.wikipedia.org/wiki/Empty_product#In_computer_programming) [Empty sum](https://en.wikipedia.org/wiki/Empty_sum)
- [Python prod](https://docs.python.org/3/library/math.html#math.prod) `prod([])=1`
- [R prod](https://www.rdocumentation.org/packages/base/versions/3.6.1/topics/prod#l_value) `prod()=1`
- [Python all and any](https://docs.python.org/3/library/functions.html#all) `all() = TRUE`, `any() = FALSE`
- [R all](https://www.rdocumentation.org/packages/base/versions/3.6.1/topics/all) `all()=TRUE`, `any() = FALSE`

**Comment by m-mohr** [comment]
Telco: We agreed on this proposal, but we'll return null (no data) for reducers which an empty array was passed to. Binary processes have no ignore_data parameter so that null is returned whenever one of the values is null. We may discuss renaming ignore_nodata later.

**Comment by mkadunc** [comment]
With binary and and or, a single null can still produce a non-null result (true || null = true, false || null = null)
