### ISSUE TITLE
Source of truth for band (dimension) metadata

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#86]
While working on band (metadata) related issues in python client and driver, I'm bit confused about the "best" source to find band metadata:

from the collection metadata example in the openEO spec:

                    "properties": {
                      "cube:dimensions": {
                        ...
                        "spectral": {
                          "type": "bands",
                          "values": [
                            "B1",
                            "B2",
                      ...
                      "eo:bands": [
                        {
                          "name": "B1",
                          "common_name": "coastal",
                          "center_wavelength": 0.4439,
                        },
                        {
                          "name": "B2",
                          "common_name": "blue",
                          "center_wavelength": 0.4966,
                        },

There is:
- `properties > cube:dimensions` which can have a dimension of type "bands", called "spectral" in the example, listing the names of the bands under `values` 
- `properties > eo:bands` which is a list of objects with band name, common name and even wavelength
- note the duplication of band names 

This metadata is used in processes, e.g.:
- In the `filter_bands` process there is a (recommended) argument `common_names`, for which the common names from `properties > eo:bands`  must be used (I assume, I'm not sure if this is specified somewhere).
- In the `reduce` process there is a `dimension` argument, for which a key from  from the `properties > cube:dimensions` object should be used (as specified in spec)

Is there a way to better centralize this band/dimension metadata and have a single source of truth without duplication/redundancy?

related: Open-EO/openeo-api#208, Open-EO/openeo-python-client#76, Open-EO/openeo-python-client#77, Open-EO/openeo-python-client#93, Open-EO/openeo-python-driver#25

**Comment by m-mohr** [comment]
Transferred as I don't see more room for improvement for the processes, not the API itself.

**Comment by m-mohr** [comment]
Made minor clarifications.
