### ISSUE TITLE
Split binary and array based reduction?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-processes#94]
@mkadunc wrote in #89:
> I'm starting to think that we should move the 'binary' reduce into a new process (e.g. called 'fold' ) and describe the mechanics there (I know this is not the best place to start this proposal - will raise it in the meeting today)

It seems we forgot to discuss it today, but is a good topic to discuss next time. Still add your comments here in the meantime.

**Comment by mkadunc** [comment]
Regarding the name: [fold](https://en.wikipedia.org/wiki/Fold_(higher-order_function)) is what Wikipedia uses, and is also the most frequent name for this function in languages that do not use "reduce". I don't know of any uses of "fold" in programming that would be inconsistent with the behaviour that what we're after.

Note: this issue may be viewed differently depending on what we decide about merging the multi-output-reduce and apply_dimension (see https://github.com/Open-EO/openeo-processes/issues/73 )

Reasons why I think splitting would make sense:

- we have a lot of difficulty with defining the behaviour and purpose of `reduce` even when considering just the variant where callback takes an array

- we have not yet discussed and considered in as much detail the binary variant, I suspect if/when we do, we will find the current description deficient in many ways

- imo `reduce` would be easier to understand for the users if there was clearly a single mode of operation, with corner cases and examples all dedicated to that same mode

- the mechanics of binary reduce (fold) are sufficiently different from the mechanics of array reduce that calling one or the other is not something that the user would be uncertain about

- the 'binary' parameter is so strongly coupled with the 'reducer' parameter that changing the operation mode from one to the other should only be done very deliberately — the kinds of changes this requires for the callback feel reasonable when changing the process, but more difficult to justify when flicking a single boolean parameter

- by packing a lot of fundamentally different functionality into a single process we're risking that the users and implementors will make mistakes and wrong assumptions — good APIs and SDKs should try to protect users from such risks

**Comment by m-mohr** [comment]
@mkadunc I like the idea as it makes the processes more streamlined as you said. I'm not sure whether a completely new name makes sense as the binary variant still will be quite similar to the array reduce, so I think reduce_binary could also be an option. One important thing to keep in mind is that there are more processes with the binary option: `aggregate_polygon`, `aggregate_temporal`, `resample_cube_temporal` and `merge_cubes`. We need to think about what to do with them and if we split up those, too, it probably makes even more sense to just name them xxx_binary?!

**Comment by m-mohr** [comment]
Another idea is to split the two reduce use cases (one return value / multiple return values => new dimension). Anyway, I need to check whether the mentioned processes above all adopted the multiple return values changes we integrated recently for reduce.

**Comment by lforesta** [comment]
Telco conclusion:

we decided to have two separate processes for reduce_binary (or whichever name) and reduce

**Comment by m-mohr** [comment]
Thanks for the conclusion, @lforesta. Unfortunately, the conclusion is incomplete as it doesn't say what to do with the similarly defined processes `aggregate_polygon`, `aggregate_temporal`, `resample_cube_temporal` and `merge_cubes`! Have you discussed this?

**Comment by lforesta** [comment]
> processes aggregate_polygon, aggregate_temporal, resample_cube_temporal and merge_cubes! Have you discussed this?

of those, we discussed only aggregate_polygon #62

**Comment by m-mohr** [comment]
Then we need to discuss this again as the binary reducers are similarly defined in all the mentioned processes. Just changing it in reduce doesn't help much.

**Comment by m-mohr** [comment]
Telco: Only aggregate_polygon and reduce are expected to handle really large amounts of data and thus need the binary parameter. We'll split those two processes and remove the binary behavior from the other processes.

**Comment by m-mohr** [comment]
Hey @mkadunc and others,

I'm working on this now and I'm wondering what would be the best option for merge_cubes. Isn't it better to use the binary behavior as default as you have two inputs? So here it may make sense to remove the "unary behavior" or am I'm missing something? If you still want to use mean as reducer it's simpler to create a new array in JSON than using array_element to split an array into two separate values for binary processes... What do you think?

**Comment by mkadunc** [comment]
I agree with https://github.com/Open-EO/openeo-processes/issues/94#issuecomment-575085785.

As long as the `merge_cubes` remains limited to two cubes, having only binary overlap resolver makes more sense. The array reducer (unary) option would be useful in case we wanted to support merging of more than two cubes, but I don't see a pressing need for that.

**Comment by m-mohr** [comment]
Here's the PR: #123
